### ISSUE TITLE
PullRequests without mention / participation are shown in "Participated"

### ISSUE THREAD

**Issue by Luzifer** [ptsochantaris/trailer#133]
Currently I observe the behavior that some PullRequests are shown in the "Participated" section even I am not mentioned in that PullRequest or any commit of it and I did not participate (like in comment, clicked "watch" or something) on it.

This happens only for a few PullRequests and I didn't observe a pattern yet.

**Comment by ptsochantaris** [comment]
Hi and sorry for the very late reply. I've just put up version 1.2 which is a big rewrite and should address a lot of these smaller issues. You can find it here for now: #176 Please give it a go and see if this behaviour improves at all. I'm going to close this issue for now but please feel free to re-open if it keeps occurring!
