### ISSUE TITLE
An amazing 9223372036854775807 PR's reported during network brief network issue

### ISSUE THREAD

**Issue by dylang** [ptsochantaris/trailer#161]
![screen shot 2014-11-03 at 7 50 13 pm](https://cloud.githubusercontent.com/assets/51505/4926194/65aad480-6531-11e4-9e59-311e8c16e2dd.png)

I think this was right after booting and the network wasn't yet connected.

**Comment by ptsochantaris** [comment]
Wow (and sorry for the very late reply) - well, the code has now been completely cleaned and re-written for version 1.2, whose Release Candidate is up now here at #176 - perhaps this will also correct this issue for you as well? Give it a go and let me know. I'll close this issue for now but please feel free to re-open it in case this happens again!
