### ISSUE TITLE
Slow with > 500 PRs in the recently closed section

### ISSUE THREAD

**Issue by akatz** [ptsochantaris/trailer#169]
My entire computer slowed to an unusable pace until I removed the bulk of PRs in trailer.

**Comment by ptsochantaris** [comment]
Hi, the release candidate for version 1.2 is up now and should hopefully improve this situation. If you'd like to give it a go before it becomes widely available for auto-update, please check out this thread: https://github.com/ptsochantaris/trailer/issues/176
