### ISSUE TITLE
Missing labels

### ISSUE THREAD

**Issue by cheba** [ptsochantaris/trailer#170]
I'm not sure what actually is going on but I've noticed that labels are not always displayed. Compare these screenshots:

![screen shot 2014-12-08 at 6 29 27 pm](https://cloud.githubusercontent.com/assets/7405/5342850/e3caa1b4-7f09-11e4-8efd-4456b14c3eae.png)
![screen shot 2014-12-08 at 6 29 48 pm](https://cloud.githubusercontent.com/assets/7405/5342851/e3cae926-7f09-11e4-8e7c-8d77083bcf3c.png)

It looks like every label is displayed only once.

**Comment by ptsochantaris** [comment]
Hi, @cheba and once again thanks for all the help with testing! The release candidate for version 1.2 is up now and should hopefully solve this issue. If you'd like to give it a go before it becomes widely available for auto-update, please check out this thread: https://github.com/ptsochantaris/trailer/issues/176

I'm marking this issue as closed for now, but looking forward to any more suggestions you may have or fixing issues you may spot!
