### ISSUE TITLE
Allow settings to be exported/synced across multiple devices

### ISSUE THREAD

**Issue by bkuhlmann** [ptsochantaris/trailer#173]
It would be nice to allow settings to be sync'd across multiple devices (via Dropbox, Box, etc.). Similar to how [Alfred](http://www.alfredapp.com) works, perhaps.

This would accomplish a couple of capabilities:

0. Keeping the same settings across multiple machines (i.e. office, home, travel machines).
0. Automatic backup of settings for loss of machine or rebuilding of new machines.

This would require a few additional enhancements:

0. The repository list might need to support profiles. For example, when at work, I'd only want to see work related repos and alerts. When at home, I'd only want to see open source projects. For consultants, this could be a boon as it would allow them to toggle the repository list by client (profile) for an way to stay in perspective.
0. Settings would probably need to be broken down by *global* and *device-specific* (per profiles idea mentioned above) so there is no additional tweaking when switching devices.

**Comment by ptsochantaris** [comment]
Sorry for the slow reply - I'll just say it's been a weird month and leave it at that :)

Profiles and exporting settings is something I think about a lot TBH, so I'm glad you brought this up, perhaps we may end up doing something about it!

I've often thought about adding iCloud sync for settings - apart from the problem of not being a Mac App Store app, what you describe as the extra functionality for profiles is another big sticking point - people may want to watch different things on their device and on their Mac (or Devices and Macs) iCloud sync, would be a 'in-or-out' proposition (even if it could be added to the OS X version) which would make this hard.

I'd think a relatively solid compromise would be to allow importing and exporting all the settings from an instance of Trailer into/from a file ("Work.TrailerProfile", or "Home.TrailerProfile"). Consultants could have a directory of profiles which they can "load up" by double-clicking on them, and device users could also save/load them via the iOS8 file providers, such as iCloud drive, Dropbox, etc.

(Doesn't cover the idea of automatically backing up settings of course, but that may be a bit too complicated to quickly add at this point. Entirely possible of course to have an option like "Overwrite last exported profile with new when settings are updated" perhaps?)

What are your thoughts on this so far?

**Comment by bkuhlmann** [comment]
No worries, I've been traveling so I've failed to uphold my end of being responsive. :)

Yeah, I love the first step of being able to export/import `*.TrailerProfile` files. One could easily save these *profiles* in a sync'd folder (i.e. managed via iCloud, Dropbox, etc) which takes care of making these profiles available on multiple machines.

Ultimately, I would imagine sync management isn't something the Trailer app would want to be concerned with. Only that it expects `*.TrailerProfile` files to always exist at a relative path. That said, I understand your point about having iCloud specific support which would make managing settings across devices easier. Although, apps like [1Password](https://agilebits.com/onepassword) and [Day One](http://dayoneapp.com), for example, manage to make use of the same file system whether you are on an OSX machine or iOS device which is a nice touch. Using these apps as examples would allow you to be sync-system agnostic, hopefully (I admit, I don't fully understand the intricacies of iCloud, though).

In terms of backups, maybe you don't have to be concerned about this either? For example, I have Carbon Cloner Backups running nightly on my machines, so if I were to accidentally hose my `*.TrailerProfile` settings, I could easily restore. I realize that not everyone might have a backup strategy so can understand the appeal of Trailer doing this for everyone. ...but you could definitely punt on that feature until later based on demand/further feedback from your user base.

I like your suggestion regarding "Overwrite last exported profile with new when settings are updated". That's great. In the case that one leaves this option unchecked, you might want to provide a "Save Settings/Profile" button that only displays when changes are detected so people can manually update if they desire.

One last suggestion, since there is potential for multiple profiles, it might be nice to allow for quick profile switching. For example, in Sublime Text, one can use the `CONTROL+COMMAND+P` keyboard shortcut for a quick list of projects to switch (fuzzy matching included). It would be neat to see this option in Trailer too. I could see myself wanting to quickly toggle between work and open source work, for sure. Icing on the cake, though. :)

**Comment by ptsochantaris** [comment]
Right - yes, I think by using profile files we don't need to worry about their ubiquity, it can be a filesystem thing (considering Trailer is a tool for non-novice or casual users).

iCloud profiles would solve a big sticking point for me personally, by keeping all my iOS devices settings synced with my OS X machine - but the profile file solution should also take care of this now that iOS8 allows filesystem document providers.

Like you say, embedding profile switching in the app may be a step too far for it's current state of functionality and scope - although never say never :) - but yes, I'd rather stick to just associating profile files and letting their "opening" trigger the profile change for now.

Stay tuned for this - it's not going to come very quickly but it's something I will work on :+1:

**Comment by bkuhlmann** [comment]
Awesome, thanks! Yeah, no worries, as a OSS maintainer, I understand. If you need an extra tester, let me know. :)

**Comment by ptsochantaris** [comment]
Hi, I've made some progress with this feature on the latest 1.3 test build here: 
https://github.com/ptsochantaris/trailer/pull/185

It's only on the OS X build for the moment (although the plan is to have this in the 1.3 iOS release as well), and it needs some refining (right now importing a new set of settings will cause a full re-sync, with notifications posted, etc), but if you feel adventurous and can risk trying out a test build your suggestions and/or bug reports would be more than welcome of course.

**Comment by bkuhlmann** [comment]
Thanks. API Key is backed up and new version is installed (have the beta installed on two machines at the moment).

![trailer preferences](https://cloud.githubusercontent.com/assets/50245/6994084/5e7bd25a-dac9-11e4-88dd-1a6e9bc445f5.png)

BTW, the use of `file:///` being displayed in the "Misc" settings...I assume you want to be explicit in showing this detail due to future protocol support?

Thanks for keeping the settings in a plist format, makes it easy to script (if necessary).

Will log issues as I find them (if any) and play with this more.

**Comment by ptsochantaris** [comment]
Hi, really glad you are liking the feature! I was just exposing it in the iOS UI which was a big pain-point for me, as I've got PocketTrailer both on my iPad and iPhone and keeping all the settings synced-up was getting tiring :)

BTW I realised later that I hadn't told you where to find the options for this feature, I'm glad you found them, that preferences window is getting a bit cluttered.

Yes, the file:/// prefix is there because of the way the OS deals with paths. Basically all file operations are URL-based, and I was thinking that some users, especially power users, may use filesystem extensions that allow loading and saving from schemes other than file://  I may improve the appearance before the 1.3 final, though, possibly colouring/graying in various scheme/host/path/filename components.

Thanks for the testing and the two separate issue reports - hopefully the next build tonight should fix the issues, keep calling them in!

**Comment by bkuhlmann** [comment]
Yeah, the work you are doing is really helpful. Happy to help. I'll keep an eye out for the new build updates and send any feedback I can.

**Comment by ptsochantaris** [comment]
Version 1.3.0 is now live and includes this feature, so I will close this, but please feel free to re-open in case there are further problems problems, or feel free to open a new issue.

Thanks for all your testing and help getting this working. If you have further thoughts on expanding this or other useful features please keep opening issues!

You can upgrade your version either from here: http://ptsochantaris.github.io/trailer/trailer130.zip or more easily from About -> Check for updates
