### ISSUE TITLE
Count on Mac menu bar is updated even though nothing has changed

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#174]
I use [Bartender](http://www.macbartender.com/) for Mac with Trailer in the Bartender bar.  I would like to use the option to show in Mac Menu Bar on changes; however, it appears that Trailer updates the count on its menu bar icon even though the value hasn't changed causing Bartender to see it as a change to the icon.

It would be good if this update to the menu bar icon old changed when the value really has changed.

![screen shot](https://cloud.githubusercontent.com/assets/6276072/5888376/a531b9d4-a3ca-11e4-83a4-e3aabe40e94f.png)

**Comment by ptsochantaris** [comment]
Yes, technically Trailer (and I'm guessing a lot of other apps) will update the menubar when various things occur internally to ensure it's displaying the right thing, such as when a sync occurs - since the redraw cost is negligible, there is no checking on whether an actual redraw needs to occur. I didn't realise that this would be an issue with Bartender though :)

I don't know if this will make the upcoming version, but I will keep it in mind for the next set of features to be worked on, so most probably the release after the upcoming one.

**Comment by ptsochantaris** [comment]
Was just working on this, and realised that despite putting code checks in to ensure no updates are done without the need to refresh, what you probably need is an option to disable the indication when Trailer refreshes, which grays the count in-and-out, and I guess that would make Bartender put it in your menu bar again. So, I will add that :)

**Comment by ptsochantaris** [comment]
The option is now added and will be in the next release - here's an intermediate build with the new feature added (it should work as well as the official build) Have a go and let me know if it improves the situation with Bartender: 

https://www.dropbox.com/s/y5uqv7uxtarb3fc/Trailer-DoNotGrayOutOption.zip?dl=0

Be sure to first disable the refreshing graying-out from Preferences -> Display -> Gray-out PR count in the bottom right.

**Comment by cgatesman** [comment]
That did the trick!  Working perfectly with Bartender with that option turned off.  Thanks you!

**Comment by ptsochantaris** [comment]
Excellent news! The next release (which will be soon as it seems there is a small bug for some user's displays) will have this as standard, meanwhile feel free to use this build - it's identical with the release apart from that option, and you will get notified of updates normally, etc.

**Comment by ptsochantaris** [comment]
Hi, version 1.2.1 is up, which includes this feature. Will close this issue for now, but please feel free to re-open if you encounter any issues with it. Thanks again for reporting this!

**Comment by cgatesman** [comment]
:+1: :beers:
