### ISSUE TITLE
Version 1.2 Release

### ISSUE THREAD

**Issue by ptsochantaris** [ptsochantaris/trailer#176]
Because it is a large update and rewrite, I'm being cautious about immediately releasing 1.2 over auto-update. It can be manually downloaded here:

http://ptsochantaris.github.io/trailer/trailer120.zip

What's new:
- A major re-write in Swift, with a cleaned up codebase, meaning more performance, maintainability and stability. A big callout to @cheba and @mauricerkelly for their testing and feedback during this big undertaking!
- Using native table views on OS X for big memory and performance wins
- New option to filter using labels and statuses
- Lots of small bug and corner-case fixes, especially in syncing and labels and statuses
- Important performance improvements throughout
- Properly signed, no longer need to right-click open on first download

If you're feeling adventurous, you can try it out and report any serious issues you may encounter in this thread, so we can proceed and push this build out to all users.

Notes:
- OS X 10.8 is no longer supported
- Once you upgrade to this version, you will not be able to downgrade to the previous version without losing your server/repo configuration. If you want to play it super-safe, keep a copy of your old version of Trailer, plus ~Library/Application Support/com.housetrip.Trailer directory, and overwrite the new ones in case you want to downgrade.

**Comment by cheba** [comment]
Vibrancy mode still need some polish, I'd say.

**Comment by cheba** [comment]
It's weird… I can't get a screenshot of what I'm seeing to demonstrate it.

In vibrancy mode hovered item is lighter than others. Its light background clashes with the number on the left side of the item.

But on screenshots it looks darker and so the number looks just fine.

**Comment by dylang** [comment]
That is funny how it changes color when trying to screenshot.
I captured it using [LiceCap](http://www.cockos.com/licecap/). 
![trailer-highlight](https://cloud.githubusercontent.com/assets/51505/6098214/069ffb54-afa6-11e4-8869-5d5b4660d8f8.gif)
So far this beta seems great. I'm happy to see Github Enterprise orgs that were previously omitted for some reason.

**Comment by cheba** [comment]
@dylang That's exactly what I'm talking about. Thank you for illustration.

**Comment by ptsochantaris** [comment]
@dylang @cheba I see what you mean there, I'll make a note to turn the count dark when highlighted in dark mode.

**Comment by mauricerkelly** [comment]
@ptsochantaris does the build need to be signed? Were the old builds ever signed?

**Comment by ptsochantaris** [comment]
No, none of them were signed, and it's getting annoying because you have to do the right-click to open them. Have to research OS X signing a bit... any pointers?

**Comment by mauricerkelly** [comment]
I haven’t done it in a few years, but it’s not much different from signing iOS applications - Xcode does a lot of the work. It does mean signing up for the Mac Developer program though, which is another 70 quid a year for something you’re not charging for, so I could understand if you didn’t think it was worth it.

**Comment by ptsochantaris** [comment]
Yeah, that's a little annoying considering I don't (currently) make any money from Trailer or other OS X apps. It's not a fortune, but leaves a bad taste in my mouth to have to pay so that people can simply open an app without right-clicking. OTOH it may mean putting Trailer on the App Store to make it easier to install and update (+ finally being able to use iCloud sync for settings). For this release though, and given Trailer is usually launched-on-login, I think I'll have to burden users with the right-click launch option :(

**Comment by mauricerkelly** [comment]
I have a Mac developer account - I’d be happy to sign the Mac app for you, but that would mean you having a third-party dependency (me) in your release process. Might also require me to register your app ID against my account, which is again something you might not want to do.

**Comment by Luzifer** [comment]
On the other hand: Maybe there are in fact people willing to pay you a small amount of money for your development which you could use for getting into the app store? If you would take this in mind count me in.

**Comment by mauricerkelly** [comment]
I would also be very happy to contribute. Donation button on the website?

**Comment by ptsochantaris** [comment]
@cheba @dylang I've replaced the 1.2 build with one that has improved dark-mode highlighting for counts, give it a try and let me know if it improved for you. The link is the same.

**Comment by ptsochantaris** [comment]
@mauricerkelly Really appreciate the offer for the signing, but like you said, I'd rather not tie up the release cycle (which is very part-time, adhoc and unorganised at the moment) with an external dependency that also needs to be taken into account.

@Luzifer @mauricerkelly I really appreciate that guys. I've thought about it before, but because this project was initially started at HouseTrip I don't want to start charging for it, and probably won't.

However, like you point out, a donation button on the site is a thought - not sure if it would pay for Mac membership long-term (I know that some people find Trailer extremely useful, and that's awesome, but I have no idea how many, and out of those how many would contribute), but perhaps it is an experiment to try out! Besides, the site needs a refresh sometime too, may as well add a donation button...

Ok, what the hell, I'll set up a Mac developer account so this release can be signed, and (eventually) get around to a donation button, worst case scenario I've spent 70 pounds for some extra Mac development experience. I've done worse things :)

**Comment by ptsochantaris** [comment]
Heh, Apple took two days to process my Mac Dev program membership order, and they came back to me with a second iOS dev membership (facepalm). I just sent them a support request, fingers crossed. As soon as I can sign it and bump the build number, I'll replace the binary, place an entry for it in the auto-update appcast.xml and close this issue.

**Comment by mauricerkelly** [comment]
@ptsochantaris y’know - I think Trailer is the first app I know of that’s been ported to Swift. Do you know of any others?

**Comment by ptsochantaris** [comment]
I don't know of any specifically being totally ported to 100% Swift (striiiiictly speaking, neither is Trailer since it uses Apple's Reachability class which is ObjC, and Sparkle for auto-updates on OS X, but yes, for most purposes I'd call it a Swift-only app)

I do know that a lot of dev houses are starting to use it for new components to apps and so forth. I just just reading this article earlier on: http://appleinsider.com/articles/15/02/07/apples-new-swift-programming-language-takes-flight-with-getty-images-american-airlines-linkedin-and-duolingo

Might be the first combined OS X & Universal iOS unified codebase to be 100% Swift though :)

**Comment by ptsochantaris** [comment]
Ok, the build at the same URL has been replaced with a signed one. Give it a try if you like to see if everything goes well and it opens on your system :)

**Comment by ptsochantaris** [comment]
Trailer 1.2 is now on the auto-update appcast feed, so I'm closing this, hoping there are not too many immediate problems with the update. If you spot anything, please do open an issue!

Thanks again to everyone for testing and helping improve Trailer, I hope it makes your life a little easier!

Now, let's have a look at all these feature requests that have been waiting patiently... :)
