### ISSUE TITLE
Support for Issues

### ISSUE THREAD

**Issue by ptsochantaris** [ptsochantaris/trailer#178]
Perhaps as a second, optional, menu item, with the issues icon?

- Same logic as PR listing: Mine, Participated (including assigned, etc), All
- Labels
- Comments counts and new badges
- List repo for each issue and able to group by repo
- Click to visit, copy, drag off etc.

On iOS, split into tabs, with badging

**Comment by appleprtest** [comment]
Test comment

**Comment by appleprtest** [comment]
Test comment

**Comment by appleprtest** [comment]
Test comment 2

**Comment by appleprtest** [comment]
Test comment 3

**Comment by appleprtest** [comment]
Test comment 4

**Comment by appleprtest** [comment]
Test comment 5

**Comment by appleprtest** [comment]
Test comment 6

**Comment by appleprtest** [comment]
Test comment 7

**Comment by appleprtest** [comment]
Test comment 8

**Comment by ptsochantaris** [comment]
Beta test builds with this feature can be found here: https://github.com/ptsochantaris/trailer/pull/185

**Comment by appleprtest** [comment]
Test comment

**Comment by appleprtest** [comment]
Another test

**Comment by appleprtest** [comment]
Test 3

**Comment by appleprtest** [comment]
Test 4

**Comment by appleprtest** [comment]
Test 6

**Comment by appleprtest** [comment]
Test 7

**Comment by ptsochantaris** [comment]
Version 1.3.0 is now live and includes this feature, so I will close this, but please feel free to re-open in case there are further problems problems, or feel free to open a new issue.

You can upgrade your version either from here: http://ptsochantaris.github.io/trailer/trailer130.zip or more easily from About -> Check for updates
