### ISSUE TITLE
1.2.0 - number of comments glitch

### ISSUE THREAD

**Issue by Karlotcha** [ptsochantaris/trailer#179]
I just upgraded to 1.2.0 and there are some weird glitches on the number of comments in the list of PRs.
Also the number of unread ones in red is sometimes behind the number in grey, making it unreadable. 

It looks a bit like that, but just on the label with the number of comments: https://github.com/ptsochantaris/trailer/issues/168

**Comment by ptsochantaris** [comment]
Hi @Karlotcha - thanks for letting me know. I assume the glitches you're referring to are graphical. Is it possible you can provide a screenshot of them?

**Comment by ptsochantaris** [comment]
Also, which version of OS X are you running?

**Comment by Karlotcha** [comment]
About the version: OS X 10.9.5 

There are graphical indeed. When I scroll, I get things like that: 
![screen shot 2015-02-17 at 10 21 20](https://cloud.githubusercontent.com/assets/1086288/6226656/4ad3b4ec-b68f-11e4-9d4f-ee99c07db419.png)

I don't have any unread comment right now, but sometimes the red label is behind the grey one. Scrolling can fix / break it again.

**Comment by ptsochantaris** [comment]
Great, thanks for the update @Karlotcha  The deletion of the text makes it a bit hard to understand what is going on - could you just blur/scramble/pixelate it instead?

**Comment by ptsochantaris** [comment]
Try this build and let me know if it helps - it should fix the red badge issue, but I'm not sure about the positioning problem, may need a few more builds, but we'll sort it out :+1: 

https://www.dropbox.com/s/jw26uhyeducx25w/Trailer-displayfix1.zip?dl=0

**Comment by Karlotcha** [comment]
@ptsochantaris the last version has a slightly different issue, here's a screenshot:

![screen shot 2015-02-18 at 09 22 01](https://cloud.githubusercontent.com/assets/1086288/6244865/78568bb2-b750-11e4-945a-deecbbe47934.png)

So when I am scrolling, it looks like the column with the numbers of comments is different than the right part, and they are scrolling at different speed :/

**Comment by Karlotcha** [comment]
Before it was like that:

![screen shot 2015-02-18 at 09 32 33](https://cloud.githubusercontent.com/assets/1086288/6244935/4e1d8516-b751-11e4-88e3-d19520bb5923.png)

**Comment by ptsochantaris** [comment]
To be totally honest I have no idea what's breaking, so I'm trying different approaches to see which one will work :) Here is another one, have a go and let me know how it goes!

https://www.dropbox.com/s/2i18zhowprwfn4x/Trailer-displayfix2.zip?dl=0

**Comment by Karlotcha** [comment]
It came back to the first glitch (like my last comment). 

On a side note also, when I try a different version of trailer, it deletes my github token when I come back to the version I am using now (1.1.5)

**Comment by ptsochantaris** [comment]
Ok, how about this one: https://www.dropbox.com/s/j3xrk5ays3fp1i9/Trailer-displayfix3.zip?dl=0

**Comment by ptsochantaris** [comment]
Also, about losing your token - yes, unfortunately Trailer isn't forwards-compatible, so do make sure you copy/paste your token when downgrading to an older version, because it will reset your DB.

**Comment by Karlotcha** [comment]
Yay! \o/ 

It's all good now, thanks :))

![image](http://media.tumblr.com/100d25a87016b90363f5f639f82fc795/tumblr_nb3kkaV5Me1sq9yswo1_500.gif)

**Comment by ptsochantaris** [comment]
Awesome! Also: Best bug-fix response ever - Made my day :)

Great, that wraps it up for 1.2.1 then, will release in the evening!

**Comment by ptsochantaris** [comment]
Hi, version 1.2.1 is up, which includes this feature. Will close this issue for now, but please feel free to re-open if you encounter any issues with it.
