### ISSUE TITLE
99% CPU usage after about a day's usage

### ISSUE THREAD

**Issue by baz8080** [ptsochantaris/trailer#182]
Hi,

Myself and a few people in our office use and love Trailer but we have this issue. Sometimes the cpu usage for trailer spikes up to 99% and won't come back down. If I click on the Trailer icon during this time I get a beachball of death.  The only way to fix it is to kill the process and start it again.  What information can I give you to help diagnose the issue?

Thanks,
Barry.

**Comment by ptsochantaris** [comment]
Hi @baz8080 and thanks for calling this in!

Great to hear Trailer is useful for you - let's see if we can also get it to work without dying on you like that :) This is going to be a bit tricky to debug, so what I'd like to do first is to try the "easy" path and see if we can get some more useful info from it:

If you can, enable console logging from Preferences -> Log activity to the console.

This will make Trailer dump a lot of info about what it's doing to the system console (accessible via Console.app) and MAY perhaps provide us with some info around the time it goes into the "beachball" mode you describe. Even if it doesn't output anything WHILE it's there, the recent output from it just before it gets there may prove to be very useful.

If we don't get any useful info like that, I'll prepare a build with a lot of (very noisy) tracing info in the various functions which ought to prove a lot more useful when tracing what happens in the run-up to this "meltdown" state.

But in the meantime, keep me up to date with how the console logging goes. If you notice Trailer goes into "meltdown", visit the console app, and see if you can dump a file with the log contents containing Trailer output from the recent past, and paste it in here or if you are worried about privacy feel free to email it to me at <my github username>@me.com

Hang in there and we'll sort this out!

**Comment by baz8080** [comment]
Thanks @ptsochantaris !

I have enabled logging now but I'm glad to report that there have been no issues today. I'm working from home today so my environment is not the same (no dual monitors etc). Thanks for your help!

**Comment by ptsochantaris** [comment]
No problem - this has been reported by a colleague as well this morning, so it's definitely an issue. It may be a bit tricky to catch but we'll get to the bottom of it :+1:

**Comment by baz8080** [comment]
@ptsochantaris This hasn't happened since. I'm on 1.2.2 and I think this bug may have been on the previous version.  I think we can close this issue :)

**Comment by ptsochantaris** [comment]
Hi - yes, it's weird that it wasn't reported since, but the damnedest thing is that it was reported within 12 hours by you and another person. I can only assume this was some GitHub API burp that the sync didn't cater for, and will be hard to trace in retrospect...

In any case, I'm glad it wasn't some sort of widespread issue.

Thanks again for calling it in, and please feel free to re-open this or file a new issue if this happens again!
