### ISSUE TITLE
iOS Extensions: Today Widget, Watch Glance & Watch App

### ISSUE THREAD

**Issue by ptsochantaris** [ptsochantaris/trailer#184]

**Comment by ptsochantaris** [comment]
Screenshots and code on this can be followed here: https://github.com/ptsochantaris/trailer/pull/185

**Comment by appleprtest** [comment]
Test comment 1

**Comment by appleprtest** [comment]
Test comment 2

**Comment by ptsochantaris** [comment]
These are mostly ready, at least in their basic form, and will be submitted for review very shortly. Because of the extra watch component, there may be rejections related to that, but hopefully we'll see these live sooner rather than later.

**Comment by ptsochantaris** [comment]
The iOS app is now in the App Store and contains these features. I will be iterating more on them as they become more testable (especially the Watch Glance and App which I expect will have performance and layout issues)
