### ISSUE TITLE
Vibrancy Graphical Glitches

### ISSUE THREAD

**Issue by gdehmlow** [ptsochantaris/trailer#186]
I love trailer! 

Just a thing I noticed after enabling vibrancy mode: there will be pretty frequent graphical glitches where clicking the icon and opening the main display area flickers the entire background black, or when I open the settings menu and mouse up to show all of the options, black boxes appear in the background. Getting a screenshot of the exact problem hasn't been very successful, but it looks mostly like this:

![screen shot 2015-03-31 at 10 56 51 am](https://cloud.githubusercontent.com/assets/850025/6925717/2b0f3852-d796-11e4-952d-eec55e683c9f.png)

I'm running Yosemite 10.10.2.

**Comment by ptsochantaris** [comment]
Hi @gdehmlow - really glad you're liking Trailer!

Yes, I've been really *really* trying to get to the bottom of this issue, as I'm affected by it too. I have no idea why it's happening, to be honest. I've put in a lot of time trying to change the way the widow gets drawn/rendered, etc, but to no avail. The rather sparse documentation on the effect views on the APIs doesn't help much either, and I'm starting to wonder if this isn't some OS graphical bug TBH...

All I can say for the moment is thanks for opening the issue, it's good to have it on the list so it can remind me to keep looking into it, and I'll keep you up to date with any progress I make.

PS If you don't mind me asking, what is the Mac model (or graphics chipset) you are using?

**Comment by bkuhlmann** [comment]
I've been experiencing this too (although I can't always consistently recreate). In case it helps, here are the details:

- Only happens when using a laptop with a retina display (i.e. the `Use vibrancy` display setting is enabled).
- MacBook Pro i7
- Intel Iris Pro graphics chipset.

**Comment by pedrocunha** [comment]
I'm not sure how it helps, but I get this behaviour consistent whenever I open the trailer PR window and some OSX notification pops out.

**Comment by ptsochantaris** [comment]
Thanks for chiming in guys, yes, same here, notifications will cause it.

This is a wild guess on my part, but I'm thinking this is occurring when the backing layers in the Trailer window are being rasterised...

Also you can get this to occur whenever you try to screenshot the window or drag items off the list as well, if you are still moving the item over the list after a second or so. I'm also using a retina system as well.

This isn't unheard of in other programs as well: http://prod.lists.apple.com/archives/cocoa-dev/2014/Sep/msg00196.html

And for some reason, while indirect, I have a feeling this is related: http://stackoverflow.com/questions/28383563/cocoa-backgrounds-of-components-on-nsvisualeffectview-rendering-incorrectly-whe

When I have some time I'm going to play with setting various backgrounds to transparent, perhaps at some point the optimisation/raster operation that causes the blackening picks up a background colour setting from somewhere. Will keep investigating!

PS If anyone without a Retina display is getting this, please let me know - it seems to be Retina-specific.

**Comment by ptsochantaris** [comment]
Just to keep you updated on this - there is something very deep and weird going on in the API syncing.

If you run Trailer on a very slow connection and try to cause this glitch BEFORE the first sync starts (or rather, after the first stage of the sync), you can't, the glitch isn't there - it seems that something is happening in the syncing that's causing weirdness in the UI layer. No idea what it is, but it seems to be related to crashes that occur when 1.3 is run with optimisations on, so it may be related. Something to do with blocks and memory management perhaps.

And so the mystery deepens :) but I wanted to keep you up to date and let you know I am looking into it.

**Comment by ptsochantaris** [comment]
Hi, I think I may have *finally* fixed this issue - if you're feeling a little adventurous, have a go with 1.3 RC5 here and let me know if it corrects things for you:

https://www.dropbox.com/s/4xve96i7r132afq/Trailer-13-RC5.zip?dl=0

**Comment by bkuhlmann** [comment]
Been using it all day and am not noticing any black background flicker. So far, so good. Nice work.

**Comment by ptsochantaris** [comment]
Excellent news, and thanks for testing!

The issue, for the record, was that I set the whole window to use a backing layer, which for some reason broke the vibrancy view (or the compositing of it). Disabling layer backing fixed the issue, but made the window redraw and scrolling very slow. The compromise was to set the content view of the table/scrollview to use layer backing, but not the window. Redraw and scrolling is pretty smooth, and the effect layer is unaffected.

**Comment by ptsochantaris** [comment]
Version 1.3.0 is now live and includes this fix, so I will close this, but please feel free to re-open in case there are further problems problems, or feel free to open a new issue.

You can upgrade your version either from here: http://ptsochantaris.github.io/trailer/trailer130.zip or more easily from About -> Check for updates
