### ISSUE TITLE
When exporting settings to new location, LAST_EXPORT_URL is not updated with new path.

### ISSUE THREAD

**Issue by bkuhlmann** [ptsochantaris/trailer#188]
Previously, when exporting my settings via Trailer 1.3.0, I accidentally exported to the following path:

`file:///Users/bkuhlmann/Dropbox/Cache/Snippets/Trailer/vilya.trailerSettings`

What I really wanted was: `file:///Users/bkuhlmann/Dropbox/Cache/Trailer/vilya.trailerSettings`. (i.e. the `Snippets` folder wasn't suppose to be used in the original export).

Upon re-exporting my settings to the correct location, I would have  expected the `LAST_EXPORT_URL` value to be updated with the new path but it ended up using the original, incorrect path.

**Workaround:** Exporting settings to a new path and immediately importing the settings from that path will update the `LAST_EXPORT_URL` key appropriately.

**Related:** Alternatively, editing the `LAST_EXPORT_URL` value within the `*.trailerSettings` file will cause Trailer to use the correct path but default back to `Trailer Settings.trailerSettings` as the file name when you might have called it `example.trailerSettings` instead (expectation: use the latter).

**Comment by ptsochantaris** [comment]
Ah, thanks for reporting these! Will check them out ASAP.

**Comment by ptsochantaris** [comment]
Yes, got it - the auto-exporing time was badly implemented, it captured the URL of the export location once and would always auto-export to it no matter what the value of the LAST_EXPORT_URL was. It should work fine on tonight's build now :+1: Well spotted!

**Comment by bkuhlmann** [comment]
Awesome, thanks! :smile:

**Comment by ptsochantaris** [comment]
Hi, I'm going to close this for now, but please feel free to re-open in case you'd like to add to this for any reason. Thanks again for testing this, and let me know in the main issue's thread of your thoughts and suggestions!
