### ISSUE TITLE
Make menubar icon contrast on if the menubar is set to black

### ISSUE THREAD

**Issue by mgingras** [ptsochantaris/trailer#195]
Can't see icon on black menubar.

![screenshot 2015-04-28 13 24 34](https://cloud.githubusercontent.com/assets/1209506/7375925/f193a8e0-eda9-11e4-9f8c-4d24b3403496.png)

**Comment by ptsochantaris** [comment]
Hi!

I assume this is a UI-theming-related black, not "dark mode".

Does the number part (when it's not red) show up properly on the menubar?

**Comment by mgingras** [comment]
@ptsochantaris Hey!

When not red the number is white, which I believe is correct. But yes it appears not to recognize that I am using the dark menubar/dock.

![screenshot 2015-04-28 18 14 49](https://cloud.githubusercontent.com/assets/1209506/7381553/7e47418e-edd2-11e4-8166-535a01e537d4.png)

**Comment by ptsochantaris** [comment]
Ok, good - that means that the colour being reported by the UI for the text is correct, and we can rely on that to generate the image :+1: Can you try this debug build and see if it helps?

https://www.dropbox.com/s/l3fnppg2zn10fqd/Trailer-statusitem.zip?dl=0

**Comment by mgingras** [comment]
:+1: Works thanks for the quick fix!
![screenshot 2015-04-28 19 29 07](https://cloud.githubusercontent.com/assets/1209506/7382442/e2644acc-eddc-11e4-8166-692da8083c38.png)

**Comment by mgingras** [comment]
Aside, is the dropdown menu themed to be dark if the theme is dark? For some reason I don't remember it being light before.

**Comment by ptsochantaris** [comment]
Great to know that part is sorted out! It's actually cleaner to do it like this because it's now possible to colour in the various images used and maintain fewer image assets :+1: 

The menu should also be dark themed. The fact that you're seeing a light menu seems to indicate that Trailer hasn't "read" the proper status for your screen mode, the same root cause of the dark icon as well. Can you try disabling and re-enabling dark mode on your system to see if Trailer picks it up?

If that works, but you then restart Trailer, does it again start in "white" mode?

**Comment by mgingras** [comment]
Perfect!

Switching between light and dark updated the menu.

Restarting trailer and the menu is still dark.

Seems fine.

Thank you,

Martin

**Comment by ptsochantaris** [comment]
Ah, great!  I've seen this happen before, and have ZERO idea why it only happens the first time and doing the on/off with dark mode fixes it, Trailer doesn't store anything related to the display mode, except the requested setting, which never changes... oh well, at least it's all good now :+1: 

Feel free to use the debug build if you prefer, although the actual released version should now also work fine as well. Their main difference is mostly that the debug build just logs stuff, which can't be turned off, so it will run a tiny bit slower, but other than that it should be fine to use.

If you can find any way to "lock" Trailer into that weird "white-only" mode please DO let me know! :)

**Comment by mgingras** [comment]
Awesome, downloaded released version and it's working fine. Thanks for getting on this so quick and the great support. Props on the awesome app. Keep up the great work!

**Comment by ptsochantaris** [comment]
No problem, and thanks!

**Comment by mgingras** [comment]
@ptsochantaris One last thing, completely unrelated. There's no link to the iPhone app on the main website. I didn't know there was one until reading the the readme. Would be cool if that was on the main website.

**Comment by ptsochantaris** [comment]
You're absolutely right - I tend to think of the Github page as the "main" page but I forget that's not it :)

I'm going to be cleaning that page up soon, and I'll definitely add a link to the App Store as well, thanks for the reminder!
