### ISSUE TITLE
Seeing all merges even when set to "Keep My Own"

### ISSUE THREAD

**Issue by bsiegel** [ptsochantaris/trailer#197]
With "When something is merged" => "Keep My Own", I am still seeing PRs appear in the "Merged" section that I was not involved in. I'm using Trailer 1.3.1.

**Comment by ptsochantaris** [comment]
Hi and thanks for reporting this!

I'll look into it ASAP, but first, are you sure that any of the other conditions that may make the PR your own aren't in play? Like it being assigned, you being mentioned in a comment and so forth? Basically, the idea is that if the PR is in the "Mine" section and it gets merged, that setting will keep it.

There was some refactoring the in sync code recently, and I wouldn't be surprised if this was a regression, but I thought I'd double-check - I'll still be looking into this in any case.

**Comment by bsiegel** [comment]
I'm fairly certain that I wasn't included in any of the PRs' metadata nor was I mentioned. But I will watch for the next one to occur and verify.

**Comment by bsiegel** [comment]
Just verified. Got notified about a newly merged PR, and it shows up in my Recently Merged section. I'm definitely not assigned, nor included in the conversation. I am in the Owners group for the repo if that makes any difference.

**Comment by ptsochantaris** [comment]
It shouldn't -- ok, so this is most likely a regression in the sync code then, I'll be definitely looking into it ASAP.

**Comment by ptsochantaris** [comment]
Hi, I'm having some trouble finding an obvious bug related to this, and my test merges seemed to be reported correctly - which just means I need to dig more :)

So for a start I've cleaned up the code around that logic and made some tweaks for clarity, including most importantly logging. Could you try this debug build for a bit and see if it improves the situation? I'm also going to subscribe to some repos with very heavy traffic to see if merging is reported for unrelated PRs.

https://www.dropbox.com/s/8n5n84xbgsgu1p9/Trailer-avatars-and-merge-1.zip?dl=0

If you still get the problem, can you check into the output in Console.app (just filter for "Trailer") and see the messages reported around the time a PR is detected as merged? The messages you are looking for will start with "Detected merged PR:" which includes important state info, and will also be followed by more messages with the "decision" the logic makes. It may help clear up what's going on.

If you get a chance, give it a go, we'll get to the bottom of this yet :+1:

**Comment by bsiegel** [comment]
Thanks so much, I'm giving it a try now. I'll let you know how things go!

**Comment by ptsochantaris** [comment]
Ah, from an unrelated issue we found a problem in the logging code that could lead to a crash on that build, here is an updated build which should hopefully correct this:

https://www.dropbox.com/s/qs2m9sy4ky0lzz5/Trailer-avatars-and-merge-2.zip?dl=0

**Comment by bsiegel** [comment]
With this build, things appear to be working as expected. When "Keep My Own" is set, I see PRs that I am involved in are moved to the "Merged" section once merged, but other PRs are simply disappearing when merged.

I've flipped the setting to "Keep All" now to verify that there was no regression, and I'll let you know if that seems to still be working as well once I have some results. Thanks!

**Comment by bsiegel** [comment]
Yep, seems to be working as expected when "Keep All" is selected too! I'll keep my eye out the next couple of days but it looks like you've solved the issue!

**Comment by ptsochantaris** [comment]
Fantastic news! Thanks for testing this - what worries me TBH is that I'm not sure HOW I fixed it, I just cleaned up some rather sloppy code I had created for this a while ago, and somehow by doing that the problem got fixed. Still, I'm really glad that fixed it, and hopefully the cleaner code and logic will mean less regressions in the future.

Thanks again for reporting and helping with the testing for this!  I'll wrap up a couple of other things and push an incremental update out this week containing this fix :+1:

In the meantime, if you encounter this again or something related, please do give me a shout. I'll keep this issue open until the update is up.

**Comment by ptsochantaris** [comment]
Version 1.3.2 is up now and should include this fix. I will close this for now, but please feel free to re-open this in case there are further issues or problems with it.
