### ISSUE TITLE
Request: Include 'checks' info?

### ISSUE THREAD

**Issue by jphastings** [ptsochantaris/trailer#201]
It'd be awesome to have a (✔) or (✘) next to listed PRs that are 'mine' to show whether all the checks (eg. Travis-CI or coveralls) for that PR have passed or not.

**Comment by ptsochantaris** [comment]
Hi!  There may be a feature that covers that need already: Have you tried the "show PR CI / statuses" option in the "Labels & Statuses" section?

It will list statuses added by services such as CI, and will use a green/red/yellow colour code to quickly let you know is it has a "passed"/"ongoing"/"failed" state for each one.  Additionally, you can Cmd-Click on a status to take you to the URL pointed to by the respective service that posted that status (if the service has provided one).  You can also control notifications based on these statuses when they change from the checkbox options in that section as well.

Listing statuses and labels is a little more "expensive" on API calls, so if you have a lot of repos or items in your lists you may want to keep a relatively high re-scan value to that, so that it doesn't eat up your quota, but in general I find that the default works decently.

I hope I have understood your question, please do let me know if I've missed your actual point :)

**Comment by jphastings** [comment]
That's the functionality I was looking for - I had missed it :)

However I was hoping for something a little more obvious (I can see a red cross on the right, say, much faster than scanning for red text beneath all the PRs), and the ability to limit those notifications to only my PRs (I've tried using the "only sow status items that include…" and entered my username, but that doesn't seem to work)

Thanks :)

**Comment by ptsochantaris** [comment]
Trust me, it's not you, those preference panes have gotten cluttered over time, and features are not very discoverable. I keep tidying them but I'm becoming more and more wary of feature creep :(

I definitely get the convenience of having an easily readable icon next to the PR name, however the trouble with a "one status to rule them all" icon is that the status messages that it would base it's logic on are essentially generic, and there may be multiple statuses relating to the latest commit (from various services), or they may simply be totally unrelated. It's impossible to chose, given the abstract nature of the status mechanism of GitHub, which status should "govern" the overall "go/no go" master icon.

Do give this a try for a bit though, it works better than you may expect :) Also, notifications on status items for me prove to be quite helpful, especially for CI.

All that said, your thoughts on how to perhaps implement a "master" red/green icon or improve the existing status reporting would certainly be more than welcome!

(Brainstorming: Perhaps only show an icon if all status items are the same "red/green/yellow" state?)

**Comment by jphastings** [comment]
Github provides an 'overall' icon (shown at the top below) which is the 'worst' of all of the statuses which might work well, I have no idea if that's exposed via the API though. I plan on working with the status text for the next couple of days and see how it pans out! Thanks :)

![screen shot 2015-05-12 at 17 54 40](https://cloud.githubusercontent.com/assets/42999/7593213/5814aeb2-f8d0-11e4-94b4-8e5a196d01a5.png)

**Comment by ptsochantaris** [comment]
I don't think it is exported by the API (although I'll have a look) but it would be trivial to base it on some logic like that (i.e. picking the "worst" status)

My thinking is this could work if we include an additional switch for statuses that goes something like:
- Show overall status (worst case)
- Show overall status (best case)

This would change the background of the comment count box (the overall "grey" one, not the unread count badge) depending on status, or it could show a vertical band" of colour at the left edge of the item.

Have a go for a bit with the existing feature-set to get a better feel for it, and we can put more thought into this :+1:

**Comment by jphastings** [comment]
Sounds good to me - thanks!

**Comment by ptsochantaris** [comment]
Hi @jphastings! Was wondering if you've had more thoughts on the stuff we talked about above. Do you still feel we need a more prominent display of statuses? Would something like I proposed above improve your workflow at all, or have you had other insights perhaps? No worries if you haven't thought about it, I thought I'd just pass by and say hello in any case :)

**Comment by jphastings** [comment]
The green status text is a little close to grey for my eyes - it's difficult to see if the tests haven't run of if they aren't green. It's not really been something I rely on to be honest, as the emails that come through from Travis have been enough for me for the moment - I'll pay closer attention :)

**Comment by ptsochantaris** [comment]
Hm, perhaps small icons next to statuses could help?

**Comment by ptsochantaris** [comment]
The more I think about this, the more I think it makes sense to add little tick/cross icons (or just Unicode TBH) at the start of status items. Besides, a large number of people are red/green colourblind, so this would probably make it useful for them as well.

**Comment by jphastings** [comment]
:) Thanks Paul!

**Comment by ptsochantaris** [comment]
Closing this for now, always happy to get more feature requests / bug reports!
