### ISSUE TITLE
Repos just not showing up

### ISSUE THREAD

**Issue by mckern** [ptsochantaris/trailer#203]
I've got Owner permission over a number of private repos under the "Puppet Labs" organization and Trailer doesn't list them as options for hiding or showing at all. I have little-to-no data to provide beyond "there's repos that it doesn't let me see."

**Comment by ptsochantaris** [comment]
Hi! Let's see if we can trace what's happening. First off, all are these repos in your GitHub Watchlist? https://github.com/watching

Assuming they are, and these are private repos, Trailer will try to see if there is any push/pull/admin permission on them - if none of those are there it will exclude them from the repo list (although it doesn't check the owner, which may be something it might need to do perhaps...)

Is it possible to check the contents of your watchlist with the following command and see what permissions are listed for the specific repos (if they show up?)

curl -H "Authorization: token (paste your auth token from preferences here, without the brackets)" https://api.github.com/user/subscriptions

You will get a (possibly long) JSON response of a list of items. Each item will contain a "permissions" sub-tree. If all three permissions are "false" in a repo, it will not show up. See what the permissions are like on the repos that are not showing up (look for "name" or "full_name" in each item to identify which repo it's referring to)

Try this when you have some time and let me know how it goes, we'll pick it up from there!

**Comment by mckern** [comment]
Totally wasn't subscribed. What happened is at some point I disabled "automatic subscription" so about a  bunch of repos created since I (probably) toggled that GitHub preference weren't actually subscribed to. Thank you so much for helping me track down the root cause!

**Comment by ptsochantaris** [comment]
Aha! Excellent, all is well that ends well then!

Let me know if you encounter any other weirdness, happy to help (it's also useful to have feedback like this, most user "errors" are misunderstandings due to bad design)
