### ISSUE TITLE
Labels aren't shown when the title wraps to two lines

### ISSUE THREAD

**Issue by bsiegel** [ptsochantaris/trailer#205]
When the title of a PR is long enough to wrap to the second line, the second line of text replaces the label. In the image below, both PRs have a label assigned but it's only shown below the second one.

![screen shot 2015-05-26 at 2 25 33 pm](https://cloud.githubusercontent.com/assets/96068/7843732/86660dec-0479-11e5-9fe0-653ba47220ea.png)

**Comment by ptsochantaris** [comment]
Interesting! Normally the labels are part of the title string, so it *ought* to wrap naturally, but it seems something is going on with the title height calculation here perhaps. Now that I know this is happening I can try to incrementally increase a test string size to see where it happens and why.

Thanks for pointing it out :+1: will get back to you about it soon.

**Comment by ptsochantaris** [comment]
I think I may have tracked this down, in a way. Seems that font bounding box calculations were slightly off (or, not accounting for a slight border) and compensating for them fixes this. Your item's title was just on the borderline where that small difference made the difference, and caused a miscalculation on the number of lines the title would take! This *should* no longer happen, but I'll be definitely keeping an eye out. Until the next version shows up, here's an updated build with the fix:

https://www.dropbox.com/s/2edxhkfnzutofgz/Trailer-detailed-repo-settings-3.zip?dl=0

**Comment by ptsochantaris** [comment]
Hi, just wanted to let you know that the latest update (1.3.4) is now live, and includes the fix for this issue. Will close this for now but please feel free to reopen or post a new issue in case you encounter any other problem!
