### ISSUE TITLE
Add ability to multi-select projects when changing PR and/or issue preferences

### ISSUE THREAD

**Issue by bkuhlmann** [ptsochantaris/trailer#217]
![repos](https://cloud.githubusercontent.com/assets/50245/8892090/a19497c6-3301-11e5-8dbe-35918bdebc11.png)

When dealing with multiple projects, it would be nice to be able select multiple projects at once and then apply the same PR and/or issue settings. For example, five out of the ten projects I'm associated with might only need "Participated" capability while projects A, C, and G need issues hidden only.

The "Set all PRs..." and "Set all issues..." buttons are handy, and nice to have, but only in situations where all projects benefit from the same settings (which isn't always the case).

With multi-select enabled, the "Set all PRs..." and "Set all issues..." buttons could be used to apply specific settings to only the selected projects.

**Comment by ptsochantaris** [comment]
That certainly makes a lot of sense.

The only trick there is that the "set all" buttons will need to change to display "set selected..." text when a multiple-selection is active, which means they need to be a bit wider (and consequently making the visibility settings columns above them wider) but the layout there affords us the luxury of expanding those two a bit anyway.

Added to the TODO list :+1:

**Comment by ptsochantaris** [comment]
By the way, as mentioned in #215 , do bear in mind you can use the filter and the "set all..." buttons in conjunction, i.e. they will only apply the visibility change to the filtered repos, not all repos. I hope this helps in case you need to change the visibility of many similar repos or orgs simultaneously (of course a multi-select approach like you suggest is the most natural approach, but I'm mentioning this in case it helps in the meantime)

**Comment by michaelwills** [comment]
This would be a nice feature. :)

**Comment by ptsochantaris** [comment]
Hi guys,

Just thought I'd mention there is a new beta-test issue up at https://github.com/ptsochantaris/trailer/issues/219, and it contains this feature. It may have issues of course, but in case you're feeling adventurous (or really need this feature :)) please feel free to give it a go!

**Comment by bkuhlmann** [comment]
Thanks! I read the release notes. I might hold off on this for a bit until things stabilize a bit more. Looking forward to the new features, though. :)

**Comment by ptsochantaris** [comment]
Version 1.3.7 for OSX is now up which includes this feature, you can auto-update from any beta or previous version from the About window.

**Comment by bkuhlmann** [comment]
Ahh, this is so nice. Thanks!
