### ISSUE TITLE
Own PR's not longer shown in "My Pull Requests"

### ISSUE THREAD

**Issue by newdark** [ptsochantaris/trailer#220]
[Reference](https://github.com/ptsochantaris/trailer/issues/141)

As of Version 1.3.6(1227) the PR's that are assigned to me for some reason don't show up in My Pull Requests list. They just stay in the "All Pull Requests".

**Comment by newdark** [comment]
This might be a integration problem with the Enterprise version of the API. Seeing how it seams to work when talking to the github.com site.

**Comment by ptsochantaris** [comment]
Hi @newdark 

Trailer will detect if an issue (or the related issue record of a PR) is assigned to you by checking its "assignee" field, and specifically the "login" field of that structure. If the login on your API server and that match, it assumes the PR/Issue is assigned to you. Is this different in GitHub Enterprise?

Assignment detection seems to be working fine for me (I'm using the latest beta, although nothing significant has changed in assignment detection there) so I think it's either that something is mis-configured on your end or, more probably, your server is providing slightly different info than the one GitHub provides for PR assignment.

If you have any idea on what may be different let me know, or I can produce a test build which will dump the API responses for you, so we can have a look if the "assignee" field contains the data Trailer is looking for.

**Comment by newdark** [comment]
@ptsochantaris Let me see if I can't get the API payload that is coming back from the enterprise version of github. Maybe that will shed some light on what is going on.

**Comment by ptsochantaris** [comment]
TBH that actually sounds like a good support feature anyway, I've added it onto the test build for the next release. If you get a chance, try it out - turn on "Dump API responses to the console for troubleshooting" from the "Misc" panel in preferences and see what you get back from the API.

https://www.dropbox.com/s/6yk6vyb417co98d/Trailer-1.3.7-1229-test-api-dump.zip?dl=0

**Comment by newdark** [comment]
Sweet that is exactly what I was looking for thanks

**Comment by newdark** [comment]
I am having problems recreating this again. I think the enterprise guys broke something and they are not admitting to it. Thanks for the help but I am going to close this.

**Comment by ptsochantaris** [comment]
No worries, at least we now have an easy way to check the API data in case it happens again :+1:
