### ISSUE TITLE
Trailer.app 1.3.7 does not work on OSX 10.9

### ISSUE THREAD

**Issue by iserko** [ptsochantaris/trailer#223]
Ever since version 1.3.7 was released, the app no longer works on OS X 10.9 Mavericks.

`system.log` shows the following:
```
Sep 30 10:05:44 titan.local Trailer[3513]: CoreData: error: (264) attempt to write a readonly database
Sep 30 10:05:44 titan.local Trailer[3513]: fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=256 "The file couldn’t be opened." UserInfo=0x600000074f00 {NSSQLiteErrorDomain=264, NSUnderlyingException=error during prepareSQL for SQL string 'SELECT Z_VERSION, Z_UUID, Z_PLIST FROM Z_METADATA' : attempt to write a readonly database}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-700.0.59/src/swift/stdlib/public/core/ErrorType.swift, line 50
Sep 30 10:05:44 titan com.apple.launchd.peruser.501[235] (com.housetrip.Trailer.92608[3513]): Job appears to have crashed: Illegal instruction: 4
Sep 30 10:05:45 titan.local ReportCrash[3514]: Saved crash report for Trailer[3513] version 1.3.7 (1236) to /Users/igor/Library/Logs/DiagnosticReports/Trailer_2015-09-30-100545_titan.crash
```

Crash report viewable: https://gist.github.com/iserko/5c12eae6497e1cb24e0e

**Comment by ptsochantaris** [comment]
Hi @iserko 

Thanks for reporting this. I have checked the app under my 10.9 VM in case there was some regression but it seems to launch and run fine.

I have looked at your crash report, and it looks like the DB directory that Trailer stores its files under seems to be read-only for some reason on your system. Specifically, it's crashing when trying to determine if the store needs migrating or not.

There may be some permission or disk issue at play here. The easiest way to get around this is to nuke, rename, or check the permissions of the directory at ~/Library/Application Support/com.housetrip.Trailer or rename it, and try launching Trailer again.

Also, just in case, check your activity monitor in case some instance of Trailer is hung in the background and is keeping the data store open for some reason (although I don't think this would cause the error you are experiencing)

Let me know if this helps at all!

**Comment by iserko** [comment]
@ptsochantaris moving the directory away and having Trailer.app recreate it did the trick.
Don't really understand why it would complain. I tried opening the sqlite db using the command line tool and it worked fine. Permissions on the file were fine as well.

**Comment by ptsochantaris** [comment]
Weird, but glad this fixed it! Whatever it was, it was related to not being able to write to the file - just in case, I would still recommend a filesystem check.
