### ISSUE TITLE
Add show option "Others"

### ISSUE THREAD

**Issue by irnnr** [ptsochantaris/trailer#229]
For some repositories I'd like to only show issues (and maybe PRs) that are not mine - from others.
Often times I just file an issue as a task/reminder for myself. Those I don't need to see in the menus.

Great job otherwise!

**Comment by ptsochantaris** [comment]
Hi @irnnr and thanks!

I get where you're coming from and it makes sense, but I'd like to better understand what you mean by "only show items that are not mine".

If you mean an option like "Hide items authored by me" that's quite easy to do, or were you thinking of options to hide the "mine" / "participated" sections instead (with all the accompanying logic that would divert or place items in those sections, for instance?)

The first one is quite straightforward, it can be a checkbox in the repository rows  like "include items I created" or something similar, default checked, which can be un-checked for certain repos.

The second case could get messy, as it would mean making per-repo settings quite granular in the preferences view, breaking them "out" of just being simple drop-downs with defaults in the watchlist/repo tab, which I'd be wary about at this time :)

How would you imagine this kind of setting? Would a checkbox in the repo row as described above cover it? Your suggestions are definitely very welcome.

**Comment by irnnr** [comment]
Yes, basically hide things that I authored myself, that would help a lot already!

It could either be a checkbox or another entry in the select list of mine/participated/hide/all

**Comment by ptsochantaris** [comment]
Yeah, I wonder if a "toggle-able" entry at the bottom of the visibility popup menu in the watchlist would make sense, so as to also make it possible to only hide authored PRs but not issues, in a certain repo for instance. Cool, stay tuned :)

**Comment by ptsochantaris** [comment]
Hi @irnnr 

I have a debug build with an initial implementation of this option. It made more sense to add this as an extra column, and to make it more generic, in addition to hiding the user's PR/Issues/Both, I have added the ability to do the same to others' items as well, so you could for instance hide everybody else's PRs or Issues in a specific repository if you wanted to (Note that this differs from the section controls, as it is a check based solely on the author, not the section into which the item would end up)

Have a go and let me know if it seems stable with your data, and also if it is covering your requirement :)

https://www.dropbox.com/s/p4rkt7tqs1okqp4/Trailer-debug-1257.zip?dl=0

Thoughts and suggestions continue to be very welcome!

**Comment by irnnr** [comment]
Works as intended, perfect!

**Comment by ptsochantaris** [comment]
Excellent, that's great to know! Hope it makes your life easier.

I'm currently wrapping up 1.3.11 and will let you know when it's up so you can upgrade to the actual release binary, as this one is a bit "fat" in terms of CPU, logs, and memory.

**Comment by ptsochantaris** [comment]
Hi, just wanted to let you know that the release build of 1.3.11 is up, you can update to it from "About Trailer" -> "Check For Updates"

**Comment by irnnr** [comment]
:+1:

**Comment by ptsochantaris** [comment]
Hi, I'm going to close this for now, please feel free to reopen or post further issues with suggestions!
