### ISSUE TITLE
Watchlist is not maintaining preferences

### ISSUE THREAD

**Issue by bkuhlmann** [ptsochantaris/trailer#234]
When setting "Set all PRs..." and "Set all issues..." to "Hide" for select repositories within the Watchlist, I'm seeing two things happen:
1. Multi-selecting certain repositories and changing their visibility for pull requests and issues will cause all repositories to inherit the new visibility even though they weren't selected.
2. Applying the desired visibility will temporarily be applied and then be randomly forgotten upon waking of the system or relaunching of Trailer.

Here are my system details:
- OS X (10.11.2) El Capitan.
- Trailer 1.3.11.

**Comment by ptsochantaris** [comment]
Ouch, sounds like an ugly regression there - I'll look into it ASAP, thanks for calling it in. Not sure what may be going on with the preferences being forgotten though, that's very weird indeed. Can you make sure you're not running two instances of Trailer somehow, perhaps with one somehow being stuck in a zombie state in Activity Monitor?

In any case, will definitely have a look and get back to you ASAP.

**Comment by bkuhlmann** [comment]
Thanks! Yeah, double checked upon waking the system this morning that Trailer didn't have multiple processes running within Activity Monitor. There was only one. Also, upon waking this morning, some of the repos that I had filtered out yesterday came back again. I re-applied new filters and then quit and relaunched Trailer and they are sticking again. I might be wrong about the relaunching of Trailer. It seems the problem is more when waking the system from hibernation that the error occurs.

**Comment by ptsochantaris** [comment]
Interesting - It sounds like the repo prefs are "returning" when a sync occurs, rather than when Trailer launches - I think the launch / wakeup from hibernation issue is incidental because that's when Trailer will perform a sync due to network returning.

Entirely possible that there's a missing "db save" when repo prefs are modified, and the change gets overridden by previous versions of their records during a sync. Or I could be totally off, this is just conjecture from me at this point - will investigate and let you know more soon :+1:

**Comment by ptsochantaris** [comment]
Hi @bkuhlmann, I've been playing around with Trailer quite a bit in the past few weeks, and during that time I've been keeping your issue in the back of my head, always trying to "catch" it, but for some reason I haven't been able to reproduce it at all.

Clearly I'm not implying this doesn't happen, but I think I'm clearly not going through the right steps to make it occur. When you have some time, and this is definitely not urgent, could you try and make a "dumb step-by-step" guide on how to reproduce this error? I'd really like to try and get to the bottom of it...

**Comment by bkuhlmann** [comment]
Thanks for trying to reproduce this. I'm wondering if it might be due to using the same API token for each machine I have Trailer on? Throwing that out there. I will see if I can get reproducible steps for you and respond back (I still hit this issue ever other week or so).

**Comment by ptsochantaris** [comment]
That's shouldn't be an issue. All data is local to each installation and Trailer does not write any info back to GitHub, so any changes you make on that machine or device, no matter what they may be, stay there. 

The only catch there would be if you un-watch a repo and re-watch it after a while, in which case Trailer will remove it from its list (and hence the related settings) from all installations that scan your watchlist. 

The above also holds true if there is some other reason why Trailer thinks that repo "went" away for some reason (i.e. it doesn't get it in the repos API call), that would also cause the specific repo settings to reset.

In any case, just brainstorming, there's no hurry here, but when.if you come find a way to reproduce this or have any kind of theory why it might occur, please *do* give me a shout.

**Comment by ptsochantaris** [comment]
Hi, I just wanted to drop you a line to see how this issue has been going for you? If it's still there give the latest (1.5.4) a shot - it has some improvements to Repo watching and some new options which you may find useful. If you get a chance give me a shout about it.

**Comment by bkuhlmann** [comment]
Thanks, I'm on 1.5.4 and things seem stable now. I haven't had any issues for several months so I *think* things are OK. It's been a difficult issue to track down so haven't had much feedback on this, I'm afraid. I'd say it's OK to close this issue as I haven't been able to sufficiently prove otherwise.

**Comment by ptsochantaris** [comment]
Hi and thanks for the update 👍 Let's hope the issue was fixed somewhere in the code cleanup that's been ongoing for the past few versions, although if you do end up seeing any issue please DO open up a new issue and we can keep investigating.
