### ISSUE TITLE
Optionally hide PR statuses that are not all green

### ISSUE THREAD

**Issue by bkuhlmann** [ptsochantaris/trailer#236]
![lables and statuses](https://cloud.githubusercontent.com/assets/50245/12805917/f4585692-cabd-11e5-9d6f-674b6fe17043.png)

After making use of this feature for a while I have more feedback/refinements. First, love this feature! However, there is a bit of an oddity when a build was green to begin with and then went red after a conversation began (i.e. someone added a `fixup!/squash!` commit, did a rebase, etc. that broke the build, etc). When this happens it's a little weird to see the PR drop off my list after I've participated.

Would it be possible to allow this feature to be refined to ignore all builds for which you have not participated in but once you have and the build goes red, well, then it's perfectly fine to keep showing the PR in the list at that point.

Thanks.

**Comment by ptsochantaris** [comment]
Hi @bkuhlmann - glad you're loving the feature!

Sorry I'm so late replying, it's a busy season!

So, it sounds like this feature is "trumping" your participation in the PR - the trouble is, if we reverse that priority then you will have all the red PRs show up in your participated section... Of course, from your description it sounds like this may be what we want in the first place: To only hide "red" PRs in the "All" section only.

I can add a "...only in the 'All' section" to the right of the checkbox you point to, similar to the line above it, which can achieve that. However, will this cover your use case? I.e. it will still keep the feature on, but it will only apply it to the "All" section.

Let me know your thoughts on this - it's entirely possible I may not have thought this all the way through :) But if it does work for you, I can go ahead and add it.

**Comment by bkuhlmann** [comment]
No worries, I know how that goes.

Yeah, good point. I hadn't considered that the checkbox could be limited to how you define your Watchlist settings as either "All", "Participated", "Mine", or "Hide". I like that a lot and by updating the text for the checkbox to specify that PRs are hidden for only those in the "All" section will help clarify what the purpose of the checkbox is.

That would be a great solution. Thanks!

**Comment by ptsochantaris** [comment]
Hi, I think I have a first build for you to try out. Give it a shot and let me know if I've understood your requirement correctly (and also see if it works well, I wasn't able to extensively test it out, although I did give it a few sanity runs :))

https://www.dropbox.com/s/nnkun93dpkeze0r/Trailer-hideInAll.zip?dl=0

**Comment by bkuhlmann** [comment]
Thanks! Downloaded and installed. Will need a couple of days to test this out, though. Will have to get back to you later next week after I've had some time to use this more.

**Comment by ptsochantaris** [comment]
There's absolutely no hurry, thanks for testing.

**Comment by bkuhlmann** [comment]
Closing this issue after using the new build for a week. Everything is working well, no issues. Thanks for the fix!

**Comment by ptsochantaris** [comment]
Great, thanks for testing and letting me know! I'll prep an update within the next few days that also includes some preferences pane tweaks and send it up! :+1:

**Comment by ptsochantaris** [comment]
Version 1.3.14 is now up and includes this feature.

**Comment by bkuhlmann** [comment]
Thanks! Downloading now. :smile:
