### ISSUE TITLE
Minimum scopes for token

### ISSUE THREAD

**Issue by iosdeveloper** [ptsochantaris/trailer#237]
Which scopes are required to be checked for Pocket Trailer to work when creating the token?

**Comment by ptsochantaris** [comment]
Ah, thanks for asking, I see Github no longer sets defaults for new tokens!

Making a note to issue an update with the appropriate instructions in the preferences window.

Here's a screenshot of the token scopes I use, note that "repo" needs to be selected from the top checkbox, not just the 3 sub-children, assuming you want Trailer to access your private repo info (if you only want to check public repos, you can skip this of course). I think those should be all you need, at least they seem to work fine for all my PRs and Issues for now.

<img width="476" alt="scopes" src="https://cloud.githubusercontent.com/assets/521581/13178701/3b2030ca-d718-11e5-882b-42196e51b5d3.png">

**Comment by ptsochantaris** [comment]
Version 1.3.14 is now up and includes notes on the preferences and quick-start views about the minimum required permissions in case you or others need this info in the future. 

Thanks again for letting me know about this!

If you encounter any other permission-related hiccups in the future, please do let me know so I can update the permission list with anything I may not have picked up on.
