### ISSUE TITLE
Trailer notifies of my own PR comments when my username is mentioned

### ISSUE THREAD

**Issue by pedrocunha** [ptsochantaris/trailer#240]
Hi,

I think there is a bug on how trailer handles self PR comments when the same user is mentioned.

Replicate with: Write a comment in a PR with your `@username` in it.

Cheers

**Comment by ptsochantaris** [comment]
Ah, that is entirely possible - probably just naive coding from my end. What do you think @ptsochantaris?

**Comment by ptsochantaris** [comment]
I concur. Thanks for spotting this @pedrocunha, will fix!

**Comment by ptsochantaris** [comment]
Hi, version 1.3.16 is now up and should correct this issue, thanks again for reporting it!
