### ISSUE TITLE
"Squelch" notifications for a particular PR

### ISSUE THREAD

**Issue by tooluser** [ptsochantaris/trailer#241]
One of the features Github has is the ability to silence notifications for a particular PR. This would be ridiculously valuable for Trailer! I have turned it on for 'alert' style notifications, to stay up to date - but I would love to be able to squelch specific PRs once I have decided I'm not involved. 

This could be implemented as a notification action, and/or an action in the menu on a specific PR, with accompanying icon to indicate. 

Thanks for a really fantastic app!

**Comment by tooluser** [comment]
Heh, indeed, it’s far too useful to call it uncluttered. ;-) But it’s all good, so it’s worth it! 

I like the faded-out version more than an icon, that’s definitely better, nice.  

Do alerts on MacOS support actions as they do on iOS? If they do, you could mute from that menu, too. It’s usually on seeing a new PR — or getting one too many alerts from a conversation I’ve checked out of — for example, that I’d decide ‘no more on this subject’. So affording it in the alert would be good too. 

I haven’t looked at the project yet; I haven’t much swift experience.

**Comment by ptsochantaris** [comment]
Ok, I think I may have a version ready for testing with this feature :+1: Give it a shot below and let me know how it works and/or any feedback you may have on it. (The equivalent features will also be on the iOS version too)

To answer your question about OS X notification actions, yes, you can have multiple actions just like iOS (and the build above supports them) BUT they are only visible on each notification if you are using "Alerts"-style notifications for Trailer and not "Banner" (you can change these per-app from Settings anytime) With the Alert-style notifications, clicking and holding down on the "Show" button will provide the other options.

https://www.dropbox.com/s/ykslnth0c04a1ft/Trailer-mute-test.zip?dl=0

Let me know how it goes!

**Comment by tooluser** [comment]
This is great! And unbelievably fast! Thank you so much for being so responsive. I love the grey-ed out items; the UX is great. 

After a day of usage, I have only impressions, into which I have not dug deeper. 

Toward the end of the day, I swear I saw two things:
	- some notifications I thought would have been blocked. It’s _possible_ they were just identically-named but distinct PRs.
	- some duplicates. I would mute one, and then see it again within a minute. This started only late in the day.

	I’ll dig more, but wanted to mention those two.

**Comment by ptsochantaris** [comment]
Thanks for testing and for the quick feedback!

I'm really glad you're liking it so far, and that the "fade" UX makes sense :+1: The way I see it, feature suggestions are extremely valuable, and I can't add requested features fast enough, especially if they are relatively simple to add, like this one :)

Interesting about the notifications you mention, I am leaning to your own explanation that these could have been similarly named PRs, as the notification "filtering" is a simple `if` statement at its core really, but I certainly wouldn't rule out some logic slipping through on my implementation! Let me know if you spot this again and I'll look into it.

About the duplicates, I'm not entirely sure what you mean? Do you mean you would mute an item and then see the identical item un-muted next to it? When you get the chance, can you give me a bit more info on that?

**Comment by ptsochantaris** [comment]
Hi!

Just wanted to let you know I've updated the release and it now includes this feature as standard (the iOS version is waiting for review in App Store too :)).

I'm going to close this for now, but if you do encounter any more of those duplicates or any issues with it going forward, please *do* open a new issue and I'll look into it ASAP.

Thanks again for suggesting this, and as always please feel free to add more feature suggestions as issues.

**Comment by tooluser** [comment]
I saw that! Thanks a million! 
I swear I just got a duplicate, but I had closed one before I had time to grab any info. I’ll keep an eye on it.

Thanks again for your extraordinary good work and alacrity. We love Trailer!

**Comment by ptsochantaris** [comment]
You're very welcome, and I'm delighted Trailer is making your life easier!

Yes, please *do* make a new issue about the duplicates when/if you spot more and can see any sort of pattern. I will definitely keep an eye out for these duplicates as well.
