### ISSUE TITLE
New Reactions?

### ISSUE THREAD

**Issue by applimatix** [ptsochantaris/trailer#246]
Would be nice if Participated could also include comments/issues I have reacted to.

Ideally a reactions count would also be useful as we now thumbs up using reactions rather than comments.

**Comment by ptsochantaris** [comment]
That makes a lot of sense @applimatix - I'm all for it, but I'm not sure if there is API support for retrieving the reactions yet?

I just took a (admittedly very quick) glance at the API docs and I didn't find any reference to reactions, but are you perhaps aware of how reactions are handled in the GitHub API?

If we can access reactions via the API, I would definitely agree that reactions should be treated like comments for the purposes of including items in Participated, etc.

**Comment by applimatix** [comment]
Sorry I couldn't find any info either. I have contacted Github support to see if / when it will become available, so I'll let you know what I hear.

**Comment by applimatix** [comment]
Response below:

Hi Mike,

Thanks for getting in touch! Other users have expressed interest in an endpoint for GitHub Reactions, and I've added your support for it to our internal wishlist. It might be something we support in the future, but we can't promise when it will happen.

If there's anything else you'd like to see improved, please feel free to write back.

All the best,
Francis
@francisfuzz
GitHub Support

**Comment by ptsochantaris** [comment]
Hi @applimatix - thank you for sharing your investigation, it's really useful info 👍

So, unfortunately it seems we don't have access to the reactions (yet) but let's leave this issue open for a while, as it's a valid and useful feature request that I'm sure other users will also eventually request, and as @francisfuzz mentions the API support for this may come our way eventually.

I will be keeping an eye out for reaction support in the API, but if you (or anyone reading this) notice that it has been added in the meantime, don't hesitate to post a comment here to "wake up" this thread so we can move ahead with the feature.

**Comment by ptsochantaris** [comment]
There seems to be an experimental API for reactions out there, so hopefully we can have reaction support sooner rather than later: https://developer.github.com/v3/reactions/

The current form may make it quite heavy on API usage, and GitHub is asking for suggestions, so I'll definitely pitch in with a couple specifically related to keeping API load down (and also getting more info on the users who posted a reaction - currently the API only provides an ID with not much to link it to a user account)

Anyway, just wanted to keep you up-to-date! More details soon, hopefully.

**Comment by ptsochantaris** [comment]
Hi @applimatix, just wanted to let you know that v1.5.6 is up, which has preliminary support for reactions (as well as reviews). Do bear in mind that these APIs are beta, so they may break or act weirdly, but if you're feeling adventurous feel free to enable support for reactions and see how it goes.

I'm going to close this specific issue for now but please feel free to open more issues related to support for reactions, any bugs, or suggestions behaviour, or logic that you would like to see are very welcome.
