### ISSUE TITLE
'Mute' should close any open notifications for the muted item

### ISSUE THREAD

**Issue by tooluser** [ptsochantaris/trailer#247]
Now that I've had a couple weeks to live with Muting (yay!) it occurs to me that it's very common that I mute a given item, and then go through and close all the still-open notifications related to it manually. 
It'd be nice if they just closed. 

AC - 
With notifications in 'alert' mode
when clicking 'mute' as the action
other notifications from the same PR are closed

Thanks again for an awesome tool!

**Comment by ptsochantaris** [comment]
Hi @tooluser - Yes, this makes a lot of sense, if you mute something then it follows that you are either already aware, or disinterested, in any further context that past notifications could have provided. I'll add this on the next update 👍

**Comment by ptsochantaris** [comment]
Hi, I was just doing some code gardening in preparation for the snoozing feature, and this was a pretty quick addition, so I've quickly made a build that contains this feature - let me know if it works well enough for you:

https://www.dropbox.com/s/c85r4em736omjj8/Trailer-mute-notifications-test.zip?dl=0

I debated about doing the same for when an item is removed (either automatically or through the "remove" buttons) but decided it's too jarring a change in behaviour, as some people may remove items and still use notifications as some sort of "ultra-recent" history. Still, I've got a feeling that options for this would be a good idea (for instance, picture hitting "remove" on top of the "recently merged" section and getting rid of all the merge notifications as well. I would definitely use that :)) What are your thoughts on this?

**Comment by ptsochantaris** [comment]
Upon further thought, I think the point is academic TBH - I really want that feature so I added it anyway :) It's default off, of course, but you can find it and turn it on in "History" in preferences on the build below if you want it as well (note that this doesn't affect the "mute" functionality you suggested, that one is always on)

https://www.dropbox.com/s/l8qxt5yyyuwytxe/Trailer-mute-and-general-notifications-test.zip?dl=0

**Comment by tooluser** [comment]
Of course you did. ;-)

I’ll check it out!

**Comment by ptsochantaris** [comment]
Just refreshing your build with RC1, please do let me know if you run into bugs or weird behaviour: https://www.dropbox.com/s/zii3qtj2wzwznw8/Trailer-1318-rc1.zip?dl=0

**Comment by ptsochantaris** [comment]
Just a quick note: If you are running any OS X before El Capitan, this development build will not migrate properly to the final version. Please be sure to export your settings before upgrading (or just do an export now and have it handy :)) so you can re-import them after the upgrade, or you will lose all your configured repos.

**Comment by ptsochantaris** [comment]
Hi, v1.3.18 is now up, but remember the warning above before upgrading from the test build!

Thanks again for the suggestion, and please feel free to open more issues with ideas and feature requests!
