### ISSUE TITLE
Milestone support

### ISSUE THREAD

**Issue by cmluciano** [ptsochantaris/trailer#251]
My team uses milestones as "sprints". Occasionally I will come up with a issues/stories that I want to work on next sprint and it would be great to hide/filter them until that milestone comes around.

**Comment by ptsochantaris** [comment]
Hi @cmluciano - This is a good point. I can see from the API docs that milestones are exposed, and we can use the "description" field as a searchable property. For instance, you could type `milestone:1.0` to search of all milestones containing 1.0 (and conversely using the `!` notation to exclude them).

Would this help you as a feature?

**Comment by cmluciano** [comment]
Yes that sounds great to me!

**Comment by ptsochantaris** [comment]
Here's a prerelease build with this feature, let me know if it works like you expected. One correction to what I said above, though, it's using the "title" property, not the description property:

https://www.dropbox.com/s/a2fzp2lek0gcpmj/Trailer-1318-rc2.zip?dl=0

**Comment by ptsochantaris** [comment]
Hi, just wanted to let you know version 1.3.18 final is out now which includes this feature. I hope you find it useful, and feel free to open more issues with ideas or suggestions in the future!
