### ISSUE TITLE
Disable 'API limit' popup

### ISSUE THREAD

**Issue by andycroll** [ptsochantaris/trailer#252]
<img width="504" alt="screen shot 2016-04-28 at 11 57 43" src="https://cloud.githubusercontent.com/assets/2780/14883815/719adea6-0d38-11e6-9754-064eaeebb9cc.png">

Any way to make this window permanently dismissible? I have a half hour until it resets and it'll be fine, but the window pops up every 3 minutes.

Perhaps move it to a 'notification' rather than a 'you must dismiss me' window.

**Comment by ptsochantaris** [comment]
Adding an option to make this a notification rather than a popup makes a lot of sense 👍 
In the meantime I would suggest you set your refresh intervals to be a bit higher - I have mine at 10 minutes for instance.

**Comment by ptsochantaris** [comment]
Here's a tweaked build of the just released 1.3.18 version that will only show you the dialog once for each occasion. When the API limit is back down and you happen to cross over it again, it will show again. This should definitely improve your experience, but still keep those important warnings there to dissuade users from abusing the GitHub API.

https://www.dropbox.com/s/jpdeazzjif8iak4/Trailer-1319-rc1.zip?dl=0

**Comment by ptsochantaris** [comment]
1.3.19 Is now out and should contain the above modification. Do you think it's good enough, or do you believe that there should be an option to turn this into a notification either-way? I would feel a bit reluctant to do this, but I'm always open to a convincing argument! :)

**Comment by andycroll** [comment]
I think the current solution is a decent solution. I'd think notifications might be a good solution if you _looking_ for something to build 😉
