### ISSUE TITLE
One API connection timeout can cause the entire sync to fail

### ISSUE THREAD

**Issue by ptsochantaris** [ptsochantaris/trailer#255]
When syncing a lot of data, especially after a long period of bring dormant, like when a Mac has been asleep for a while or the iOS app hasn't been launched in ages, Trailer needs to make a lot of parallel API calls, perhaps thousands, in the case of very heavy repos with a lot of statuses and labels.

While this can't be avoided, in some cases (and the larger the number of calls, the higher the probability of this occurring) one of these calls will time-out for whatever reasons (GitHub may be deploying code to a server, connection burp, or any other reason) and this will take down the entire sync and display the red "X" on the status bar. Most usually the next refresh cleans this up, but it's wasteful of both bandwidth and API to refresh everything twice.

It would be nice if Trailer's API fetching can detect a timeout (rather than an error code from GitHub) and retry the same call after a short pause a coupe of times. This would greatly reduce occasions of "red X", put less strain on GitHub API, reduce a user's API quota usage, and in general make Trailer a better behaved API client.

**Comment by appleprtest** [comment]
Test comment

**Comment by appleprtest** [comment]
Test comment 2

**Comment by ptsochantaris** [comment]
This feature is now in the latest 1.3.20 release.
