### ISSUE TITLE
Expose assignee as a filterable option

### ISSUE THREAD

**Issue by cmluciano** [ptsochantaris/trailer#257]
I author quite a bit of issues, but some of these are for other people. It would be great to have a dropdown per repo for "assigned".

**Comment by ptsochantaris** [comment]
Makes sense 👍 Although I'm thinking it may be better to use "assignee:" to match GitHub's terminology, so something like "assignee:cmluciano" for instance?

**Comment by ptsochantaris** [comment]
Here's a test build: https://www.dropbox.com/s/3e1jiiewegtmeqm/Trailer-Assignee-Test.zip?dl=0

Let me know how it goes.

(As always when switching between dev versions and finals, make sure you export your settings first *just in case* you lose your config!)

**Comment by cmluciano** [comment]
This works great through the filtering list. It would be awesome to expose it through here too 
<img width="393" alt="screen shot 2016-05-11 at 9 59 04 am" src="https://cloud.githubusercontent.com/assets/4790487/15183437/0fc1f8be-175f-11e6-9d75-667c69bd44d5.png">

**Comment by ptsochantaris** [comment]
Interesting, how would you suggest it's exposed?

**Comment by tylerneu** [comment]
I have a similar flow as @cmluciano. Could `Mine` be split out into `Created` & `Assigned To`?
