### ISSUE TITLE
App keeps crashing on latest release

### ISSUE THREAD

**Issue by cmluciano** [ptsochantaris/trailer#258]
I upgrade to version  1.3.21 (1296) today and since then the app keeps crashing for me. I uninstalled and reinstalled to no avail. I grabbed the crash report from my console and posted it in a [gist](https://gist.github.com/cmluciano/a901b9c1d2601520a90d19461cc158e0)

**Comment by ptsochantaris** [comment]
Thanks for calling this in, checking it out now.

**Comment by ptsochantaris** [comment]
The crash report is a bit vague... Can you activate logging activity from Misc->Logging to see where it might be blowing up?

**Comment by ptsochantaris** [comment]
Also, in case this is happening on a public resource, could you activate the API logging as well? It may help to have to JSON response that Trailer is chocking on.

**Comment by cmluciano** [comment]
I'm trying to get into this. It unfortunately has been crashing immediately on load before I can activate the switch

**Comment by ptsochantaris** [comment]
Ah, yes, I should have added, you may want to turn your network off to prevent it from syncing - that's where it's breaking.

**Comment by cmluciano** [comment]
Not sure if this helps or not, but it seems to be segfaulting after a small period of syncing.

<img width="753" alt="screen shot 2016-05-13 at 4 26 45 pm" src="https://cloud.githubusercontent.com/assets/4790487/15260933/84992256-1927-11e6-9a40-b6682902096f.png">

**Comment by cmluciano** [comment]
It sat for a period of time with the network turned off, but crashed soon after when turned back on

**Comment by ptsochantaris** [comment]
Yes, the crash is definitely while it's syncing (or about to sync) an issue, the one that comes after the labels in the log above. Could you try this debug build with all the symbols in it so we can get a more accurate crash report? It will crash exactly like the other one, but if you can, send me that crash report. That will give us more info 👍 (You can go ahead and send it directly to my email at ptsochantaris AT me.com)

https://www.dropbox.com/s/48c8xelw5e8nbph/Trailer.zip?dl=0

**Comment by ptsochantaris** [comment]
Hm, I think I have a theory about the crash, but will wait for your log to verify it.

**Comment by cmluciano** [comment]
Sent

**Comment by ptsochantaris** [comment]
Cool, can you try this build? If it still crashes, please forward the crash report again: https://www.dropbox.com/s/48c8xelw5e8nbph/Trailer.zip?dl=0

**Comment by ptsochantaris** [comment]
Hm, just to be sure I sent you the right file, try this :) https://www.dropbox.com/s/jgzbodpcfa8nykp/Trailer2.zip?dl=0

**Comment by ptsochantaris** [comment]
And in case that crashes too, let me know, and then try this: https://www.dropbox.com/s/n9w8p5wkhm6qccp/Trailer3.zip?dl=0

**Comment by ptsochantaris** [comment]
Any luck?

**Comment by ptsochantaris** [comment]
So, what I think is going on with your copy locally is that your DB suddenly holds two or more copies of the same item from a certain API server. This should not happen, but somehow it did, from some sync glitch perhaps. The updates I've made will basically "skip over" any item with a duplicate ID in the database, causing it to be removed at the end of a sync (the original item will stay in the DB, of course) and this crash should  no longer occur.

I've updated the 1.3.21 release with these safeguards in case they happen to others: (you can get it from here: https://github.com/ptsochantaris/trailer/releases/tag/v1.3.21)

Let me know if the issue stops occurring for you. If for some reason it keeps persisting, back-up your API key(s) / export your settings, and remove the database at `~/Library/Application\ Support/com.housetrip.Trailer` to totally reset the app.

**Comment by cmluciano** [comment]
This new build has not been crashing anymore. Thanks for your time!

**Comment by ptsochantaris** [comment]
Glad it's fixed! 👍
