### ISSUE TITLE
Option to request desktop version of GitHub

### ISSUE THREAD

**Issue by dbrockman** [ptsochantaris/trailer#261]
It would be great if the iOS app had an option to request the desktop version of GitHub.

I haven't tried this myself but I think it should be possible to set the User-Agent header of the web view to the user agent string of desktop Safari.

[WKWebView customUserAgent](https://developer.apple.com/library/ios/documentation/WebKit/Reference/WKWebView_Ref/#//apple_ref/occ/instp/WKWebView/customUserAgent)

**Comment by ptsochantaris** [comment]
Hi @dbrockman, thanks for the suggestion.

While I totally agree with the feature itself, I'm a bit queasy about explicitly modifying a user-agent, unless it's to add a clear-cut addition that would enable desktop mode.

That said, I will definitely look into this and get back to you soon 👍

**Comment by ptsochantaris** [comment]
I think I found an clean way to handle this. I noticed that on iPad I always get the desktop version of the pages, and tried simply replacing "iPhone" with "iPad" on the user agent string, and it did the trick 👍 

I'll be sure to add add an option for this on the next update of the app.

**Comment by ptsochantaris** [comment]
Version 1.4.1 is up on the App Store now and includes this feature. You can find the new setting in the advanced settings panel. Have a go and let me know if it's working well for you.

**Comment by ptsochantaris** [comment]
Hi @dbrockman - I was just wondering if this option works for you as expected on your device?

**Comment by ptsochantaris** [comment]
Closing this for now, please feel free to reopen if you have any problems with it.
