### ISSUE TITLE
Separate team mentions and personal mentions

### ISSUE THREAD

**Issue by WilsonChiang** [ptsochantaris/trailer#267]
Could we have an option of having a separate area in Participated for team mentions versus personal mentions? I know we can change what "Participated" filters for, but it would be great to separate them so I can stay up to date with my team's mentions but still be able to see when someone directly mentions me.

**Comment by BMorearty** [comment]
I would like that (the alternative by @ptsochantaris). 

(Although for some reason I never see PRs with team mentions at all, at least when using GitHub Enterprise. I came here to see what I'm doing wrong.)

**Comment by ptsochantaris** [comment]
Hi @BMorearty and thanks for the input on the routing if items 👍

Currently team mentions are only checked on the main body of a PR or issue and not in the comments. Also the format is @org/team

So in your case, we have one of these unexpected cases
- Mention is is the comments
- Mention is in a different format, or
- Mention is in this format and in the body

Changing or fixing any of these should be quite easy. Open a new issue if you'd like, let me know which of the above is happening (I'm thinking it's probably the first), and I'll happily look into it! 👍

**Comment by WilsonChiang** [comment]
Sounds great. The main thing is I want to distinguish between mentions for my team and myself directly as my org team gets a lot of mentions. As long as they can be in separate sections I would be very happy. Maybe an option to create custom sections?

Keep up the great work, love Trailer. Has really helped my workflow.

**Comment by BMorearty** [comment]
Thanks, @ptsochantaris. I'll file a separate issue. 

Once I get that working, I will have the same issue @WilsonChiang is having: my team gets tons of mentions, so I'll want to separate out my own mentions from my team's mentions.

**Comment by ptsochantaris** [comment]
Hi @WilsonChiang! The latest beta here #289 has the new "multiple choice" routing options in preferences. If you are feeling adventurous have a go and let me know how it goes. I hope it's an improvement for your workflow!

**Comment by ptsochantaris** [comment]
Hi, this is now available as part of the 1.5.0 release which just went up. Please feel free to create more issues with suggestions and/or problems you may encounter.
