### ISSUE TITLE
Count pushes as activity on a PR

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#270]
Recently GitHub notification engine was improved and now I'm getting an e-mail when somebody pushes new commits to a PR even when it doesn't add matching comment to PR itself.

It would be great, if a push would caused PR to be marked as red as it happens, when new comment is added.

**Comment by aik099** [comment]
That would also would result in auto wake up for snoozed or stale (#273) issues.

**Comment by ptsochantaris** [comment]
This can be part of a wider feature which marks items with a "!" even if they have no comments. I'm thinking of introducing this together with an option to mark any new PR or Item with a "!" even if it starts off with no comments, and then also adding an option for what you suggest above (i.e. "mark PRs with an alert badge if there has been a recent push")

**Comment by ptsochantaris** [comment]
Hi, here's s a build which features this. You can activate it by selecting "Highlight PRs that have new commits" in the Comments section of preferences. Have a go and let me know how you get on with it.

https://www.dropbox.com/s/grtullrbctjk2xh/trailer155-rc.zip?dl=0

**Comment by aik099** [comment]
I can confirm, that it works. For PR where only new commits are added the "!" (exclamation mark) is shown in red bubble where "new comment count" is usually shown.

Not sure if PR having both new comments and new commits would show "!" or new comment count.

**Comment by ptsochantaris** [comment]
Good to hear!

When there are new comments, the numbering takes precedence over the exclamation mark.

Let me know if you run into any issues. I'm currently polishing up some code and keeping an eye out for any stability or logic regressions (the change required some deep plumbing tweaks) If all is well then I'll put up an update later this week.

**Comment by ptsochantaris** [comment]
v1.5.5 is up now and includes the feature. I'm going to close this issue for now, but as always feel free to open more issues with suggestions/problems you may encounter.

**Comment by aik099** [comment]
After performing an upgrade from the version you've posted on dropbox some random 9 PRs (out of 68) now display as having new commits (the `!` mark). Example PR: https://github.com/squizlabs/PHP_CodeSniffer/pull/1201

Not sure what caused this, but I probably can mark them as read.
