### ISSUE TITLE
Issue/PR snoozing state not reevaluated on snooze configuration change

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#271]
I have not used Snoozing features before and now I've configured it like this:

![2016-06-15_2300](https://cloud.githubusercontent.com/assets/1277526/16095432/2d852772-334d-11e6-9654-7bcbd8fbccc6.png)

After saving changes to configuration and even after restarting Trailer issue count haven't changed. I guess I have to wait for 1 more month (according to my configuration) to see any changes.

If snoozing state can be reevaluated automatically, then it would be good. Having "Reevaluated snoozing issues/PRs" button sounds good as well.

**Comment by ptsochantaris** [comment]
Hi! I think snoozing is probably the opposite of what you're thinking. Snoozing will make an item move to the "snoozing" section when you select "snooze" from their context menu (you can also hide the snoozing section if you like, to hide the snoozed items). This can be forever, or for the amount of time you specify. Additionally, items can auto-wake-up if any of the events below occur.

If you want to try out the feature, create a preset with 1 minute and snooze an item. Then wait a minute or so and see how it wakes up.

I suspect this tab isn't too clear on that, and perhaps a short description should be added somewhere there. What would be your suggestions for improving this?

**Comment by aik099** [comment]
> If you want to try out the feature, create a preset with 1 minute and snooze an item. Then wait a minute or so and see how it wakes up.

That unfortunately will mark all items (PR/issue) in the list as snoozed and will hide them. What I want is to actually make it work as configured - hide items older than 1 month.

> I suspect this tab isn't too clear on that, and perhaps a short description should be added somewhere there. 

What you've described is exactly what I thought it's doing:

* item marked as snoozed according to rules
* snoozed items will be hidden if such behavior is enabled
* fact, that new snoozing section will be created wasn't really explained on configuration page

**Comment by ptsochantaris** [comment]
Unfortunately, it's the exact opposite, sorry :( Snoozing is not about auto-hiding items that are older than a certain amount of time, although this could be a nice feature to consider (perhaps we can make a feature suggestion issue specifically for that?)

To snooze an item you have to manually right-click (or CTRL-click) and then select a snooze preset from the "snooze" menu in order to put it to sleep. It will wake up after a certain duration, a certain amount of time, and/or if any of the specified events occur.

And yes, it's definitely clear that this section needs better help/descriptions 👍 

I hope I'm not misunderstanding your point though, let me know if I am!

**Comment by aik099** [comment]
I had no idea, that you right-click on items in issue/pr dropdown. Now I know. Still when snoozing by hand feature is usable as now due auto wake support.

I've filed #273 with idea about stale status for issue/pull request.

**Comment by ptsochantaris** [comment]
Yeah, I think I need to explain this functionality more in preferences, definitely. I'm glad this helped clear it up a bit for you, though. I hope it ends up being useful. Will respond to your new issue in a little bit, I think some variation of what you propose there makes a lot of sense. 👍

**Comment by ptsochantaris** [comment]
Going to close this issue for now (having made a note to improve the snoozing prefs a bit)

See you on the other issue :)
