### ISSUE TITLE
Confusing UI, when configuring soozing

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#272]
When double clicking on soozing preset name an editing cursor appears and I can change it's name, but once clicking outside of input field changes are not saved.

I guess this is a mistake and preset name shouldn't be editable to a user, because it's name is auto-generated anyway.

Video: http://screencast.com/t/oIdFwZQJ17

**Comment by ptsochantaris** [comment]
Ah, thank you for spotting that, will fix it ASAP. Yes, the name is auto-generated and not meant to be user editable.

**Comment by ptsochantaris** [comment]
Version 1.4.3 is up now and fixes this issue, thanks again for reporting it.
