### ISSUE TITLE
Stale issue/pull request status support

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#273]
In open source world people participate in lots of issues/pull requests and sometimes issue/pull request author just vanishes without informing discussion participants. This results in open issue/pull request counter in menubar to stay large forever.

Proposing to introduce `is stale` flag for each issue/pull request.

New Settings (inspired by `Snoozing` setting group):
- `Consider issue/pull stale after [X] of inactivity`, where `X` is control where you specify day/month/week/year count
- `Hide stale issues/pull requests` - checkbox
  
  It would work like this:

When 1st setting (with day count) is entered (setting is optional by default), then Trailer on a regular basis will check last activity date on an issue/pull request (from ones it have in DB without asking GitHub). It an issue turns out to be stale, then it's assigned `is stale` flag internally.

If `Hide stale issues/pull requests` setting is enabled then all stale issues/pull requests are hidden from counter/dropdown. Otherwise all stale issues/pull requests are moved to new `Stale` sub-menu (e.g. like `Mine` or `Participated`).

When an update comes in on an issue (usually that results in red counter appear on a PR) then stale flag is removed from issue/pull request.

**Comment by ptsochantaris** [comment]
This looks very useful but, like you say, it is very close to the "Snoozing" functionality, so I'd like to think about integrating it there, to avoid creating a new menu section and whole set of preferences.

How about having an "auto-snooze item after X days inactivity" option in the snoozing preferences section? It ought to cover this requirement, I think.

**Comment by aik099** [comment]
> This looks very useful but, like you say, it is very close to the "Snoozing" functionality, so I'd like to think about integrating it there, to avoid creating a new menu section and whole set of preferences.

For now I've started to use snoozing functionality and help greatly. I no longer have huge issue/pr counts just because I've participated in them some time ago, but their authors have abandoned them.

> How about having an "auto-snooze item after X days inactivity" option in the snoozing preferences section? It ought to cover this requirement, I think.

Sounds good.

**Comment by ptsochantaris** [comment]
I'm really glad to hear it's useful (it wasn't my idea, but suggested here in the issues section, but it took a while to implement so I'm glad it's not just one person who's benefiting from it :))

Glad you agree on adding it to snoozing. Adding this to the TODO list.

**Comment by aik099** [comment]
> I'm really glad to hear it's useful (it wasn't my idea, but suggested here in the issues section, but it took a while to implement so I'm glad it's not just one person who's benefiting from it :))

Your app is a major time saver and `one of a kind` app for that task (tracking issues/prs across all participated repositories).

**Comment by ptsochantaris** [comment]
Version 1.4.3 is up now and contains the option to auto-mark items as snoozed after a certain amount of days. Let me know how you get on with this.

**Comment by aik099** [comment]
The control for choosing day count is hard to use, because you to have 60 days detail you need to click 60 times. See: http://screencast.com/t/uN73VMJJ2g

**Comment by ptsochantaris** [comment]
@aik099 Ah, thanks for the feedback, may update this on a next update. However TBH this isn't a setting that changes too often. Also, for now, you can just keep the arrow pressed on any particular direction instead of clicking repeatedly.
