### ISSUE TITLE
OSX Yosemite label text alignment

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#274]
On Yosemite (maybe on El Capitan too) there are following UI issues, when I choose to see labels of PRs:

* label text isn't vertically aligned on the label itself, as it's done on GitHub
* the spacing between `PR title and labels` and `labels and next row` seems to be different (or it looks that way), which makes it harder to see what's been displayed in last row (with repo name)

![2016-06-16_2147](https://cloud.githubusercontent.com/assets/1277526/16129098/1f0a41fe-340c-11e6-82e9-50df0770699f.png)

**Comment by ptsochantaris** [comment]
I think this may have to do with Yosemite's text rendering not respecting the vertical centring attribute for the labels. Will take a closer look at it though and get back to you.

**Comment by ptsochantaris** [comment]
Version 1.5.0 which is now up should include a slightly improved baseline alignment for label strings. Hope it improves things a bit. It's worth noting that the fonts used in Yosemite will unfortunately end up producing a slightly "taller" label. This does not happen on later versions, and seeing that Sierra is just around the corner (and quite stable based on my usage the past months), I would recommend an upgrade :)

I'm going to close this issue for the moment but feel free to reopen or create a new one if you think there still is an issue.
