### ISSUE TITLE
Constant jumping of icon on menubar

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#279]
Since `groups` feature was introduced (in 1.4.x version) you can have sub-set of prs/issues icons for any repository group. That however is causing removing/adding of icons on the menu bar.

I'm using Bartender 1.x (see https://www.macbartender.com/) to position the app on menu bar. Icon remove/add fact drives Bartender crazy and that causes Trailer icon to be 1st in the list all the time.

**Comment by aik099** [comment]
Even without Bartender.app usage the Trailer icon is placed in menubar in the order the app is launched and fact, that it suddenly (not on every refresh, but surely after computer wakes up from sleep + no crash happens) moves from it's position to beginning isn't good.

**Comment by ptsochantaris** [comment]
Thanks for reporting this.

Interesting. At some point the icons *do* get recreated, but this happens only in some specific cases, specifically when importing/altering related settings and dark mode change.

I can see one case where Trailer will recreate the icons when the system wakes up, even if the dark mode hasn't changed, so this will definitely case your second issue - will fix.

For the first issue with Bartender, from what I understand it will move icons to the beginning if they are updated (not just recreated) and for this reason I've added the "do not grey out items when refreshing" option in the display settings section, which is probably what's causing the icons to be promoted at every refresh. Can you give that a shot and see if it keeps Bartender happy?

**Comment by aik099** [comment]
> I can see one case where Trailer will recreate the icons when the system wakes up

This is the case I'm seeing. Manual refresh doesn't cause jumping, but maybe automatic refresh does.

> For the first issue with Bartender, from what I understand it will move icons to the beginning if they are updated (not just recreated) ...

There is something else to it, because:

* I do have other apps in menubar, that change their icons (e.g. Skype) and that doesn't cause them to jump to beginning of menu bar
* this was working in Trailer 1.3.x, so there is definitely something changed in 1.4.x that causes this

> Can you give that a shot and see if it keeps Bartender happy?

Manual refresh changes icon into grey one, but that doesn't cause the move to beginning of menu bar.

**Comment by ptsochantaris** [comment]
Cool - ok, at least for the first part, this build ought to fix your issue. Have a go and let me know if it helps: https://www.dropbox.com/s/pnl0ttbhjpg0rcw/Trailer-wake-menu-fix.zip?dl=0

There's not that much difference between automatic and manual refresh in the code TBH, so anything that Trailer does by hitting Cmd-R should be the same as when it automatically decides to refresh. Let's see what things improve with this build. It should help you get an even better idea of the circumstances under which the Bartender issues occur.

Thanks for testing and reporting the issue. We'll get to the bottom of it soon.

**Comment by aik099** [comment]
Actually you fix that issue with icon move on wake up and then I'll install it and see if jumping will happen at all.

**Comment by ptsochantaris** [comment]
Yep, this build should fix that issue.

**Comment by ptsochantaris** [comment]
Have things improved for you at all on this build?

**Comment by aik099** [comment]
I'm not receiving any update. I'm on 1.4.2 version.

**Comment by ptsochantaris** [comment]
Ah, I think I had forgotten to put out a 1.4.2 GitHub release. Will have to fix that. But what I meant was the build I created above, following this link: https://www.dropbox.com/s/pnl0ttbhjpg0rcw/Trailer-wake-menu-fix.zip?dl=0

**Comment by aik099** [comment]
I can confirm, that during wakeup menu icons no longer jump.

**Comment by ptsochantaris** [comment]
Ah, great! 👍 I guess my second question would be, does this improve the situation with Bartender for you as well? We may have a better picture of what's going on now that this issue is out of the way.

**Comment by aik099** [comment]
Yes. I've tested these cases:

1. close lid (causes short term sleep) > wait for 8h (that causes long term sleep) > open lid
2. open lid > don't do anything for 20 minutes (causes short term sleep) > open lid
3. waited for auto-refresh to happen

In all cases icons stayed in their place.

**Comment by ptsochantaris** [comment]
Brilliant, thanks for testing! I'll send out a small incremental update soon to ensure this is fixed for others as well.

**Comment by aik099** [comment]
Thank you for quick fixing.

**Comment by ptsochantaris** [comment]
Version 1.4.3 is up now and should correct this issue for good. Feel free to close the issue if all is good.
