### ISSUE TITLE
Snoozing improvements

### ISSUE THREAD

**Issue by dangitall** [ptsochantaris/trailer#280]
Thanks for an awesome tool! Trailer makes my life better.

I mute a lot of the PRs that come through and I find that these muted PRs dilute the useful information that Trailer gives me. I'd love it if:

- The project list was at least sorted giving priority to non-muted PRs. It is annoying to have to scroll down through ones I don't care about to find the ones I do want to see (when there are too many to fit on my screen). Even better, though, would be an option to have them not displayed at all!
- Regardless of how or if muted PRs are displayed, it would be nice if the menu bar count only reflected non-muted PRs. If I've already said I don't care about a PR then I certainly also don't care how many of them there are.

Thanks for all your work!.

**Comment by ptsochantaris** [comment]
Hi @dangitall, I'm really glad Trailer is making your life better! 👍

Muting is a lightweight feature mostly to get an item to "shut up for a minute" and not for longer-term use TBH :) Instead, what you describe sounds very much like the "snooze" functionality, which is similar to muting, but more "heavy handed". I.e. it lets you mark an item as snoozed for a while (or forever) which can be then woken up depending on certain time & event criteria (or never).

From what you describe, you probably want to do the following in the "Snooze" tab in preferences:
- Add a snooze preset, and don't configure anything about it, so it stays as "Until event or manual wake".
- Disable the "new comment", "mentioned", and "status item update" options to ensure snoozed items stay snoozed.
- After that, you can right-click over items on your list and select to snooze the items you won't want in your main list.
- The selected item will move to the "snoozed" section. If you prefer not to see the snoozed section at all (and/or not having snoozed counted as you mention) you can hide this section by selecting the "hide snoozed items" option in the same preference pane.
- Snoozed items are treated as muted, i.e. you will not get notifications for comments, etc, from a snoozed item.

<img width="456" alt="screen shot 2016-07-06 at 17 38 06" src="https://cloud.githubusercontent.com/assets/521581/16626390/8dd4e820-43a0-11e6-8ee9-bafac8e7221f.png">

How much does this workflow cover your needs above? Is there something still missing? Let me know how it goes (or if I've misunderstood your requirement!)

**Comment by dangitall** [comment]
Ah, yes, you're right, snoozing does pretty much cover the functionality I was looking for. Thank you!

A couple of things that feel like it would make it more useful to me:

- If I could assign a hotkey to specific snooze presets (hitting ⌘-M is so easy), that would be super nice!
- If the options for waking and hiding a snoozed item were preset specific (so that I could use one preset to truly snooze and another to silence/mute).

Thanks so much!

**Comment by aik099** [comment]
Agreed on `Command+S+[Number]` shortcut.

**Comment by dangitall** [comment]
That sounds fine to me though it might be slightly odd from a usability issue in that deleting one preset could cause the hotkeys for all the others to change.

**Comment by ptsochantaris** [comment]
Yes, that could be a bit weird but I'm not sure how often one would edit the snoozing presets. It's more of a case of settling on a preset set that one uses often. However, this could combine with the ability to drag-and-reorder the existing snoozing presets, which is something I've wanted to add fro a while there. This way a user can ensure that nothing goes "out of order" if they make one edit, for example.

**Comment by dangitall** [comment]
I agree, the ability to reorder the presets would mitigate the issue.

**Comment by ptsochantaris** [comment]
I took the liberty of renaming your issue just to help disambiguate it from other issues and to make it clearer what it's evolved into. Summarising here what I think Trailer could definitely benefit from as the result of the discussion (so far)
- Hotkeys for snoozing presets, most probably through a predetermined pattern of Cmd+S+[number] which corresponds to the number of the specific preset.
- Make conditions for waking up local to each preset instead of being global for all presets.

**Comment by aik099** [comment]
> Make conditions for waking up local to each preset instead of being global for all presets.

Haven't thought about it, but it can be helpful, because some issues just are not supposed to be woken up. 👍

**Comment by dangitall** [comment]
Thanks, @ptsochantaris. It seems to work great. My only issue is that after using the hotkey to snooze an item the cursor/highlight jumps up several items (perhaps to the first PR in "All items"? Hard to say for sure). It was a little surprising that it didn't go to the next (below) item after snoozing.

**Comment by ptsochantaris** [comment]
Ah, true, thanks for spotting that! I'll be sure to fix it in the next beta build and give you a shout when it's up.

(PS. In case you spot any other weird behaviour or crashes on the beta be sure to give me a shout as there have been quite a few internal changes in 1.4.4)

**Comment by ptsochantaris** [comment]
Version 1.5.0 is up now and includes all these changes. Please feel free to open further issues with suggestions or comments! Closing this issue for now.
