### ISSUE TITLE
Search query resets after mac Sleep

### ISSUE THREAD

**Issue by danwenzel** [ptsochantaris/trailer#281]
Repro steps:

- Type a search query: 

![image](https://cloud.githubusercontent.com/assets/11724146/16635183/0b268894-4386-11e6-93c5-b9e3ed1fe057.png)

- collapse the menu
- Put macbook to Sleep
- log back in

When opening Trailer back up, the search query is blank again:

![image](https://cloud.githubusercontent.com/assets/11724146/16635206/2f73d40e-4386-11e6-8afc-641ad2b4edbb.png)

This was definitely not happening in a previous version.

Current Trailer version: 1.4.2(1338)
Macbook version: OS X Yosemite 10.10.5

Let me know if you need any more info.  Thanks!

**Comment by ptsochantaris** [comment]
Hi @danwenzel and thanks for calling this in!

This is most probably related to the forced recreation of the windows when the system wakes up, which was done to cater for dark mode updates while the system was in power-nap.

The next update fixes this, so windows should not be recreated each time, only if there IS a change in dark mode after all :)

In case this is giving you headaches for now, this intermediate build should correct this: https://www.dropbox.com/s/pnl0ttbhjpg0rcw/Trailer-wake-menu-fix.zip?dl=0

**Comment by danwenzel** [comment]
I downloaded the intermediate build, and it works perfectly.  Thanks for the quick response!

**Comment by ptsochantaris** [comment]
You're very welcome. I wish I could say it was me being fast, but this was the exact same code bug that another user was suffering from here, so the solution was pre-packaged :)  However, it's still great to know this fixed it for you. A proper update should be up soon to make sure this is fixed for everyone. Thanks again for calling it in!

**Comment by ptsochantaris** [comment]
Hi, just wanted to let you know that version 1.4.3 is up now and should correct this issue for good. Feel free to close this issue if all is good.

**Comment by danwenzel** [comment]
Excellent, thanks again!
