### ISSUE TITLE
Partially cut off option names on "Snoozing" section in settings

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#283]
Partially cut off option names on "Snoozing" section in settings:

![2016-07-08_1341](https://cloud.githubusercontent.com/assets/1277526/16685996/8c50a4a8-4517-11e6-9f62-301c4998db37.png)

OS: Yosemite 10.10.5

**Comment by ptsochantaris** [comment]
Ah, thank you for reporting this. Yosemite system fonts are a bit wider, I should have caught this while testing on my Yosemite VM. Will upload a hotfix tonight 👍

**Comment by ptsochantaris** [comment]
Hi, this should improve in the latest beta: #289 (Sorry for the delay, my "tonight" turned into "just under a month", it's been crazy busy!)

**Comment by ptsochantaris** [comment]
Hi, this issue should now be corrected in the latest 1.5.0 release. Closing this for now.
