### ISSUE TITLE
Trailer 1.5 Beta for macOS

### ISSUE THREAD

**Issue by ptsochantaris** [ptsochantaris/trailer#289]
For the moderately adventurous, this is the latest build of Trailer.

#### Changes include
- Mentions, team mentions, and new items in owned repos can now be routed to any section.
- Support for multiple assignees when searching or detecting if an item as been assigned
- Snoozing logic improvements, improved keyboard shortcut support in macOS, and preset-specific wakeup options.
- In case launch fails because of a database incompatibility (or corruption), Trailer will no longer auto-wipe the database but will display a warning, offering the options to wipe the database or quit.
- Labels in preferences widened to improve readability in macOS Yosemite.
- "X" mode will no longer cause group status bar items to disappear.
- iOS app updated for iOS 10. Notifications are now expanded and use the same title / subtitle / body format of macOS notifications. The Mac-only option to automatically remove notifications for removed items is now also supported.
- Apple Watch app updated for watchOS 3, including the glance "summary" view in the main app.
- Under the hood: Updated for the latest Swift 3 / Xcode 8 toolchain, macOS Sparkle updater now v14.
- Database access settings updated to improve store robustness.
- Bugfixes & significant performance improvements.

#### Current stability
Using it on my work machine without problem, but always keep a backup handy in case you have mission-critical data in Trailer.

#### Latest (Beta build 31, updated  14 Sep 2016, 00:00)
https://www.dropbox.com/s/8xu81f6h6a8e4os/trailer-15-beta-31.zip?dl=0

#### Release date targets
- macOS: Next few days
- iOS: Now in the App Store

**Comment by NeckBeardPrince** [comment]
Why are you not hosting the beta on github as well?

**Comment by NeckBeardPrince** [comment]
On Sierra darkmode does seem to be broken in Trailer

**Comment by ptsochantaris** [comment]
Hi @NeckBeardPrince, it seems to be fine here on Sierra - can you elaborate a bit on what you mean? Are there specific steps to reproduce?

**Comment by ptsochantaris** [comment]
Ah, I see what you mean, the menu is still bright. Looking into it.

**Comment by ptsochantaris** [comment]
Hi @NeckBeardPrince, I think it's been fixed now. Sierra seems to have changed the NSAppearance being reported to the app for some reason, but we can still rely on the *defaults* setting. Can you download the latest build from above and give it a try?

**Comment by NeckBeardPrince** [comment]
@ptsochantaris LGTM 👍  thanks

**Comment by ptsochantaris** [comment]
Thanks for reporting it!

**Comment by ptsochantaris** [comment]
Version 1.5.0 is now up and can be downloaded through auto-update or from here: https://github.com/ptsochantaris/trailer/releases/tag/v1.5.0
