### ISSUE TITLE
Trail.app is crashing one second after starting

### ISSUE THREAD

**Issue by ssbarnea** [ptsochantaris/trailer#290]
```
11/08/2016 19:16:07.135 Trailer[29397]: ApplePersistence=NO
11/08/2016 19:16:09.114 Trailer[29397]: CoreData: error: (11) Fatal error.  The database at /Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite is corrupted.  SQLite error code:11, 'database disk image is malformed'
11/08/2016 19:16:09.114 Trailer[29397]: Core Data: error: -executeRequest: encountered exception = Fatal error.  The database at /Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite is corrupted.  SQLite error code:11, 'database disk image is malformed' with userInfo = {
    NSFilePath = "/Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite";
    NSSQLiteErrorDomain = 11;
}
11/08/2016 19:16:09.116 Trailer[29397]: CoreData: error: (11) Fatal error.  The database at /Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite is corrupted.  SQLite error code:11, 'database disk image is malformed'
11/08/2016 19:16:09.116 Trailer[29397]: Core Data: error: -executeRequest: encountered exception = Fatal error.  The database at /Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite is corrupted.  SQLite error code:11, 'database disk image is malformed' with userInfo = {
    NSFilePath = "/Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite";
    NSSQLiteErrorDomain = 11;
}
11/08/2016 19:16:09.129 Trailer[29397]: CoreData: error: (11) Fatal error.  The database at /Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite is corrupted.  SQLite error code:11, 'database disk image is malformed'
11/08/2016 19:16:09.129 Trailer[29397]: Core Data: error: -executeRequest: encountered exception = Fatal error.  The database at /Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite is corrupted.  SQLite error code:11, 'database disk image is malformed' with userInfo = {
    NSFilePath = "/Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite";
    NSSQLiteErrorDomain = 11;
}
11/08/2016 19:16:09.431 Trailer[29397]: CoreData: error: (11) Fatal error.  The database at /Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite is corrupted.  SQLite error code:11, 'database disk image is malformed'
11/08/2016 19:16:09.438 Trailer[29397]: fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=259 "The file “Trailer.sqlite” couldn’t be opened because it isn’t in the correct format." UserInfo={NSFilePath=/Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite, NSSQLiteErrorDomain=11, NSUnderlyingException=Fatal error.  The database at /Users/sorins/Library/Application Support/com.housetrip.Trailer/Trailer.sqlite is corrupted.  SQLite error code:11, 'database disk image is malformed'}: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-703.0.18.8/src/swift/stdlib/public/core/ErrorType.swift, line 54
11/08/2016 19:16:09.443 com.apple.xpc.launchd[1]: (com.housetrip.Trailer.281952[29397]) Service exited due to signal: Illegal instruction: 4
```

seems to be duplicate of #287 but I don't even get the prompt about the database being damaged.

**Comment by ptsochantaris** [comment]
Hi @ssbarnea - thanks for reporting this.

You won't get the prompt, as that is coming in 1.5. What you're seeing there is the same issue, basically your database file has become corrupt. The easiest way to fix this is to remove the directory with the DB and restore your settings from a recent settings export.

The other option is to try running an SQLite recovery/repair tool, but TBH I haven't had much experience with them so I can't recommend any. It seems that in some cases SQLite DBs can still be read even if corrupt, and you can copy the contents over, but I haven't tried this. This may be worth a look: http://techblog.dorogin.com/2011/05/sqliteexception-database-disk-image-is.html

Just out of curiosity what is your OS and Mac setup? Did you have a power failure? I've never had the DB corrupt this way on any of my machines, but it sounds as if Trailer ought to perhaps mount the DB with slightly stronger safety settings from 1.5 onwards...

**Comment by ptsochantaris** [comment]
Hi, just wanted to let you know that I've just added the tweak to the database options in the 1.5 beta here: #289 In case you're feeling adventurous, feel free to have a go with it. From this version onwards there should be no chance of a power failure or OS crash corrupting the database.

**Comment by dangitall** [comment]
FYI I'm all of a sudden seeing Trailer exit immediately after starting as well, but the errors I get are a bit different:

```
9/9/16 1:32:00.150 PM Trailer[1834]: CoreData: error: Mutating a managed object 0x7fdbe8d22a80 <x-coredata:///PullRequest/t11B7484D-F960-41AB-9FB5-F40DC2A2D3662> (0x7fdbe8db77c0) after it has been removed from its context.
9/9/16 1:32:00.150 PM Trailer[1834]: CoreData: error: Mutating a managed object 0x7fdbe8d22a80 <x-coredata:///PullRequest/t11B7484D-F960-41AB-9FB5-F40DC2A2D3662> (0x7fdbe8db77c0) after it has been removed from its context.
9/9/16 1:32:00.150 PM Trailer[1834]: CoreData: error: Mutating a managed object 0x7fdbe8d22a80 <x-coredata:///PullRequest/t11B7484D-F960-41AB-9FB5-F40DC2A2D3662> (0x7fdbe8db77c0) after it has been removed from its context.
9/9/16 1:32:00.150 PM Trailer[1834]: CoreData: error: Mutating a managed object 0x7fdbe8d22a80 <x-coredata:///PullRequest/t11B7484D-F960-41AB-9FB5-F40DC2A2D3662> (0x7fdbe8db77c0) after it has been removed from its context.
9/9/16 1:32:00.150 PM Trailer[1834]: CoreData: error: Mutating a managed object 0x7fdbe8d22a80 <x-coredata:///PullRequest/t11B7484D-F960-41AB-9FB5-F40DC2A2D3662> (0x7fdbe8db77c0) after it has been removed from its context.
9/9/16 1:32:00.150 PM Trailer[1834]: CoreData: error: Mutating a managed object 0x7fdbe8d22a80 <x-coredata:///PullRequest/t11B7484D-F960-41AB-9FB5-F40DC2A2D3662> (0x7fdbe8db77c0) after it has been removed from its context.
9/9/16 1:32:00.151 PM Trailer[1834]: CoreData: error: Mutating a managed object 0x7fdbe8d22a80 <x-coredata:///PullRequest/t11B7484D-F960-41AB-9FB5-F40DC2A2D3662> (0x7fdbe8db77c0) after it has been removed from its context.
9/9/16 1:32:00.151 PM Trailer[1834]: CoreData: error: Mutating a managed object 0x7fdbe8d22a80 <x-coredata:///PullRequest/t11B7484D-F960-41AB-9FB5-F40DC2A2D3662> (0x7fdbe8db77c0) after it has been removed from its context.
9/9/16 1:32:00.151 PM Trailer[1834]: fatal error: unexpectedly found nil while unwrapping an Optional value
```

I have no idea what triggered this, there was no power failure or anything. I just noticed that when I came in today that Trailer wasn't running. My best guess is that this started happening when my MBP came out of sleep. (15" Retina: 2.8GHz i7, OS X 10.11.5)

**Comment by dangitall** [comment]
Oh, I should add that I'm already running #289.

**Comment by ptsochantaris** [comment]
He @dangitall, thanks for letting me know. Is it possible you could provide a link to a crash log resulting from this? Will look into it ASAP.

**Comment by dangitall** [comment]
Here you go.

[Trailer_2016-09-09-133200_dangit.crash.zip](https://github.com/ptsochantaris/trailer/files/465646/Trailer_2016-09-09-133200_dangit.crash.zip)

**Comment by ptsochantaris** [comment]
Hi @dangitall - thanks for the crash report!

From the report I see the build is a bit older than the latest beta build (the version number indicates "1.4.4" which suggests that this is one of the older beta builds)

Would it be possible for you to download the latest build from #289 and see if it improves things? I've made quite a few changes to the code since then, so the possibility that this _may_ be fixed is non-trivial :)

OTOH if it keeps happening, could you attach a new crash report from that build? It would greatly help in locating the issue.

Thanks again for reporting and helping to fix this issue, we'll get it sorted out!

**Comment by dangitall** [comment]
Oh, I'm sorry! I thought I was running the latest. Indeed upgrading to 1.5.0 fixed the problem I was seeing. Thanks!

**Comment by ptsochantaris** [comment]
There's certainly no need to apologise. After all, the betas don't have auto-update (although they WILL auto-update to the final when it's out (very soon now)) That said, there's little chance the beta you are using right now will change before release (currently I'm regarding it as more of an RC TBH) unless anyone spots any issues.

I'm really glad this has fixed the issue, good to see that the code improvements I made had some impact 👍 Thank you once again for reporting this. Please DO report any issue you may see with the beta in the meantime.

**Comment by ptsochantaris** [comment]
1.5.0 is now live, please give it a go and feel free to open further issues with any problems or suggestions you may have. Closing this for now.
