### ISSUE TITLE
Trailer app starts twice in menu bar and crashes after a few seconds

### ISSUE THREAD

**Issue by rossgardt** [ptsochantaris/trailer#292]
The following screen rescording summarizes everything:
https://youtu.be/c8diX1t9q9Q

This may relate to some other issues I found. I just don't get any error log messages. Maybe I can delete the app's configuration files? Unfortunately I could not find anything under `/Library/Application Support`.

Best regards,
Benedikt

**Comment by ptsochantaris** [comment]
Hi @rossgardt - thanks for calling this in and the video capture. From your video Trailer doesn't seem to be starting twice, you're just seeing the issues and PRs menu items. They appear depending on whether you are monitoring PRs and issues from various repos and can be configured from the "Watchlist" section in preferences.

The crash you're experiencing afterwards is obviously a problem though :) and it seems to be happening while the app is syncing, so something is breaking there. Let's try the following steps to investigate:

- When an app crashes you can get a crash log from the Console app. Could you post a link to it here?
- Can you see if the crash is still occurring on the latest Beta linked to in #289 ?
- If it still is, you can reset all your Trailer data by removing the directory in `~/Library/Application\ Support/com.housetrip.Trailer/`.
- Another thing we can try is to enable logging from the "Misc" section in preferences after you have reset all your settings but before you re-configure and add the GitHub server, so we can get a better trace of what's happening from the Console app and see where your sync is blowing up.

Let me know how it goes!

**Comment by rossgardt** [comment]
- Using the Beta version did **not** solve the problem.
- Removing the _Application Support_ folder did the trick.

Please find an error report [here](http://pastebin.com/yTdBJFQS).

Thank you for the help!

**Comment by ptsochantaris** [comment]
Great, I'm glad this helped!

Thank you for putting up the crash report. I'm going to analyse it and see what went wrong, and try perhaps to prevent this crash from occurring in the future, if possible.

**Comment by ptsochantaris** [comment]
For what it's worth, it seems as if your crash was related to your login username disappearing from a API server record. I've added some code to try and re-fetch this data if it is missing, as well as safeguarding against the crash in the future. I'm going to update the beta build with this in a bit, so if you get this crash again in the near future, try the beta again and see if it will fix your issue.

Thanks again for calling it in!

**Comment by rossgardt** [comment]
I will keep it in mind. Thanks for the fast support! 👍
