### ISSUE TITLE
After disabling dark mode status bar items are still white

### ISSUE THREAD

**Issue by RobinDaugherty** [ptsochantaris/trailer#294]
When dark mode is enabled, Trailer's icons are changed to have a white foreground. But when dark mode is disabled, the icons are not changed back.

![trailer status bar](https://cloud.githubusercontent.com/assets/1005280/18413803/4bb1603e-7782-11e6-9f90-b6770ffa259e.jpg)

While most users might not see this, I found it because I'm using [f.lux](https://justgetflux.com), which sets dark mode at night and turns it off in the morning.

In my debugging, I see that `updateDarkMode` is being called when dark mode is disabled, it's calling `setupWindows`, and `currentSystemDarkMode` has the correct new value. But the status bar images and text are still drawn white, except for any red text in an icon, which is still drawn red and is visible in the status bar.

**Comment by ptsochantaris** [comment]
Hi @RobinDaugherty, thanks for reporting this and the investigation you've done. This issue (or perhaps one very similar to this) was solved quite recently, see here: https://github.com/ptsochantaris/trailer/issues/260

Either the version you are running is a bit older, or _more likely_ this is a regression. Can you give the latest beta (https://github.com/ptsochantaris/trailer/issues/289) a try and see if it still suffers from the problem?

(Also, how do I get f.lux to do the automatic dark-mode switch? I do use f.lux too, and haven't noticed the setting :) Can you give me a few pointers on how to turn it on?)

**Comment by RobinDaugherty** [comment]
The setting in f.lux is in their status bar menu (and apparently not in the Preferences dialog):
![flux dark theme setting](https://cloud.githubusercontent.com/assets/1005280/18418282/f186f256-7810-11e6-91ad-4b87ecc1b8be.jpg)

It sounds like it might be a regression. I don't recall how long ago it started happening, but I've been ignoring it for a while. I was experiencing this in the latest version of master as of yesterday, so at ce925bd97ccd91aa80202347bce2c20ef4c2e9ce.

**Comment by ptsochantaris** [comment]
Thanks for the tip! I can't see that setting on mine for some reason. Will investigate further :)

Back to the issue you're seeing, thanks for updating me on the version you're testing. It's definitely the latest code, so I'm going to try and replicate this locally and see why Trailer is missing the change (again :)) Stay tuned 👍

**Comment by ptsochantaris** [comment]
Ok, so the reason I can't see that setting is because of Sierra, apparently. Hope it becomes possible in the future, as it sounds like a nice feature to keep turned on :)

I've just updated #289 with a new build (30) that seems to fix this on my local testing (tested on a Yosemite VM). Can you have a go and see if it improves things for you?

**Comment by ptsochantaris** [comment]
Updated the beta once again, since the previous one seemed to keep the menu "light" even in dark mode, in Sierra. This new build should fix that issue.

**Comment by RobinDaugherty** [comment]
Unfortunately I'm on Sierra now, so I can't confirm that it changed on Yosemite. But it works correctly for me in Sierra!
