### ISSUE TITLE
Integration with hosted GitLab server

### ISSUE THREAD

**Issue by arnaugm** [ptsochantaris/trailer#296]
My GitLab server expects the personal token as a header with key "PRIVATE-TOKEN" or with a "private_token" parameter. Trailer sends it as a header with key "token" and is not customisable.
Could it be possible to choose the key to be compliant with the server?

**Comment by ptsochantaris** [comment]
Hi @arnaugm - is the GitLab API the same as GitHub's?

If so, is this the only difference between the two APIs? If it's just that, I'd be interested in adding an option for this. Do you have a link for documentation relating to GitLab's API?

I'd happily have a look, but if the two APIs diverge, it may not be possible to support GitLab.

**Comment by arnaugm** [comment]
Hi @ptsochantaris,

Reading some issues I though it was already compatible with GitLab and that was the only inconvenience.

Not sure how different are the APIs, didn't go that deep.
Here you have the documentation if you want to have a look https://gitlab.com/help/api/README.md

**Comment by ptsochantaris** [comment]
Hi - those docs definitely show a *similar* API to GitHub's, as they use many of the same concepts, but TBH I'd have to go through the API examples line by line to tell you what kind of differences there are. 

My impression is that there are differences throughout, so it's not just a question of authentication. I did notice, for instance, that comments are called "notes" and the API path for them differs, as well as many other entities that don't even exist in the first place on GitHub.

As it stands, it looks like it wouldn't be feasible to add "tweaks" for every API difference, it would end up creating a whole new code path in the existing code. 

Perhaps my answer to this issue may sum up my feelings and approach to adding a new API to Trailer (TL; DR: I'd love to, but it would mean creating a whole new swappable API layer which is not something I would prioritise: https://github.com/ptsochantaris/trailer/issues/264)

I certainly remain open to suggestions though. Let me know your thoughts.

**Comment by arnaugm** [comment]
Thanks for taking the time to look at the GitLab API and evaluate the possibility of supporting it.
I completely understand the complexity of giving support to a different API. Just a pity I can not use Trailer in this context as I find it very useful.

My main usage is to monitor PRs which helps the team to see how is the sprint going and if there are some who needs a code review.
I don't know if adding a minimal support to cover this would be possible or is still too much work.

In any case thanks and cograts for your project.

**Comment by ptsochantaris** [comment]
Sorry for not responding for a while. Yes, it's quite complicated to modify Trailer to have a more abstract API layer for syncing items. Maybe further down the line? Will be keeping an eye on GitLab :) 👍 

I'll close this issue for now, but if you have further thoughts and/or suggestions on any of this, please feel free to open new issues!

**Comment by axemaster** [comment]
+1 "_Thanks for taking the time to look at the GitLab API_"
I would also be interested in GitLab compatibility.  I am just noting this to show there is interest.

**Comment by akaralar** [comment]
We will unfortunately be moving from github to gitlab 😢 so I would be interested in a GitLab version as well.

**Comment by gegge87** [comment]
up for gitlab (if I search gitlab on app stores your app figures out, why?)

**Comment by genehynson** [comment]
Also would love to see gitlab support!
