### ISSUE TITLE
Lost focus on issue/pr on hover after click

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#298]
How to reproduce:

1. enable both issues and PRs in menubar
2. get some notification (e.g. comment added on issue; not sure if it matters)
3. move mouse over list of issues and see that issues under cursor is highlighted as cursor is moved
4. click on the issue, that received notification (maybe can be clicked on any issue) and see that issue opens in browser
5. open list of issues in Trailer again
6. see that issue under cursor isn't highlighted anymore

I guess focus state of issue/pr list is changed once click happens and that's why hover no longer works.

P.S.
This issue happens on `masOS Sierra`, but not on Yosemite.

**Comment by ptsochantaris** [comment]
Hi, unless I'm misunderstanding your report, this was always meant to occur - i.e. once you click on an item, it opens in the browser and the menu closes. When the menu is opened, the focus shouldn't be there anymore (if you want to keep focus when opening an item, try alt-clicking)

Apologies if I'm not getting it, please feel free to elaborate a bit more and I'll try to look into it.

**Comment by aik099** [comment]
I'm talking about issue row highlight on mouse over, not focus. Maybe I shouldn't have used `focus` term in last sentence.

Cursor is over 2nd issue, but it's not highlighted:
![2016-10-05_1209](https://cloud.githubusercontent.com/assets/1277526/19107399/b15d77a8-8af4-11e6-99fd-2bc4313173ad.png)

Cursor is over a PR and it is highlighted:
![2016-10-05_1209-1](https://cloud.githubusercontent.com/assets/1277526/19107412/bb99dc0c-8af4-11e6-86ae-5e9ac0c48db3.png)

**Comment by aik099** [comment]
@ptsochantaris , were you able to replicate this locally? You need to have macOS Sierra to see the problem.

**Comment by ptsochantaris** [comment]
Yes, I have - although I can't find a way to consistently reproduce it, and my time has been very limited these past couple of weeks. Will definitely get around to fixing this, though 👍

**Comment by aik099** [comment]
Glad you're at least saw what happens. No worries, for now I click on links from GitHub notification emails and use Trailer as counter for unread updates.

**Comment by ptsochantaris** [comment]
I don't think this has to do with notifications - the times I've managed to reproduce this are when I'm scrolling down a long list of PRs, then the "focus" just seems to go weird. Will look into this.

**Comment by ptsochantaris** [comment]
(Also bear in mind, you can still use keyboard navigation)

**Comment by ptsochantaris** [comment]
Ok, have a go with this build, see if it improves things for you: https://www.dropbox.com/s/59gcx6jgrh7y4x7/Trailer-focus-fix-Sierra.zip?dl=0

**Comment by aik099** [comment]
> (Also bear in mind, you can still use keyboard navigation)

I had no idea, that it's possible.

> Ok, have a go with this build, see if it improves things for you: https://www.dropbox.com/s/59gcx6jgrh7y4x7/Trailer-focus-fix-Sierra.zip?dl=0

Installed it. I won't know the results until I use it for some time though.

**Comment by aik099** [comment]
Looks like issue was fixed in that build.

**Comment by ptsochantaris** [comment]
Great news! I pushed an update out with this a little earlier (it's the identical build to what you have right now) because it fixed another Sierra issue, so I'm glad no further update is needed. Thanks for reporting it, and sorry once again for taking a while to respond, it's been very busy recently.
