### ISSUE TITLE
PRs & Issues from "Custom Repositories" are not displayed

### ISSUE THREAD

**Issue by obmarg** [ptsochantaris/trailer#307]
I've updated to the latest version of Trailer, and am trying to make use of the new "Custom Repositories" feature.  I have three custom repositories in my list, however no items from those repositories are actually appearing in Trailer.

**Comment by ptsochantaris** [comment]
Hi @obmarg - have you checked the visibility settings for the newly added repos? Have a look just in case they're hidden by default in your main repository list. After checking that, just in case, try a manual refresh.

Also, are these public repos by any chance? I could try and replicate the issue if so.

**Comment by obmarg** [comment]
You're right, they were set to "Hide" in my repositories list.  Updated that and they're appearing now.  Seems a bit strange that they defaulted to be hidden, but my bad for not checking.

**Comment by ptsochantaris** [comment]
Hm, there is a bug there indeed!

All custom repos should ordinarily take the permissions from the "for new repositories" setting, under the main repositories list. However it seems they're not, they're always added as hidden. I'll fix this asap, thanks for spotting it.

If it's OK with you I'd like to keep this issue open for a bit until I push out the next point release in a few days, just in case others encounter a similar problem.

**Comment by ptsochantaris** [comment]
v1.5.5 is up now and includes this fix. I'm going to close this issue for now, but feel free to open more issues with suggestions/problems you may encounter!
