### ISSUE TITLE
Repos list is empty

### ISSUE THREAD

**Issue by joaquinrulin** [ptsochantaris/trailer#310]
Hey! I just installed Trailer (v 1.5.5 1406) on OS X 10.11.6 and i got zero repositories on the list. The github token test was ok but no repositories were fetched.

Am i doing something wrong or is some kind of trailer/osx version bug?

**Comment by ptsochantaris** [comment]
Hi @joaquinrulin - no, there shouldn't be any issue with your OS X version, and 1.5.5 is the latest released version so that should be fine too. Are you sure you're using the token from the correct account (i.e. one with a list of repos on its watchlist?)

**Comment by joaquinrulin** [comment]
Sorry i was my problem! I thought the app would show you all your repos and you have to watch them right through the app not via github.

Thanks for the really quick answer

**Comment by ptsochantaris** [comment]
No worries, glad it worked out! Let me know if you run into any issues.
