### ISSUE TITLE
some watched private github repos don't show in repo list

### ISSUE THREAD

**Issue by olets** [ptsochantaris/trailer#311]
This may be a GitHub problem, not a Trailer problem: some of my watched private repos aren't adding to Trailer's repo list automatically.

I suspect GH might be to blame because these same repos don't show up when I search GH, even though they're owned by an org I'm part of and even though I'm working in the repo. I have a ticket in with GH about this. … But maybe that's just coincidence, maybe Trailer is missing some.

Afraid I don't have any ideas about what to look for, but I'm interested to hear if anyone else is having this problem

**Comment by ptsochantaris** [comment]
Hi @olets and thanks for calling this in.

I may need a bit more info from you to see if this is a Trailer issue or something that may be breaking further upstream. The best way to get this info is to (temporarily) enable the option "Dump API Responses to the console" from the "Misc" section in Preferences. Then go to Preferences -> Repositories -> Advanced and select "Re-scan now". This will make the required API calls to refresh your watchlist.

The setting you just enabled will basically dump every API call that Trailer makes to your system log (so in general this should always be off for security reasons!!) but in this case we're interested in the response that Trailer gets from calling `/user/subscriptions` The response for this may be broken into several pages, depending on how large your personal watchlist is.

From this response, you can see if the GitHub API is returning the repositories that you expected to see and aren't seeing.

If you can't see your repos there, GitHub is probably not sending them, as you suspected.

If you CAN see your repos there, Trailer may be ignoring them because of permission issues. The way to tell is relatively easy. The repo entry will contain a hash called "permissions". This hash contains various boolean fields. Trailer checks for "pull", "push" and "admin". One of the three needs to be set to "true" or else Trailer assumes the repo is inaccessible and ignores it.

It _may_ of course be the case that Trailer may be out of date in it's interpretation of these permissions, and you may be getting another set of permissions there altogether. So if you get another set of permissions there, it would be very helpful for me to see what you get (redacting any confidential info, of course, and only just the "permissions" hash would be fine)

Have a go and let me know how it goes, let's see if we can get to the bottom of this!

**Comment by olets** [comment]
So actually now I'm getting some other more significant problem. After submitting this, I had the idea that maybe my access token didn't have enough permissions. I created a new access token, added that to Trailer, it tested fine, but didn't fix the problem. I deleted the old access token… and my watched repos disappeared from Trailer. 😮 

Tried generating new tokens, editing the permissions of tokens, and still no repos. Eventually had to completely remove the app… and when I started fresh the missing repos showed up! Nice for the immediate use, but a bummer that we'll have to wait who knows how long for the bug(?) to show up again.

Fwiw, the dump when nothing was coming through looked like 

```
default	(TIME)	Trailer	UNIX error exception: 17
default	(TIME)	Trailer	FIRSTHASH opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	(TIME)	Trailer	FIRSTHASH closed /private/var/db/mds/system/mdsDirectory.db
default	(TIME)	Trailer	UNIX error exception: 17
default	(TIME)	Trailer	SECONDHASH opened /Users/USER/Library/Keychains/login.keychain-db: 352772 bytes
default	(TIME)	Trailer	SECONDHASH closed /Users/USER/Library/Keychains/login.keychain-db
default	(TIME)	Trailer	loading /Users/USER/Library/Keychains/login.keychain-db
default	(TIME)	Trailer	THIRDHASH opened /Library/Keychains/System.keychain: 42416 bytes
default	(TIME)	Trailer	THIRDHASH closed /Library/Keychains/System.keychain
default	(TIME)	Trailer	loading /Library/Keychains/System.keychain
default	(TIME)	Trailer	TIC TCP Conn Start [43:FOURTHHASH]
default	(TIME)	Trailer	TIC TCP Conn Event [43:FOURTHHASH]: 1 Err(0)
default	(TIME)	Trailer	TIC TCP Conn Connected [43:FOURTHHASH]: Err(0)
default	(TIME)	Trailer	TIC Enabling TLS [43:FOURTHHASH]
default	(TIME)	Trailer	TIC TLS Event [43:FOURTHHASH]: 2, Pending(0)
default	(TIME)	Trailer	TIC TLS Event [43:FOURTHHASH]: 20, Pending(0)
default	(TIME)	Trailer	TIC TCP Conn Event [43:FOURTHHASH]: 8 Err(0)
default	(TIME)	Trailer	TIC TLS Handshake Complete [43:FOURTHHASH]
default	(TIME)	Trailer	TIC TCP Conn Event [43:FOURTHHASH]: 2 Err(0)
default	(TIME)	Trailer	TIC TCP Conn Cancel [43:FOURTHHASH]
default	(TIME)	Trailer	TIC TCP Conn Destroyed [43:FOURTHHASH]
default	(TIME)	Trailer	UNIX error exception: 17
default	(TIME)	Trailer	FIFTHHASH opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	(TIME)	Trailer	FIFTHHASH closed /private/var/db/mds/system/mdsDirectory.db
default	(TIME)	Trailer	UNIX error exception: 17
default	(TIME)	Trailer	SIXTHHASH opened /Users/USER/Library/Keychains/login.keychain-db: 352772 bytes
default	(TIME)	Trailer	SIXTHHASH closed /Users/USER/Library/Keychains/login.keychain-db
default	(TIME)	Trailer	loading /Users/USER/Library/Keychains/login.keychain-db
default	(TIME)	Trailer	SEVENTHHASH opened /Library/Keychains/System.keychain: 42416 bytes
default	(TIME)	Trailer	SEVENTHHASH closed /Library/Keychains/System.keychain
default	(TIME)	Trailer	loading /Library/Keychains/System.keychain
default	(TIME)	Trailer	TIC TCP Conn Start [44:EIGHTHHASH]
default	(TIME)	Trailer	TIC TCP Conn Event [44:EIGHTHHASH]: 1 Err(0)
default	(TIME)	Trailer	TIC TCP Conn Connected [44:EIGHTHHASH]: Err(0)
default	(TIME)	Trailer	TIC Enabling TLS [44:EIGHTHHASH]
default	(TIME)	Trailer	TIC TLS Event [44:EIGHTHHASH]: 2, Pending(0)
default	(TIME)	Trailer	TIC TLS Event [44:EIGHTHHASH]: 20, Pending(0)
default	(TIME)	Trailer	TIC TCP Conn Event [44:EIGHTHHASH]: 8 Err(0)
default	(TIME)	Trailer	TIC TLS Handshake Complete [44:EIGHTHHASH]
default	(TIME)	Trailer	TIC TCP Conn Start [45:NINTHHASH]
default	(TIME)	Trailer	TIC TCP Conn Event [45:NINTHHASH]: 1 Err(0)
default	(TIME)	Trailer	TIC TCP Conn Connected [45:NINTHHASH]: Err(0)
default	(TIME)	Trailer	TIC Enabling TLS [45:NINTHHASH]
default	(TIME)	Trailer	TIC TLS Event [45:NINTHHASH]: 2, Pending(0)
default	(TIME)	Trailer	TIC TLS Event [45:NINTHHASH]: 20, Pending(0)
default	(TIME)	Trailer	TIC TCP Conn Event [45:NINTHHASH]: 8 Err(0)
default	(TIME)	Trailer	TIC TLS Handshake Complete [45:NINTHHASH]
default	(TIME)	Trailer	TIC TCP Conn Event [45:NINTHHASH]: 2 Err(0)
default	(TIME)	Trailer	TIC TCP Conn Cancel [45:NINTHHASH]
default	(TIME)	Trailer	TIC TCP Conn Destroyed [45:NINTHHASH]
default	(TIME)	Trailer	TIC TCP Conn Event [44:EIGHTHHASH]: 2 Err(0)
default	(TIME)	Trailer	TIC TCP Conn Cancel [44:EIGHTHHASH]
default	(TIME)	Trailer	TIC TCP Conn Destroyed [44:EIGHTHHASH]
```

**Comment by ptsochantaris** [comment]
Hi @olets - interesting, so from what I understand you create new tokens and deleted the previous tokens. Did you replace your old token with the new in Trailer? After doing that, did you let Trailer do a sync? Your log doesn't seem to contain any API response info (which is OK, if you are now seeing everything properly, it's best to keep that logging off :))

When you say complete remove, did that include the DB in ~/Library/Application Support/com.housetrip.Trailer?

**Comment by olets** [comment]
Funny you mention that: logging actually _is_ off (and I've never turned it on). Was going to make a new ticket for that.

If you expected additional API info in there, maybe my Misc preferences are stuck on "YES log, NO dump"?

Yes, I replaced the tokens. I deleted:

- `~/Library/Application Support/com.housetrip.Trailer`
- `~/Library/Caches/com.housetrip.Trailer`
- `~/Library/Group Containers/group.Trailer`
- `/private/var/folders/xn/.../C/com.housetrip.Trailer`
- `~/Library/Preferences/com.housetrip.Trailer.plist`

and the app. (Missed the `/private` file the first couple times, and kept wondering why I wasn't starting with a blank slate.)

Shortly after my last comment, Trailer's refreshes stopped doing anything. It says it's refreshed, but it doesn't. Haven't tried deleting it this time around, in hopes that keeping this problem alive will give us a chance to solve it.

Btw this is an awesome tool, my favorite of the many github-watcher desktop apps I've tried!

**Comment by ptsochantaris** [comment]
I'm glad you find Trailer useful! Let's see if we can't solve the issues you're having.

The uninstall you did sounds pretty thorough :) 👍 

If you turn on logging, you will get some good feedback on what's going on with the sync. What are you expecting to see after the sync and aren't seeing?

**Comment by olets** [comment]
In short I'm not seeing any of the newly added issues or PRs, or repos I've been added to.

With logging on, a re-scan shows a lot of stuff that looks like ^ but then also

```
default	13:31:07.395321 -0500	Trailer	(GitHub) GET https://api.github.com/user - NO CHANGE (304): 200
...
default	13:31:07.539491 -0500	Trailer	(GitHub) GET https://api.github.com/user/subscriptions - NO CHANGE (304): 200
default	13:31:07.582553 -0500	Trailer	(GitHub) GET https://api.github.com/user/teams - NO CHANGE (304): 200
default	13:31:07.583970 -0500	Trailer	Updating Team: xxxx
default	13:31:07.584421 -0500	Trailer	Updating Team: xxxxxxx
default	13:31:07.588930 -0500	Trailer	Nuked total 0 items marked for deletion
default	13:31:07.590822 -0500	Trailer	Saving DB
default	13:31:07.615832 -0500	Trailer	Saving DB
default	13:31:07.647799 -0500	Trailer	Refresh done
default	13:31:07.654847 -0500	Trailer	Updating PullRequest menu, 3 total items
default	13:31:07.655205 -0500	Trailer	Updating PullRequest status item
default	13:31:07.679369 -0500	Trailer	Updating Issue menu, 1 total items
default	13:31:07.679603 -0500	Trailer	Updating Issue status item
default	13:31:07.693772 -0500	Trailer	Updating PullRequest menu, 2 total items
default	13:31:07.694066 -0500	Trailer	Updating PullRequest status item
default	13:31:07.784258 -0500	Trailer	Updating Issue menu, 6 total items
default	13:31:07.784524 -0500	Trailer	Updating Issue status item
...
default	13:34:07.158623 -0500	Trailer	subsystem: com.apple.AppKit, category: Layout, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 0, enable_private_data: 0
error	13:34:07.158726 -0500	Trailer	Detected missing constraints for <private>.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.
```

Note that while there may not have been any changes since Trailer's last check, there _are_  subscription changes that aren't reflected in Trailer's repo list, and the Issues list is out of date.

**Comment by ptsochantaris** [comment]
Hi @olets - the best way to verify that Trailer is hearing about these new repos are to enable API logging and see what's coming down from the subscription endpoint. Are those repos listed there, and is does your current user token have permission to access them?

**Comment by olets** [comment]
In both of the above examples I've turned on API logging and run a "re-scan." Just tried again, and there was definitely no new Console activity associated with re-scanning

It isn't just new repos, it's also a question of updating the repos it grabbed. When I started fresh with this latest key, Trailer found all my watched repos as well as my assigned issues in some but not all of them… but it was a sadly a one-time deal: Trailer hasn't picked up on any subsequent activity in the repos it lists under "Repositories".

**Comment by ptsochantaris** [comment]
Hi @olets - from the looks of the log above, something is going wrong in your DB. Trailer is basically not syncing at all, as if the servers configured are not registered. After getting your user details it should have hit the two event endpoints to see what's new and sync it down. It's not doing any of that, so something has broken. The pattern suggests that it's not seeing the configured server in the DB for whatever crazy reason. My recommendation is to keep the logging on, just in case. Select and cut your token out of the existing server Personal Access Token field, and re-paste it. That will basically nuke all the info from the server, so when you close preferences, everything will sync back down. (you may want to tailor your repo preferences again before closing the preferences window first) Give that a try and let me know how it goes. Keep an eye on the sync log, see if Trailer keeps checking the /*events endpoints.

**Comment by olets** [comment]
For whatever reason, it's been working. Maybe I just needed to restart :man_shrugging:

**Comment by ptsochantaris** [comment]
Hi @olets, I'm going to close this issue for now. If you encounter this issue again or have any other problem, feel free to open more issues!
