### ISSUE TITLE
"misc" preferences seem to be stuck

### ISSUE THREAD

**Issue by olets** [ptsochantaris/trailer#312]
This came up in #311. Figured I'd make a separate ticket in case it's happening for anyone else:

My "Misc" preferences look like this

![trailer misc preferences](https://cloud.githubusercontent.com/assets/3282350/23807725/b53d73b2-0594-11e7-9ddc-b58bad7ea14a.png)

but they're acting like they're stuck at

    ☑️  log activity to the console
    ⬜️  dump api responses

- In the Console I'm seeing all Trailer activity logged.
- When I turn on "dump api responses to the console" and do a `preferences > repositories > advanced > re-scan now` I still only see normal activity in the Console.

**Comment by ptsochantaris** [comment]
Ah, interesting. Thanks for creating a separate issue for this! I'll take a look at it ASAP.

**Comment by olets** [comment]
Of course as soon as I wrote it up it turned out I'm wrong: turning on "log activity" does make a difference. This can probably be closed, sorry about that

**Comment by ptsochantaris** [comment]
No problem at all! Better safe than sorry 👍
