### ISSUE TITLE
Avatars not loading

### ISSUE THREAD

**Issue by oligriffiths** [ptsochantaris/trailer#313]
![image](https://cloud.githubusercontent.com/assets/1246671/23814063/d33a8da8-05af-11e7-92f9-5440af0b2f81.png)

The spinner appears whilst it's trying to load, but then it doesn't load.

**Comment by ptsochantaris** [comment]
Hi @oligriffiths and thanks for calling this in - Things to check out:

- Just in case Trailer's caching went funny, can you try quitting Trailer, nuking `~/Library/Application Support/com.housetrip.Trailer`, and re-starting it? This will cause Trailer to re-fetch the images next time it runs.

- Are these avatars publicly accessible? It's a bit complex to track it down, but if you enable `Dump API responses to the console` from the `Misc` section in Preferences, you will get a (very) long log in your Console.app log of what the server is telling Trailer. If you look for an issue or PR (the URL will look something like `https://server/api/pulls/[number]`) inside that dump you will have a hash called `"user"` and inside that `"avatar_url"`. Can you load one of those URLs in your browser and see if you can access it publicly?

Let me know how this goes.

**Comment by oligriffiths** [comment]
Cool, I'll try that. 

It's a GitHub enterprise api by the way, not sure if that makes a difference. Not sure if those avatars need authentication to fetch them. Will try turning on logging and see what it spits out.

**Comment by ptsochantaris** [comment]
Ah - there may be a chance that the avatars may not be publicly accessible then... IIRC there was a similar issue (quite) a while ago with a user who couldn't see avatars on GE. I don't unfortunately have a local GE server to test things on, so tracking that was a bit hard :(

It _may_ be that avatars won't show on GE in general due to some weirdness in authentication that isn't congruent with how the API does authentication, but if you have any ideas or suggestions on how to add some extra authentication, or anything that would help make those avatars visible in Trailer, I'd definitely be more than happy to see if it can be added to the app!

**Comment by oligriffiths** [comment]
So, the URL that GHE uses for avatars (on the website) is `https://github.tumblr.net/avatars/u/[user-id]?s=[width]` and it requires authentication if i hit that in the browser. I assume because GHE is organization based and they're not public.

**Comment by oligriffiths** [comment]
I'm also seeing a huge number of 
```
default	10:30:03.635359 -0400	Trailer	not switching as we're not in ~/Library/Keychains/: /Library/Keychains/System.keychain (0)
default	10:30:03.635587 -0400	Trailer	switching to keychain-db: /Users/oli/Library/Keychains/login.keychain-db from /Users/oli/Library/Keychains/login.keychain (0 1 1 1)
```
in the console

**Comment by ptsochantaris** [comment]
Ah, ok, so the image provider needs auth. You know, that's not an entirely bad thing - perhaps we can add authentication for fetching images in options - perhaps an advanced tab in the server config or so. Question is, do you know what kind of auth is required there? Basic HTTP auth with username and password perhaps? If you can point me to some docs, perhaps we can make this work - it's a shame that GE users can't see avatars right now.

PS Don't worry about that keychain message. It seems to be an OS thing, possibly related to sandboxing - Trailer never touches the keychain.

**Comment by oligriffiths** [comment]
So that browser URL will be using cookies, I'll see if I can find some docs for authenticating via the API, it probably needs to token to be passed in somehow.

**Comment by oligriffiths** [comment]
So, the URL that's returned from the API is `https://github.[internal-host]/avatars/u/[user-id]` and this requires authentication, however I can't seem to find any documentation on this.

**Comment by ptsochantaris** [comment]
Cool - anything you can find out will certainly be useful, but there's no hurry. If there is ANY way we can create the needed cookie from our end, that would do :)

**Comment by ptsochantaris** [comment]
Hi, just wanted to give you a heads-up that I'll be closing this issue for now to try and keep the issue list "contained" :) But if you do find out any more info about this, please feel free to open new issues or submit PRs that may help with viewing avatars in GE servers, they would be very welcome.
