### ISSUE TITLE
Idea: Warn on outdated base branches

### ISSUE THREAD

**Issue by rossgardt** [ptsochantaris/trailer#315]
**Description**
Everyone experienced it: Epic pull requests that cannot be merged without several user stories being finished. A reminder that my base branch is outdated would be super helpful.

**Proposal**
Introduce an indicator that shows on how much commits my working branch is behind the original base branch.
<img width="168" alt="screen shot 2017-03-15 at 11 06 36" src="https://cloud.githubusercontent.com/assets/234840/23943421/b973021a-096f-11e7-9b21-0c6c0c6df360.png">

I am thinking of an analogue view just as on github:
<img width="149" alt="screen shot 2017-03-15 at 11 09 50" src="https://cloud.githubusercontent.com/assets/234840/23943483/eee41d3a-096f-11e7-99f2-140f297c805b.png">

Best,
Benji

**Comment by ptsochantaris** [comment]
Hi @rossgardt and thanks for the suggestion. Sorry for taking so long to respond.

I'm not sure if this information is available over the API -do you by any chance know where we could pick up this number?- but I like the idea, it's certainly simple enough to implement as an option if the info is there.

**Comment by rossgardt** [comment]
[It seems](http://stackoverflow.com/a/2970101/90432) that one needs to execute git commands locally. Not sure if the effort is worth it?

I am not sure if this is easy to implement into the existing application? There will probably be the need to [make use of the git library](https://github.com/SwiftGit2/SwiftGit2).

**Comment by ptsochantaris** [comment]
To be totally frank I'd be quite reserved about running local system commands or getting involved with git authentication, etc.

Trailer right now depends solely on the GitHub API to get its info, and that in itself is quite a bit of work to maintain and expand over time, as well as having configurations options for it, etc. I'm worried that if I introduced a second source of configuration, calls, etc. it would just either be unmaintainable or a hack so simple that it could not be expanded in the future.

Sorry to sound a bit negative about this, but if it's not coming directly from the GH API I would be quite wary about adding it in as a core feature, as it would literally be a second thing to maintain and expand.

Having said that, always very happy to look at PRs though :)

**Comment by rossgardt** [comment]
That's totally fine. It was just an idea 😉  Maybe there will be such information available through the REST API in the future.

Regard this idea as archived so far 🙂  Thanks you for your time!

**Comment by ptsochantaris** [comment]
No worries, it's great to get suggestions, always - and the feature you're suggesting _would_ be useful. It's just the availability of data over the API that's the issue. If you do spot anything API-related which can lead to this being implemented or have any more thoughts on this, feel free to re-open!

**Comment by rossgardt** [comment]
I will keep it in my mind!
