### ISSUE TITLE
How to use group function ?

### ISSUE THREAD

**Issue by Samemura** [ptsochantaris/trailer#316]
This app helps a lot me, thanks.
I got some repositories, so would display repositories by groups.

I changed preferences but then nothing showed.
Repositories: put group name to repository

Can someone help me, please ?

**Comment by ptsochantaris** [comment]
Hi @Samemura - If you just add a group name to a repository (or more than one) then any items from them will show on their own menubar item, titled with that name group name. If those repos don't have items of course then there won't be a menu item for them until some items exist.

**Comment by Samemura** [comment]
@ptsochantaris thanks for help !
Now I found new menu bar icon for the groups, thank you.

By the way, is group function only shown on different menu bar icon ?
Originally I guessed it will be grouped on same menu bar icon. It is easier to see for me.

**Comment by ptsochantaris** [comment]
No problem, I know it's not the most self-explanatory feature :) - I'm glad it worked out for you!

Groups are currently only separated by menu-bar icons, yes, since groupings inside each menu are reserved for the relationship of each item (mine, participated, etc) and sub-grouping would probably not make this very readable, but I'm always open to suggestions.

**Comment by Samemura** [comment]
@ptsochantaris  , thank you so much !

Yes, your understanding is just my thinking. (like 'Mine', 'Participated') And also I know your concern.
To me, relationship grouping may be less important than specified grouping. So how about switching either of those by preferences?
E.g. Set specified grouping by preferences.
Items will be separated by specified groups. To recognize relation (mine, participated), author avatar is enough to me. (Generally, items shall be kept small numbers to be simple by filtering / closing items, so won't be big problem hopefully.)

**Comment by ptsochantaris** [comment]
Hi @Samemura - sorry for the almost half-year delay in answering, it's been an interesting/busy summer.

I understand where you're coming from, and eventually Trailer may support this by making grouping a more generic concept, but then this would need to be a larger feature than simply grouping items internally in one drop-down menu. 

However, currently the section groupings are very much an integral part of how Trailer works and presents its info, a part of its "personality" if you will - it would be quite hard to simply turn these in-built concepts and abstract them so they can then become part of a more arbitrary grouping feature.

I'm not saying this is a bad idea at all BTW, but it's something that may not show up in Trailer in the immediate future. Long term though, it's definitely a good idea to keep in mind as the interface evolves, and I will definitely do that.

**Comment by Samemura** [comment]
Hi @ptsochantaris , thank you for reply. I appreciate your kindly answer and also of course agree with you. Hope develop fine for trailer future!
