### ISSUE TITLE
Display number of lines of code added

### ISSUE THREAD

**Issue by rsaunders100** [ptsochantaris/trailer#317]
![screen shot 2017-03-27 at 16 16 48](https://cloud.githubusercontent.com/assets/555546/24363888/0eaf3bd4-1309-11e7-9f26-5c4a70f5ef33.png)

Will be useful to see at a glance roughly how big the pull request is so I can decide if I have time to review it quickly now or if I have to reserve some time later.

**Comment by ptsochantaris** [comment]
This definitely makes sense. I'm not entirely sure if the API provides the info we may be looking for here, although I think there is a high probability that it does, and it's definitely worth investigating. Stay tuned :)

**Comment by ptsochantaris** [comment]
Note to self: It feels like an option to sort PRs by number of lines changed would also be a good accompanying tweak to this feature. Only catch is that it applies only to PRs so it would need to be part of the option group to enable displaying this info, and not part from the main sorting menu.

**Comment by ptsochantaris** [comment]
Just a followup note - I had a look at the GitHub API and this indeed seems very straightforward - the data literally is in the base PR info that the API gives out. Will aim to have this in the next release.

**Comment by ptsochantaris** [comment]
Slightly discouraging news on this, unfortunately.

After actually implementing it, I realised that the data isn't actually being sent by GitHub, despite the impression the docs give.

Their documentation isn't *strictly* wrong: They DO provide this info if you request PRs one-by-one, but this info is not included in the records that are part of the list of PRs that is provided by the repos (which is almost identical in most other ways)

Querying PRs one-by-one would basically murder your API usage limit, so I'm not sure if that's the right way to go. I will give GitHub a shout to see if there's any chance of including the additions/deletions/files_changed (and incidentally "mergeable") attributes in the list calls too, but I won't be holding my breath :)

Sorry about this, wish I had better news. Will keep you updated when I get a reply.

**Comment by ptsochantaris** [comment]
Hi and happy 2020!

It's always bothered me that this feature wasn't part of Trailer because it's do damn useful. I've finally taken a deep breath and added v4 API syncing to Trailer, which now makes this feature possible. There is a beta here: https://github.com/ptsochantaris/trailer/pull/400 which now has this option, and you are very welcome to try it out and report any problems that you may encounter.

**Comment by rsaunders100** [comment]
Happy 2020!
Hope you are doing well.  Very excited about this, Ill give it a go :)
