### ISSUE TITLE
Snoozed items unsnooze occasionally

### ISSUE THREAD

**Issue by dangitall** [ptsochantaris/trailer#318]
I'm currently using v1.5.5 (1406).

I keep a lot of items snoozed 'Until manual wake'. Every once in a while (I'm guessing on the order of every 2 months) many of my snoozed items wake up with no input from me. In this most recent incident, I had 11 issues and 48 PRs snoozed and 10 and 46 respectively of them woke up. Oddly, it was only Trailer issues and PRs that remained snoozed.

I don't think I did anything to trigger this. It happened when I first sat down at my computer this morning, so the computer was coming out of sleep, but I don't know of any system events that occurred that could have caused this sort of thing.

Is there anything I can do to help provide more information about this?

**Comment by dangitall** [comment]
To my surprise, it just happened again. And the same Trailer issues/PRs remained snoozed.

**Comment by ptsochantaris** [comment]
Hi @dangitall - thanks for calling this in. Will look into this asap.

I realise that you have set the item to snooze "no matter what" (i.e. the checkboxes for that setting in "wake up immediately on..." are all off) but, on the premise that Trailer is somehow ignoring that, do you think there were events in the items themselves, like comments, updates, etc. which would have woken the item up had you kept those checkboxes ticked?

(i.e. I'm thinking that Trailer may be mis-applying the rules in the "wake up immediately on..." box)

**Comment by dangitall** [comment]
It seems unlikely since these are are across 5 or 6 different projects in a mix of public and private organizations.

**Comment by dangitall** [comment]
I really don't know what happened here. I saw this behavior three times in two days and nothing since.

**Comment by ptsochantaris** [comment]
Well, that's good news at least. I'm not sure what was happening there, unless the wakeup dates that were recorded for those entries were wrong somehow, perhaps some bug with the version you had used to snooze them originally (it wouldn't shock me, there were a couple of rough edges with the snooze feature initially)

However, I'm still planning on investigating this a bit further to see what could have made it happen - I haven't had much of a chance while working on the 1.5.6 release and the beta features (it's been bumpy :)) as well as having had to deal with quite a bit of work, but still, I just wanted to let you know I haven't forgotten about this issue - sorry I haven't updated you for a while though, even if it's just with a "please hold" :)

**Comment by dangitall** [comment]
FWIW, I haven't seen this issue in a long time. It's probably safe to close if you're so inclined!

**Comment by ptsochantaris** [comment]
Hi @dangitall - that's great to hear, and thanks for keeping me updated! I'll close this for now, then, and feel free to open further issues if you encounter any more problems related to this or anything else.
