### ISSUE TITLE
Initial import and syncing isn't working

### ISSUE THREAD

**Issue by mattaningram** [ptsochantaris/trailer#321]
Set this up on my MacBook a couple of weeks ago and it worked great, even with a lot of watched repos and other things to track.

Got a new MacBook Pro and decided to set it up again (even made a new auth token with appropriate permissions), and the initial sync never finished. I closed the app and started it up again and no data to be found anywhere. If I go to "Advanced Repository Settings" the "Re-scan now" button is disabled and has a spinner going next to it without any sign of progress after a long time waiting.

What am I doing wrong?

**Comment by mattaningram** [comment]
Issue somehow resolved itself after a couple of days. Syncing is working properly now.

**Comment by ptsochantaris** [comment]
Hi, I'm glad the issue was resolved, and sorry for the very late response here.

I've been wondering if your issue was related to your API quota running out, which is definitely possible if you have many repositories watched. Currently Trailer is not too good about reporting that - I've been meaning to improve the "on-boarding" experience with a repo selector, so a user can pick which repositories they want to view initially, instead of subscribing to all of them.

At the very least, it ought to signal that the limit was reached so a user knows to try again in an hour or so.

Still, glad to see things are up and running again. Please re-open if you have more problems like this, and hopefully soon the first sync situation will improve quite a bit.

**Comment by alexjhannan** [comment]
I think I'm running into this issue now. Just getting started, and I'm on an endless sync with no end in sight. What's the surest path to getting synced up?

**Comment by ptsochantaris** [comment]
Hi @alexjhannan and thanks for reaching out. Can you give me a few more details on what you mean y endless sync? How does the interface display the sync? Does the operation count stay frozen at a certain number for instance?

**Comment by alexjhannan** [comment]
Thanks for responding! Unfortunately I don't have much context to offer. This is all I see, after having entered a token with the appropriate permissions:

<img width="492" alt="screen shot 2017-08-16 at 7 08 47 pm" src="https://user-images.githubusercontent.com/13947899/29389105-5b05348a-82b6-11e7-81bd-4aabc21cc4c6.png">

It's been like this all day, so I expect that it's endless.

**Comment by ptsochantaris** [comment]
Yes, it's safe to say that if you're not seeing any kind of activity for a long time then it's basically stuck. 

Normally after a few calls, the sync display will start showing you a count of the operations that it is doing (this number can go up while it is running, so it's not really a countdown, but it indicates activity). If you're not seeing this number then something is definitely going wrong with the API calls that are being made at an early stage.

This, in a way, is a good thing because it means we can try catching it early.

My feeling is that GitHub may have made API token permission changes recently, as I have had similar problems reported to me personally as well, so I am looking into it, but in the meantime can you try generating a token with all permissions on and see if that improves the situation at all?

Additionally, you can get more info about what the initial sync is doing if you open the preferences window, go to "Misc" and turn on "Log activity to console" so you can see what calls are being made and/or failing from Console.app.

Can you give those two things a try and let me know how it goes? I'll also make a note to locally try and create a new token with the permissions which Trailer recommends and see if the default sync will actually run or if more permissions may in fact be needed (also, why Trailer isn't visibly failing if this is in fact the problem)

In the worst case, we can try manually setting up your token instead of using the quick-start view (you can just close it and visit preferences, enter your token into a new server entry, then visit the repos list and set things up like that if you prefer. Then Trailer will run a first sync when you close preferences.)

Thanks for bearing with me, let's see if we can sort it out.

**Comment by alexjhannan** [comment]
Hmmmm, no luck with any of these approaches. I've tried giving the token full permissions to no avail.

I started logging activity to console to see if anything would show up, but I'm not getting much usable info, other than _that_ an error occurred. For instance:

`TIC TCP Conn Event [5:0x61000019cf20]: 1 Err(0)`

**Comment by ptsochantaris** [comment]
Hi again and sorry for the slow responses, it's been a busy week.

Ok, so something else must be happening than your token or Trailer not syncing properly. If you're not getting any messages it probably means that no connections are being made at all to your server, so this means that (most likely) Trailer got itself into some sort of knot database-wise or there is some proxy or network issue on your end.

Let's try resetting Trailer completely, by ensuring that it is not running, then deleting the data directory in `~/Library/Application Support/com.housetrip.Trailer` and running Trailer again. Try the quickstart again and see if things have improved at all. Perhaps turn logging to on before doing that so you can keep an eye on Console.app and see if connections are being made.

Let me know how it goes!

**Comment by alexjhannan** [comment]
Hey, no worries about the slow responses. Thanks for working on this! I've heard great things from co-workers, so I'm happy to help.

I deleted the data directory and started from scratch with a full-permission token. Here's the plaintext of the log in Console.app:
(Hopefully this gives you some useful info)
```
fault	14:45:53.248304 -0400	cfprefsd	attempt to write to a container /var/root/Library/Group Containers/group.Trailer that does not yet exist. Using client-provided container path without resolving symlinks.
error	14:45:53.248452 -0400	Trailer	Failed to read values in CFPrefsPlistSource<0x6000000e9700> (Domain: group.Trailer, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null)): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
default	14:45:53.250121 -0400	Trailer	Files in file:///Users/alexjhannan/Library/Application%20Support/com.housetrip.Trailer
default	14:45:53.267398 -0400	Trailer	Database setup complete
default	14:45:53.270978 -0400	Trailer	Reachability monitoring active
default	14:45:53.271057 -0400	Trailer	Network is Local
default	14:45:53.304508 -0400	Trailer	Updating PullRequest menu, 0 total items
default	14:45:53.314017 -0400	Trailer	Updating PullRequest status item
default	14:45:53.340958 -0400	Trailer	Setting NEW_ISSUE_DISPLAY_POLICY_INDEX to identical value (3), skipping
default	14:45:53.369599 -0400	Trailer	Check for updates set to true, every 28800.0 seconds
default	14:45:53.400261 -0400	Trailer	Faulting in NSHTTPCookieStorage singleton
default	14:45:53.400284 -0400	Trailer	Faulting in CFHTTPCookieStorage singleton
default	14:45:53.400299 -0400	Trailer	Creating default cookie storage with process/bundle identifier
default	14:45:53.402320 -0400	Trailer	TIC TCP Conn Start [1:0x608000199f30]
default	14:45:53.428139 -0400	Trailer	TIC TCP Conn Event [1:0x608000199f30]: 1 Err(0)
default	14:45:53.428161 -0400	Trailer	TIC TCP Conn Connected [1:0x608000199f30]: Err(0)
default	14:46:07.255965 -0400	Trailer	0x600000274440 opened /var/folders/rn/s3bhk7p15pg9lzbh_pw2w65c0000gn/C//mds/mdsObject.db: 4404 bytes
default	14:46:07.256300 -0400	Trailer	0x600000274800 opened /var/folders/rn/s3bhk7p15pg9lzbh_pw2w65c0000gn/C//mds/mdsDirectory.db: 50540 bytes
default	14:46:07.257886 -0400	Trailer	0x61000027ab40 opened /var/folders/rn/s3bhk7p15pg9lzbh_pw2w65c0000gn/C//mds/mdsDirectory.db: 50540 bytes
default	14:46:07.259584 -0400	Trailer	0x610000277180 opened /Users/alexjhannan/Library/Keychains/login.keychain-db: 130796 bytes
default	14:46:07.263142 -0400	Trailer	0x608000264ec0 opened /Library/Keychains/System.keychain: 34748 bytes
default	14:46:07.267476 -0400	Trailer	TIC TCP Conn Start [2:0x60800019a9c0]
default	14:46:07.283695 -0400	Trailer	TIC TCP Conn Event [2:0x60800019a9c0]: 1 Err(0)
default	14:46:07.283722 -0400	Trailer	TIC TCP Conn Connected [2:0x60800019a9c0]: Err(0)
default	14:46:07.283869 -0400	Trailer	TIC Enabling TLS [2:0x60800019a9c0]
default	14:46:07.295204 -0400	Trailer	TIC TLS Event [2:0x60800019a9c0]: 2, Pending(0)
default	14:46:07.295704 -0400	Trailer	TIC TLS Event [2:0x60800019a9c0]: 11, Pending(0)
default	14:46:07.296558 -0400	Trailer	TIC TLS Event [2:0x60800019a9c0]: 12, Pending(0)
default	14:46:07.296596 -0400	Trailer	TIC TLS Event [2:0x60800019a9c0]: 14, Pending(0)
default	14:46:07.300802 -0400	Trailer	TIC TLS Trust Result [2:0x60800019a9c0]: 0
default	14:46:07.311842 -0400	Trailer	TIC TLS Event [2:0x60800019a9c0]: 20, Pending(0)
default	14:46:07.312180 -0400	Trailer	TIC TCP Conn Event [2:0x60800019a9c0]: 8 Err(0)
default	14:46:07.312197 -0400	Trailer	TIC TLS Handshake Complete [2:0x60800019a9c0]
default	14:46:07.416692 -0400	Trailer	(GitHub) GET https://api.github.com/user - RESULT: 200
default	14:46:07.417065 -0400	Trailer	API data from https://api.github.com/user: {"login":"alexjhannan","id":13947899,"avatar_url":"https://avatars3.githubusercontent.com/u/13947899?v=4","gravatar_id":"","url":"https://api.github.com/users/alexjhannan","html_url":"https://github.com/alexjhannan","followers_url":"https://api.github.com/users/alexjhannan/followers","following_url":"https://api.github.com/users/alexjhannan/following{/other_user}","gists_url":"https://api.github.com/users/alexjhannan/gists{/gist_id}","starred_url":"https://api.github.com/users/alexjhannan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alexjhannan/subscriptions","organizations_url":"https://api.github.com/users/alexjhannan/orgs","repos_url":"https://api.github.com/users/alexjhannan/repos","events_url":"https://api.github.com/users/alexjhannan/events{/privacy}","received_events_url":"https://api.github.com/users/alexjhannan/received_events","type":"User","site_admin":false,"name":"Alex Hannan","company":null,"blog":"alexhannan.com","<…>
default	14:46:07.417673 -0400	Trailer	Setting LAST_SUCCESSFUL_REFRESH to identical value (nil), skipping
default	14:46:07.417743 -0400	Trailer	Actively verifying reported network availability state…
default	14:46:07.417799 -0400	Trailer	No change to network state
default	14:46:07.419777 -0400	Trailer	Updating PullRequest menu, 0 total items
default	14:46:07.419967 -0400	Trailer	Updating PullRequest status item
default	14:46:07.423344 -0400	Trailer	Starting refresh
default	14:46:07.429240 -0400	Trailer	(GitHub) GET https://api.github.com/user - CACHED
default	14:46:07.536069 -0400	Trailer	API data from https://api.github.com/user: {"login":"alexjhannan","id":13947899,"avatar_url":"https://avatars3.githubusercontent.com/u/13947899?v=4","gravatar_id":"","url":"https://api.github.com/users/alexjhannan","html_url":"https://github.com/alexjhannan","followers_url":"https://api.github.com/users/alexjhannan/followers","following_url":"https://api.github.com/users/alexjhannan/following{/other_user}","gists_url":"https://api.github.com/users/alexjhannan/gists{/gist_id}","starred_url":"https://api.github.com/users/alexjhannan/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alexjhannan/subscriptions","organizations_url":"https://api.github.com/users/alexjhannan/orgs","repos_url":"https://api.github.com/users/alexjhannan/repos","events_url":"https://api.github.com/users/alexjhannan/events{/privacy}","received_events_url":"https://api.github.com/users/alexjhannan/received_events","type":"User","site_admin":false,"name":"Alex Hannan","company":null,"blog":"alexhannan.com","<…>
default	14:46:07.540391 -0400	Trailer	TIC TCP Conn Start [3:0x61800019f890]
default	14:46:07.549936 -0400	Trailer	TIC TCP Conn Event [3:0x61800019f890]: 1 Err(0)
default	14:46:07.549962 -0400	Trailer	TIC TCP Conn Connected [3:0x61800019f890]: Err(0)
default	14:46:07.550071 -0400	Trailer	TIC Enabling TLS [3:0x61800019f890]
default	14:46:07.562698 -0400	Trailer	TIC TLS Event [3:0x61800019f890]: 2, Pending(0)
default	14:46:07.562817 -0400	Trailer	TIC TLS Event [3:0x61800019f890]: 20, Pending(0)
default	14:46:07.563187 -0400	Trailer	TIC TCP Conn Event [3:0x61800019f890]: 8 Err(0)
default	14:46:07.563209 -0400	Trailer	TIC TLS Handshake Complete [3:0x61800019f890]
default	14:46:07.581462 -0400	Trailer	(GitHub) GET https://api.github.com/user/subscriptions?per_page=100 - RESULT: 200
default	14:46:07.581633 -0400	Trailer	API data from https://api.github.com/user/subscriptions?per_page=100: []
default	14:46:07.640115 -0400	Trailer	(GitHub) GET https://api.github.com/user/teams?per_page=100 - RESULT: 200
default	14:46:07.640678 -0400	Trailer	API data from https://api.github.com/user/teams?per_page=100: [{"name":"Codecademy","id":77292,"slug":"codecademy","description":null,"privacy":"secret","url":"https://api.github.com/teams/77292","members_url":"https://api.github.com/teams/77292/members{/member}","repositories_url":"https://api.github.com/teams/77292/repos","permission":"pull","created_at":"2007-10-20T11:24:19Z","updated_at":"2016-04-04T17:39:28Z","members_count":55,"repos_count":103,"organization":{"login":"RyzacInc","id":887145,"url":"https://api.github.com/orgs/RyzacInc","repos_url":"https://api.github.com/orgs/RyzacInc/repos","events_url":"https://api.github.com/orgs/RyzacInc/events","hooks_url":"https://api.github.com/orgs/RyzacInc/hooks","issues_url":"https://api.github.com/orgs/RyzacInc/issues","members_url":"https://api.github.com/orgs/RyzacInc/members{/member}","public_members_url":"https://api.github.com/orgs/RyzacInc/public_members{/member}","avatar_url":"https://avatars0.githubusercontent.com/u/887145?v=4","description":"<…>
default	14:46:07.641624 -0400	Trailer	Creating Team: 77292
default	14:46:07.645311 -0400	Trailer	Creating Team: 2125377
default	14:46:17.609686 -0400	Trailer	TIC TCP Conn Event [2:0x60800019a9c0]: 2 Err(0)
default	14:46:17.609750 -0400	Trailer	TIC TCP Conn Cancel [2:0x60800019a9c0]
default	14:46:17.609807 -0400	Trailer	TIC TCP Conn Destroyed [2:0x60800019a9c0]
default	14:46:17.649974 -0400	Trailer	TIC TCP Conn Event [3:0x61800019f890]: 2 Err(0)
default	14:46:17.650016 -0400	Trailer	TIC TCP Conn Cancel [3:0x61800019f890]
default	14:46:17.650064 -0400	Trailer	TIC TCP Conn Destroyed [3:0x61800019f890]
default	14:46:53.418173 -0400	Trailer	TIC TCP Conn Cancel [1:0x608000199f30]
default	14:52:40.706664 -0400	Trailer	System is going to sleep
default	15:46:23.238905 -0400	Trailer	System woke up
default	15:46:24.278028 -0400	Trailer	Won't start refresh because refresh is already ongoing
```

**Comment by ptsochantaris** [comment]
Ah, interesting, I think we have a good clue on what's going on at this line:
```
(GitHub) GET https://api.github.com/user/subscriptions?per_page=100 - RESULT: 200
API data from https://api.github.com/user/subscriptions?per_page=100: []
```

This snippet shows that Trailer is downloading your watchlist and you don't actually have any repositories in your watchlist, so the setup is _technically_ working fine - but there's just nothing to show (and Trailer seems to get confused)

It's worth noting that Trailer should NOT have just stayed frozen there, it should have told you that setup is done but you have no watched repositories to show, so this is definitely a bug in a sense. I'm making a note to fix this in the next release coming up.

In the meantime, assuming this is the problem, you can fix this by actually adding a few repositories on your watchlist. Try it and run through quickstart again, it _should_ complete fine after that. Let me know if we're getting closer to a solution :)

Note: Be sure to delete your DB again before trying again, to make sure Trailer isn't using locally cached data (as it _does_ cache things for a minute or so, and you may not see the changes you made immediately)

Also - you may want to edit and remove the logging data from your comment above, as it is showing some API responses from your account which, albeit not critical to security, are probably not a good idea to expose publicly, just to be on the safe side.

Let me know how it goes.

**Comment by alexjhannan** [comment]
Hah! It finished almost immediately after adding a repo to the watchlist. I hope my weird GitHub habits helped a bit with debugging things. 😁 

Redacted the log for safety. Thanks for your help through this, and thanks for building such a useful tool. Cheers!

**Comment by ptsochantaris** [comment]
Fantastic! I'm glad we tracked this down. You absolutely _did_ help in this case, I'll be sure to add some logic to catch out this corner case in future updates.

Enjoy Trailer, and I hope the rest is all smooth sailing!
