### ISSUE TITLE
Move PR to Participated if user approves/requests changes/comments on PR

### ISSUE THREAD

**Issue by JonathanTech** [ptsochantaris/trailer#322]
Currently it only goes into Participated if you leave a comment on a PR. I think there should be an option to move it to participated if you just approve it without any comment.

**Comment by ptsochantaris** [comment]
That makes sense, if you have reviewed a PR it should move to Participated, just like adding a comment would.

**Comment by ptsochantaris** [comment]
Hi, version 1.5.8 is now up and has this behaviour. Thanks a lot for suggesting it - like all great ideas it seems completely obvious in retrospect.

I'll close this issue for now but please do keep the suggestions coming in further issues! :)
