### ISSUE TITLE
Stuck in refreshing...

### ISSUE THREAD

**Issue by thejspr** [ptsochantaris/trailer#324]
Hi Paul!

I'm still enjoying Trailer since leaving HouseTrip in 2015. Nice work!

I keep encountering the app getting stuck in "Refreshing", both when running normally and after resuming from standby. Here is a dump from the log:

![image](https://cloud.githubusercontent.com/assets/293672/26760399/23eba91c-4917-11e7-9df3-3c5016707309.png)

Restarting the app fixes the issue most of the time, but not always.

Any idea whats wrong?

**Comment by ptsochantaris** [comment]
Hi @thejspr - good to hear from you! From the log it seems that refresh seems to have a problem resuming if it was interrupted in the middle by the machine going to sleep. I'll try to reproduce this locally and get back to you very soon.

**Comment by NiXXeD** [comment]
I seem to be running into a similar issue. However, I'm not able to restart the app to fix it. I even tried reinstalling it. Any suggestions for a workaround in the mean time?

**Comment by ptsochantaris** [comment]
Hi @thejspr and @NiXXeD 

I've been trying to reproduce the issue based on the assumption that the system going to sleep in the middle of a sync was to blame, but not much luck. It seems that network requests in transit at that time are restarted (or fail) properly after a moment, so bang goes that theory.

I've just put up an update which includes all the tweaks done to the API stack for the recent iOS update as well: https://github.com/ptsochantaris/trailer/releases/tag/1.5.9

This is not directly trying to solve this issue, but it does include tweaks to the way it handles network call processing and caching, and it may be that there were some hidden rare deadlock cases in the previous code which this one shouldn't have. Give it a try and let me know if this helps at all.

Sorry for not having more news about this ATM, but we'll keep picking at it and hopefully get to the bottom of it eventually!

**Comment by thejspr** [comment]
Thanks @ptsochantaris. I've updated and will report back if I keep getting the issue.

**Comment by ptsochantaris** [comment]
An interesting footnote to this issue - it seems that if for some reason Trailer could not get a list of repos from GitHub (e.g. in the sense of some security token permission change, not in a sense of a network connection failure) then it could end up spinning for infinity when syncing. I'm not sure how much this relates to your issues above, but something to keep in mind if you see this again - i.e. is the `subscriptions` API endpoint returning the right data to you?

(Also, this issue has been fixed in the latest branch and should be out with the latest update this coming week)

**Comment by ptsochantaris** [comment]
I'm going to close this for now, but please feel free to open a new issue if this problem re-occurs for you!

Also please note v1.6.0 is up now which should correct the issue mentioned above, which may have also been part of the issue you were experiencing.
