### ISSUE TITLE
Review statuses API no longer works with GitHub Enterprise 2.9

### ISSUE THREAD

**Issue by ScottDugas** [ptsochantaris/trailer#328]
This change: https://github.com/ptsochantaris/trailer/commit/a52432970ccb105776c96777b0ca6ebc65c5892e removed the header from requests to the reviews API, because it was removed from preview in GitHub proper, however it is still in preview mode for the current enterprise release ( [docs](https://developer.github.com/enterprise/2.9/v3/pulls/reviews/) ) resulting in failed requests when enabling reviews:
```
(Work GitHub) GET https://github.enterprise.com/api/v3/repos/team/project/pulls/11557/reviews?per_page=100 - FAILED: (code 415) Server responded with error 415
API data from https://github.enterprise.com/api/v3/repos/team/project/pulls/11557/reviews?per_page=100: {"message":"If you would like to help us test the Pull Request Reviews API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.","documentation_url":"https://developer.github.com/enterprise/2.9/v3"}
```

**Comment by ptsochantaris** [comment]
Hi @ScottDugas and thanks for bringing this to my attention. I'll post an update that re-enables the beta headers on GitHub Enterprise API requests very soon.

**Comment by ScottDugas** [comment]
This appears to be working now with 1.5.9
