### ISSUE TITLE
What about private repos in organizations?

### ISSUE THREAD

**Issue by pekhota** [ptsochantaris/trailer#329]
I can't generate token via "My Tokens". I used basic auth to get token. Then I received infinite loader. What I have to do to fix this problem?

**Comment by ptsochantaris** [comment]
Hi @pekhota - I'm not sure if I'm clear about what you mean by using basic auth to get a token. The token you create should be from https://github.com/settings/tokens - anything else probably won't work. Also, I'm not sure if your question is about accessing private repos or data not loading at all - can you give me more info on what you're encountering? BTW you can get more info on the calls being made to GitHub via the preferences panel. Turn "Log activity to the console" to get more info on the Console.app on what calls are being made and why initial sync may be taking a long time.

**Comment by pekhota** [comment]
ok, I'll do it later. Thanks
