### ISSUE TITLE
[MacOS version] Integration with Ship-2 ?

### ISSUE THREAD

**Issue by digiwano** [ptsochantaris/trailer#330]
I don't know how feasible this is and/or whether or not [Ship](https://www.realartists.com/index.html) can even accept some form of "open this issue/PR" command, but it would be really nice if I could use both Ship and Trailer together in such a way that when I click on an issue in Trailer's menubar app I get the issue/PR opened in Ship.

**Comment by digiwano** [comment]
After talking with their support, I've learned that Ship supports being opened via a github url, as in `open https://github.com/ptsochantaris/trailer/issues/330 -a /Applications/Ship.app` would open this issue with Ship, so it seems all that would be needed is to have Trailer have the browser it launches the github URL with be configurable?

**Comment by ptsochantaris** [comment]
Hi @digiwano and thanks for posting!

First off, Ship looks like a really cool app, I ought to try it out too. It sounds from your description that what we're looking for is an option to "Open clicked items in..." and then a dropdown of installed apps that can handle opening URLs. I don't know if macOS provides API to accomplish this, but given how it's done in apps like Transmit (when selecting a default FTP client, for instance) I'd bet it's doable. I'll investigate a bit and keep you posted.

In the meantime, from the description you got from Ship tech support, it may be that you can evoke this behaviour right now by dragging a Trailer item over the Ship app icon, it theoretically ought to have the same effect as the command you're quoting above.

**Comment by digiwano** [comment]
That *DOES* work, though it's a little tedious. Thanks for looking into this. Ship's actual official answer was to look into [choosy](https://www.choosyosx.com), but i'd really rather not have to install something that hijacks the opening of all links on my system just to get this functionality :) Luckily, i]I'm familiar enough with MacOS to know that means that it just needs to be opened with the default "open url with app" apis and that /usr/bin/open would work :)

I'm pretty sure the api calls you're looking for are under here somewhere: https://developer.apple.com/documentation/appkit/nsworkspace

The following worked for me, but i'm not sure if it's the "best" way, as that specific method was fairly [lacking](https://developer.apple.com/documentation/appkit/nsworkspace/1528548-open) in documentation:
```
🌀  swift
Welcome to Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42). Type :help for assistance.
  1> import Cocoa
  2> let locUrl = URL(string:"https://github.com/user/project/pull/99")!
  3> let appUrl = URL(string:"file:///Applications/Ship.app")!
  4> NSWorkspace.shared().open([locUrl], withApplicationAt:appUrl, options:[], configuration:[:])
```

**Comment by ptsochantaris** [comment]
Hi @digiwano, I'm glad the workaround works for you, at least temporarily.

I agree you shouldn't need extra utilities, however the code you're thinking about would be hardcoded to Ship.

I wouldn't like to add a feature to Trailer that hardcodes behaviour for a specific app, instead what I'd like to do is have a menu that offers to open URLs by default using the selected app, similar to how Transmit does it.

That does mean I need to have a look for how to do this :) - i.e. query the launch services registry for handlers to http(s) URLs. Very similar to how Transmit does it, or I suspect to how Choosy does it too:

<img width="348" alt="screen shot 2017-08-03 at 19 16 22" src="https://user-images.githubusercontent.com/521581/28936652-44ea1840-7880-11e7-8173-f89790970d8f.png">

**Comment by digiwano** [comment]
As far as I can tell and/or google,  that's in the Launch Services stuff .. this gist seems to have a nice example in `getInstalledBrowsers()` : https://gist.github.com/cho45/ac9443aaa66406408485

**Comment by ptsochantaris** [comment]
That's a good link! I wonder if this would also have Ship show up on that list too (i.e. I wonder if Ship registers as an http handler in that fashion - may have to install it and try that out)

**Comment by digiwano** [comment]
I don't think it would normally show up, when I was trying out Choosy, I had to manually add it to their list which did populate with some other browsers on my system (it's worth noting that they don't use that standard-looking control like transmit), but I suppose that's why even your Transmit screenshot has the 'select...' option at the bottom :)

**Comment by ptsochantaris** [comment]
Hi @digiwano,

It's been a while, but here's a work-in-progress build of Trailer with a version of this feature added. It's less glamorous than the selection menu I originally envisioned, but then again this feature would only be useful in its capacity as the "Select..." menu entry above (otherwise the default web browser would just make sense), so I thought I'd skip the menu altogether.

You can find two new entries in the "Misc" section: One for overriding the app in which to open item links, and the other for potentially overriding the browser to open other web links in (like CI links, repos, etc) Leaving either or both blank will fall back to the default system web browser.

Let me know how/if this works for you and if you have any comments or suggestions.

[trailer163-wip.zip](https://github.com/ptsochantaris/trailer/files/1346698/trailer163-wip.zip)

**Comment by ptsochantaris** [comment]
Hi, I'm going to close this issue for now. Feel free to open new issues with feedback and/or suggestions on this feature, or anything else!
