### ISSUE TITLE
It won't update labels on issues.

### ISSUE THREAD

**Issue by cperezabo** [ptsochantaris/trailer#331]
It just doesn't display labels for issues, just for PRs, I don't know what else to try, any help?

**Comment by ptsochantaris** [comment]
Hi @cperezabo - I wonder if this is some sort of sync hiccup. Something to try: Hide the repos containing the PRs whose labels you can’t see. Sync once, then un-hide those Repos so items sync down again. See if this helps at all.

**Comment by ptsochantaris** [comment]
Hi @cperezabo - was just wondering if you're still having this issue? Did any of the steps above improve things at all?

**Comment by cperezabo** [comment]
I stopped using Trailer :(

**Comment by ptsochantaris** [comment]
Cool, if you ever re-install it and run into a similar issue feel free to file another issue. Will close this for now.
