### ISSUE TITLE
Notification of new comment from myself

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#334]
As I review and comment on pull requests, I end up going back to Trailer after I have finished to find all the pull requests have a notification of a new comment, so I have to go back in to all of these pull requests just to find out that it was my comments and not someone else.  Is there a way to prevent new comment notifications if the comments are from yourself?

**Comment by ptsochantaris** [comment]
Hi @cgatesman 

Trailer should not be letting you know of comments that you posted.

Are you sure what you're seeing is a new comment notification? For instance, do you also get a desktop notification saying there was a new comment from yourself? I'm wondering if you're perhaps seeing is the "!" signifying that there was a new commit to a PR?

If that's the case, you can turn this off from `Preferences` -> `Comments` -> `Highlight PRs that have new commits`.

If that's not what you're seeing, make sure that the API token you are using to access GitHub is from the same account that you are seeing the comment notifications from - perhaps Trailer is thinking you're someone else? :)

Let me know how you get on, happy to help further if it's none of the above.

**Comment by cgatesman** [comment]
> I'm wondering if what you're perhaps seeing is the "!" signifying that there was a new commit to a PR?
>
> If that's the case, you can turn this off from Preferences -> Comments -> Highlight PRs that have new commits.

This is the feature I'm referring to.  I would like notification (the `!`) on PRs with new comments.  However, it is notifying me that there is a new comment when it's just me making the new comment.

**Comment by ptsochantaris** [comment]
Ah, ok - so, the `!` symbol doesn't mean there is a new comment, it means there's a new commit, which is what may be confusing you. You can turn that feature off from `Preferences -> Comments -> Highlight PRs that have new commits so it doesn't bother you`.

Comments are marked with a number, which shows how many new comments there are on each item, and your own comments won't get counted as part of that.

**Comment by cgatesman** [comment]
Ah.  I guess I misread the option since it was under the "Comments" section.  However, I do believe this was coming up when I made a comment on a PR with no new commits added.  I'll have to double check that.

**Comment by cgatesman** [comment]
Thanks.  I'll close this, and if I see any other problems around this now that you explained it to me, I'll just open a new Issue.

**Comment by ptsochantaris** [comment]
Great, let me know how it goes.

I can definitely see how you could have misread that option - I'm not sure it was the best idea to have this option under "Comments" to be honest.

It's very easy to misread "commit" as "comment" in that context as one's mind is already primed by the other word. I'll make a note to move this option to "Display" where it more properly belongs.
