### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by MichMich** [ptsochantaris/trailer#339]
When trying to update the application, I get the following error message:
<img width="532" alt="screen shot 2017-10-31 at 09 58 49" src="https://user-images.githubusercontent.com/210954/32215473-50a346a6-be22-11e7-9eb4-366666f8e54c.png">

The application is installed on the following location.

    /Applications/Trailer.app

The console shows nothing more than a similar error message

    default	10:02:09.509674 +0100	Trailer	Sparkle: Error: Trailer can’t be updated when it’s running from a read-only volume like a disk image or an optical drive. Move Trailer to your Applications folder, relaunch it from there, and try again. (null) (URL (null))

**Comment by ptsochantaris** [comment]
Hi @MichMich and thank you for reporting this.

I'm not sure what could be causing it. I haven't updated Sparkle recently on Trailer, so I don't think anything has broken there. And I do test app updates on my secondary machine to make sure they run smoothly after publishing an update, and it went fine.

Could this be a local system issue? Could your main drive be running some maintenance task? If you try to upgrade again after a while, do you get the same thing? I don't mean to worry you, but have you run a DiskUtility First Aid check recently?

I can only propose you grab the latest version from the releases page (or this link: https://github.com/ptsochantaris/trailer/releases/download/1.6.3/trailer163.zip )

I'm not sure how to advise you on fixing this any other way apart from suggesting you look at Console.app for any suspicious errors and/or messages around the time you select "update" in Trailer perhaps.

Let me know how things go with this or if I can help at all.

**Comment by MichMich** [comment]
I've updated the app manually as you described. I'll keep an eye on the issue. If it comes back, I'll let you know. Thanks for your help.

**Comment by MichMich** [comment]
@ptsochantaris I ran into a similar issue with an old version of google drive. It turned out the app wasn't compatible with the new AFS (APFS) in High Sierra. It might be possible that the trailer update problem is caused by the same issue. Did you test it on an High Sierra machine which uses the new APFS?
