### ISSUE TITLE
Missing Required Github Review not being displayed in PR CI/statuses

### ISSUE THREAD

**Issue by spkane** [ptsochantaris/trailer#341]
Some PR's look like they can be merged because all checks have passed, even thought a Github review is required before merging.

https://help.github.com/articles/enabling-required-reviews-for-pull-requests/

**Comment by spkane** [comment]
I found it. Not sure why I missed this the first time through the prefs.

**Comment by ptsochantaris** [comment]
Great! I'm glad you found the pref you were looking for.

The prefs aren't exactly a walk in the park these days - a cleanup is needed at some point, so, apologies.

(That said, you're very welcome to open new issues with suggestions on how prefs could be improved!)
