### ISSUE TITLE
Team mentions on review requests don't notify me

### ISSUE THREAD

**Issue by sammilechman** [ptsochantaris/trailer#345]
Apologies if this is related to https://github.com/ptsochantaris/trailer/issues/277 but reading that, it seems like it might be a separate issue.

I've noticed that whenever my teammates request review using the team alias (ex. `Backend Team`), I never get any kind of notification through Trailer. I've confirmed that I am a part of this team on GitHub.

Any thoughts on how I can remedy this?

**Comment by ptsochantaris** [comment]
Hi @sammilechman and sorry for the delay in replying.

I'm not sure if it's related to #277 - it might be, but it depends on what you mean by "requesting review" in this context. For instance, are they simply referencing your team in the PR description via a text edit? In that case that would probably be related to #277.

OTOH if they're posting a comment referencing your team, Trailer ought to be picking that up.

If you can give me a bit more info on the workflow involved I'd be more than happy to test this out and fix it if at all possible.

**Comment by sammilechman** [comment]
Hey @ptsochantaris - thanks for the reply!

I am referencing when a team is assigned to a PR via the right sidebar at the top. Hopefully this image explains exactly what I mean.

<img width="949" alt="trailer" src="https://user-images.githubusercontent.com/6484380/35121106-2b833262-fc4f-11e7-91f4-540554164d06.png">

**Comment by ptsochantaris** [comment]
Ah, I see! Thanks for the quick reply. In this case you're right: Trailer would not scan for teams there, it only scans for the current user, not their team(s). This must be a new feature from GitHub (and pretty useful!). I'll definitely look to see how/if this is exposed in the API and add it in, or get back to you on this thread if this isn't exposed in the API yet.

**Comment by rsumner31** [comment]
Thank you i been get ridof this signal   changing my vmwares to hacking me from the inside by remote ssh connect

**Comment by ptsochantaris** [comment]
I know, don't you just hate it when the signal changing my vmwares to hacking me from the inside? Me too.

**Comment by ptsochantaris** [comment]
Hi @sammilechman - Seems that GitHub decided to pull the rug from under the review assignment API anyway, by completely changing the format. I just had to do an update to fix this issue, but while I was at it, I thought I'd also add support for the team assignments too. So in theory the 1.6.5 build that's up now should also fix the issue you are seeing. Please give it a go and let me know how it goes.

**Comment by sammilechman** [comment]
Looks like it's working - thank you @ptsochantaris!!
