### ISSUE TITLE
GHE with API 2.12 seems to be broken with 1.6.5

### ISSUE THREAD

**Issue by cogitor** [ptsochantaris/trailer#347]
I'm using the Mac OS version of the app with the company Github Enterprise server on API level 2.12.

Once I've updated to 1.6.5 I was not able to sync pull requests and issues on Trailer. Reverting to version 1.6.3 works.

**Comment by ptsochantaris** [comment]
Ah, thanks for pointing this out. I have a feeling the Enterprise servers haven't yet caught up to the breaking change in the API that the new release catered for. I'll have to do a quick update to make parsing of that API backwards compatible. I'll try posting a fixed build here in a little bit for you to try our and see if it fixes things.

**Comment by cogitor** [comment]
Sounds like a plan..  Thanks!

**Comment by ptsochantaris** [comment]
Hi, have a go with this one and let me know if it corrects the issue. I wasn't able to test on a GE server directly, so I hope this won't blow up for you (if it does, just let me know and please keep using 1.6.3 while I dig deeper :))

[Trailer-1-6-6-test.zip](https://github.com/ptsochantaris/trailer/files/1678879/Trailer-1-6-6-test.zip)

**Comment by cogitor** [comment]
Cool. Unfortunately I'd have to wait until tomorrow morning (CET). Hope
that's fine!

**Comment by dylang** [comment]
Fixed it for me using Enterprise 2.12, thanks!

**Comment by ptsochantaris** [comment]
@cogitor No worries, let me know how it goes for you (I'm on GMT anyway)

@dylang thanks for testing! Glad it's fixed for you. For the sake of speed and having this disrupt as few people as possible, I'll put out an update for this now with the assumption @cogitor's test will go well too, and if something breaks I'll iterate on it then and there.

**Comment by ptsochantaris** [comment]
(PS for anyone using the build above, you won't get notified on this update, it will be the identical build)

**Comment by cogitor** [comment]
@ptsochantaris sorry for the delay. The new version is working on my side as well! 👍

**Comment by ptsochantaris** [comment]
Excellent! That's great to know. Update is now up for everyone else too, so thank you for reporting it and helping to fix it!
