### ISSUE TITLE
URL scheme to search

### ISSUE THREAD

**Issue by thespacedoctor** [ptsochantaris/trailer#349]
Is there a URL scheme for pocket trailer? I found that `pockettrailer://` works to open the app, but it would be lovely to be able to use a scheme to search. For example I could use

`pockettrailer://open/?filter=bug`

to instantly view all my issues with the bug label. 

Love the app BTW, especially the consolidated issue list.

**Comment by ptsochantaris** [comment]
Hi @thespacedoctor and I'm really glad you like the app!

Your suggestion makes a lot of sense and would be easy to add, I'll add it to the TODO list.
