### ISSUE TITLE
Feature request: New section "Assigned to review"

### ISSUE THREAD

**Issue by rsaunders100** [ptsochantaris/trailer#350]
### Rationale

If I add a comment on a review but I forget to complete the review it no longer say review requested.  This means if I use trailer to scan for outstanding review work I can miss a pending review.

Having a section named `Assigned to review` would simplift the workflow of checking for pending reviews. I would need to do everything in that list that does not say "@rsaunders100 approved changes".

**Comment by jscheel** [comment]
100%, this would be amazing

**Comment by ptsochantaris** [comment]
Question: Given the changes in how Trailer displays info for reviews along with the newer filtering and so forth, does it still make sense to have a specific section listed as "assigned to review"?
