### ISSUE TITLE
Feature request: allow changing the GitHub server URL

### ISSUE THREAD

**Issue by dainkaplan** [ptsochantaris/trailer#354]
Awesome app! The server API URL is currently hardcoded. Could this be exposed as an optional configuration setting to allow custom GitHub instances?

**Comment by ptsochantaris** [comment]
Hi @dainkaplan and thanks! Glad you like Trailer. I think what you need may already be there, as part of the `API Path` parameter on the server configuration tab of preferences? Apologies in case I have misunderstood your question, let me know if that's the case.

<img width="561" alt="server" src="https://user-images.githubusercontent.com/521581/38942109-e8cd9106-4325-11e8-8bfe-a39142ab656f.png">

**Comment by dainkaplan** [comment]
Super! User error 😅 The initial window did not make it apparent there were other options to set (I did look for a "preferences" menu option, but didn't see one.) All sorted, thanks!

**Comment by mbednarek81** [comment]
I also did not find it obvious how to configure my Github Enterprise URL from the Quickstart screen. I did not realise I could close Quickstart and open Preferences from the little icon at the top!
