### ISSUE TITLE
Notification banners flash up and disappear immediately

### ISSUE THREAD

**Issue by rossgardt** [ptsochantaris/trailer#359]
Quite often, I see notification banners flashing up in the right top corner. They disappear immediately. When I then click on the Trailer icon in the menu bar, there is no update. So, I guess these are notifications from objects (i.e. PRs, issues, etc.) that I excluded from my filter.

Does someone else experience this issue too?

Best,
Benedikt

**Comment by ptsochantaris** [comment]
Interesting! Please keep an eye on this and let me know if you have a better idea of where they may be from (or: why they should not have appeared in the first place, I guess :))

**Comment by rossgardt** [comment]
Okay Unfortunately they are too fast to click them 😜

**Comment by rossgardt** [comment]
I cannot really do anything about this and I also cannot provide any further information.
My assumption is that the flashing banners are from objects that I filtered out via the preferences.

For now, I will close this PR due to the lack of information.

**Comment by sarambasich** [comment]
Sorry to bump an old thread, but this is occurring for me in 2024. I am subscribed to the repos where the notification comes from. I am not sure why this happens. I've double checked my settings to ensure that everything is as it should be and it appears so.
