### ISSUE TITLE
Can I hide some items ?

### ISSUE THREAD

**Issue by Samemura** [ptsochantaris/trailer#360]
Hi, I love trailer on everyday.

Sometime, I muted an item to ignore for my mind. It is shown as light gray but still there is.
On my lists, muted items are increased and use large area. So I would hide muted items, or any way to hide that ??

**Comment by ptsochantaris** [comment]
Hi @Samemura - great to hear you're loving Trailer!

What you're trying to do sounds like it can be achieved indirectly. Set up a snoozing preset and do not specify a wakeup time. Also deactivate the options to wake up immediately on a certain event. Then also choose "hide snoozed section", and apply this to any items you want to "hide" this way via the context menu. That should do it.

See screenshots for an example:

<img width="992" alt="example" src="https://user-images.githubusercontent.com/521581/41280238-5e8481e0-6e26-11e8-9129-f69fb79ea513.png">

<img width="446" alt="screen shot 2018-06-12 at 09 54 30" src="https://user-images.githubusercontent.com/521581/41280357-aa65e414-6e26-11e8-9d2a-6ed5918280ba.png">

I hope this makes some sense - will that cover your use-case?

**Comment by Samemura** [comment]
Hi @ptsochantaris , thank you so much for quick response.

Your suggestion makes me happy ! Actually, I was not understanding what purpose of snooze is, but it is good feature like time limited mute/hide items I felt. Maybe some people wants to know this.

Anyway, thanks again, and I keep with Trailer !

**Comment by ptsochantaris** [comment]
That's great to hear, I'm glad you're finding it useful! As per your suggestion, an FAQ would make sense at some point, I agree - will keep it in mind. Closing this for now - but as always if you have suggestions or thoughts on how this feature can be improved feel free to open more issues.
