### ISSUE TITLE
Request: Allow hiding archived repos

### ISSUE THREAD

**Issue by Luzifer** [ptsochantaris/trailer#361]
Now that Github allows to archive repositories owners can freeze the state of a repository which also includes frozen issues. Those issues are still open but can't be edited even by the repos owner without previous un-archiving the repo.

While those issues are frozen it makes no sense to have them in the list of "active" issues and PRs. Therefore an option (or even default behaviour?) to hide issues from archived repos would make sense to me.

**Comment by ptsochantaris** [comment]
Hi @Luzifer and thanks for the suggestion! Sorry for the late reply, my presence from Trailer has been lacking a bit lately, and I'm now looking to catch up a bit.

This definitely makes sense and the attribute is exposed by the API, so it's a simple addition. Can you try out this test build if you have some time at some point? The option you're looking for is in the "Advanced" window under the "Repositories" tab. After you set it, just select "Re-scan now" and any archived repositories should in theory automatically change to "hidden" for both PRs and Issues.

[Trailer-168-1.zip](https://github.com/ptsochantaris/trailer/files/2152981/Trailer-168-1.zip)

**Comment by Luzifer** [comment]
From what I can tell after running the new version for around 3 days now: It works great and auto-hiding archived repos also works like a charm! 👍

**Comment by ptsochantaris** [comment]
Fantastic! Thanks for testing @Luzifer! I'll push out the update soon with some other changes too. Feel free to keep using this build - you'll get notified when the "final" one is up and I'll also give a shout here.
