### ISSUE TITLE
New watched repos are not showing up, new personal access token shows 0 repos

### ISSUE THREAD

**Issue by effektz** [ptsochantaris/trailer#362]
I've been using trailer for years and has always worked well. Recently I watched 2 new repos and after weeks, they will not show up in the "Repositories" list. Today I tried replacing my Github personal access token with a new one inside Trailer, and with that new token I get a message saying "You have no watched repositories, please add some to your watch list and try again", and none of my watched repos show up in my Repositories list. I did try going to "Advanced" and hitting "Re-scan now" with no luck. The permissions on my newly generated access token are `read:org, repo, user`. I'm currently on version 1.6.7

**Comment by ptsochantaris** [comment]
Hi @effektz - First off, just in case, try restarting Trailer. See if the repositories show up in the preferences Tab. If not, I'm guessing there may be a permissions issue with your token (and/or it may be a different account?) Try giving it more (all?) permissions just in case - GitHub may have altered permissions needed to get the subscription list for you. This is also partly corroborated by the fact that your recently watched repos don't seem to show up - i.e. GitHub hans't been providing the right watchlist for a while now for you.

You may want to check out the `[subscriptions](https://api.github.com/users/effektz/subscriptions)` endpoint yourself via `Paw` or `curl` to see what info GitHub is providing to Trailer, and use your token as authentication. I'm pretty certain this must be a permission thing, as v1.6.7 has been around for a long time now.

Let me know how it goes, let's see how we can get this sorted out.

**Comment by effektz** [comment]
I just finished reading this comment https://github.com/ptsochantaris/trailer/issues/311#issuecomment-285745057 and after also removing the app, and all of teh foldres and files listed in the comment, trailer is now seeing all the repos it couldnt find last time, and the green "API Use" bar in the servers tab is also functional again. Might be worth adding an option to "Start from scratch" so if this happens in the future, manual file deletion isn't required?

**Comment by ptsochantaris** [comment]
Hm, well, I'm glad it was fixed, whatever it was :) You're right about the reset option, it's something I've had on the TODO list for ages, and I should add it at some point - i.e. nuke everything and start from scratch - although I'm glad that these incidents are very rare (still? :)) This may be a good "nudge" for me to get onto that sooner rather than later 👍

**Comment by effektz** [comment]
Thanks @ptsochantaris for the quick response and for all the time you've put into the Trailer app! :)
