### ISSUE TITLE
Re-arranged cell and Mojave Dark Mode

### ISSUE THREAD

**Issue by jegnux** [ptsochantaris/trailer#364]
Hi @ptsochantaris 

I discovered your app and was really surprised by it. It's very complete and helpful.
As I'm on Mojave and use dark mode a lot, I noticed that Trailer wasn't compatible.
So I forked the project and make it work.
I also took the opportunity to change a little bit the UI to have more contrast (especially in dark mode) and bigger text. I also added the Pull Request number to fit my needs.

Then I rearranged the cell to have the count on right as in many other apps (Mail, Todo, Calendar, etc...).

Here are my results:

mode | BEFORE |  AFTER
--------|--------|---------
light |  <img width="546" alt="capture d ecran 2018-08-14 a 11 36 55" src="https://user-images.githubusercontent.com/63070/44084204-6827df0a-9fb6-11e8-946a-906891a33b4b.png"> | <img width="546" alt="capture d ecran 2018-08-14 a 11 31 10" src="https://user-images.githubusercontent.com/63070/44084227-732367b2-9fb6-11e8-9493-f00166582587.png">
dark | <img width="546" alt="capture d ecran 2018-08-14 a 11 36 45" src="https://user-images.githubusercontent.com/63070/44084259-85b6e1e2-9fb6-11e8-8638-e4b33f396b84.png"> | <img width="546" alt="capture d ecran 2018-08-14 a 11 31 19" src="https://user-images.githubusercontent.com/63070/44084286-93b40c02-9fb6-11e8-8dc8-d7a6797a926d.png">

Is it something you'd be willing to merge back here?

If so, I can work on a PR once:
- [ ] I fixed the missing red notification badge
- [ ] I added a setting to show/hide #PR-Number
- [ ] I added a setting to toggle bold titles
- [ ] I checked that I didn't break anything on iPhone as some part of the code is shared

I noticed you wanted Trailer to be highly customizable to fit many needs and I respect that. That's why I'm okay to add new settings for my changes. But tell me, if you think bold titles are great for everyone, I can also keep them without any option :)

**Comment by ptsochantaris** [comment]
Hi @jegnux and sorry for the slow reply - things are a bit busy right now.

I really like the idea of showing the PR number in the title, provided there was an option for it, and better support for dark mode on Mojave sounds really good - if you want to PR these just be sure that your changes are compatible all the way back to the earliest version of macOS supported, I know this API can be tricky.

On the UI changes I'm a bit more ambivalent, even though they do look very nice indeed, so I'd like to elaborate more and perhaps get more of your thoughts on it:

About moving the badges to the right, the problem there is not that the "total" badges would be positioned on the right, this is OK with me, but more that the red "new comments" badge would also have to move with them, which I would see as a UX issue, as it's far harder to scan for what's unread by scanning the right-hand side "column" and then have to scan your eye all the way to the left, crossing "the void" between the badge and right-most title word to find which row you're still on, the reverse and read what this is about for each entry, left-to-right. And once you're done reading, you then need to "jump" right across the "void" again to go back to where you were and keep scanning for items below that. You'd need 6 "eye movements" for each unread row, whereas on the left, it's one contagious scan to the right, and the one to the left to resume scanning - 2 in total. There could be some way to perhaps show the unread counter on the left separately from the total counter, but then I can't quite see how that could be done and still make the UI feel cohesive - but I'm definitely open to suggestions.

I'm not too keen on the bold titles, they don't really look like the macOS dropdown menus. I get your point about readability though, and I have to admit that when I built those views close to 5 years ago I could have done a better job with spacing and fonts - I'm not even sure I'm currently using the correct macOS font there for menus, so I'd be more than happy to correct that, if it's wrong, but ideally the goal would be to keep this view, as much as possible, in sync with macOS `NSMenu`s. This could perhaps come from altering the "subtitles" in some way? My main concern is that this still looks like a dropdown belonging to the menubar and also that information density is kept relatively high, something that large titles would also reduce. I'd definitely be open to discussing this more though and hear more about your view on this.

**Comment by ptsochantaris** [comment]
Hi, I'm going to close this issue for now but feel free to re-open if you have further thoughts, I'm definitely interesting in talking more about this.
