### ISSUE TITLE
Who updated the PR?

### ISSUE THREAD

**Issue by benedikt-roth** [ptsochantaris/trailer#366]
Hi! Recently, I am finding myself confused by the way on how updates are being displayed in the Mac OS X menu bar. An example:
<img width="441" alt="screen shot 2018-08-17 at 09 38 29" src="https://user-images.githubusercontent.com/234840/44253947-95ff3e80-a201-11e8-96ed-23fff3450ced.png">

It literally says "`@GauSim` updated Today at xxx". It looks like `@GauSim` updated the PR. But in fact the update is the one in the line before ("`@rossgardt` approved changes").

From my point of view, it would make sense to move the "updated Today at xxx" one line up.

What's your take?

Best,
Benedikt 🙂

**Comment by ptsochantaris** [comment]
Hi @rossgardt - I think you're right. I probably wouldn't create a new line (that would stretch out the PR/Issue lists) but it does make sense to perhaps move the phrase somehow, or make it less ambiguous, as the spacing there isn't exactly the pinnacle of UX design :) I'll definitely think about this and try to improve the situation there.

**Comment by ptsochantaris** [comment]
> From my point of view, it would make sense to move the "updated Today at xxx" one line up.

(Thinks about it for 5 years)

I think you're right. Or one line down, but that's the way to go. I'll update this in the upcoming release.

**Comment by ptsochantaris** [comment]
I've updated this UI element now on the most recent update. I know this issue is hopelessly outdated but thanks for your feedback and I hope this helps. Feel free to open more issues if this can be improved further!

**Comment by benedikt-roth** [comment]
Oh, this is great! Thanks a lot @ptsochantaris ❤️
