### ISSUE TITLE
Linux Port

### ISSUE THREAD

**Issue by domgreen** [ptsochantaris/trailer#367]
Really enjoyed using trailer on MacOS but on my Linux machine cannot find a tool that is anywhere near as polished.

**Comment by ptsochantaris** [comment]
Hi @domgreen!

I've often thought about a theoretical Linux port, but that would basically involve re-writing the whole app. There is no common infrastructure between the AppKit/UIKit/CoreData stack used in the macOS and iOS versions and Linux, except the network handling as part of Swift's Foundation layer. As a part-time open-source project, I would not be able to find any time even close to what would be needed to do a port like that justice.

I am definitely more than happy if anyone would like to create one though, and would try and offer as much help support as I could, in case you're thinking about doing one!

There is, of course, the ultra-geeky sister app to Trailer: [Trailer-CLI](https://github.com/ptsochantaris/trailer-cli), which can also build and run on Linux as well as Mac. However, this is not a GUI utility but a (very configurable, and cool IMHO ;)) command-line tool.

What may make it interesting to you is that, while Trailer-CLI has different goals from this project, part of its goals is to fetch and store PR/Issue data locally in plain JSON, which another GUI tool (for example, in Linux) could read and create a UI with. So, to be honest, if I or anyone else wanted to build a GUI tool in Linux, I would probably make it a wrapper for Trailer-CLI..?
