### ISSUE TITLE
Show source branch name for PRs

### ISSUE THREAD

**Issue by stembrain** [ptsochantaris/trailer#369]
Hello,
first of all, I love trailer. its one of my all-time greatest tools, an essential for productivity as a developer.

 unless I'm missing something, the UI displays the destination branch of the PR, but does not show the name of the source branch. Is that possible to show , optionally? The source repo name alone gives good information and context some times.

Cheers,

David

ps looking forward to trying Gladys!

**Comment by ptsochantaris** [comment]
Hi @stembrain and sorry for the ultra-slow reply. What you're saying makes sense, if this info is available on the API. There can be an option to display something like `steambrain/trailer → ptsochantaris/trailer` in the repo display line, if the two repos differ. I'll definitely look into it and see if this info comes from the API.

**Comment by stembrain** [comment]
Heya @ptsochantaris , happy 2021! It looks like the `head` property of the Pull Request api calls list the source repo and branch. It would be so useful to me if I could see this from trailer, as I often have my just my jira ticket number in the PR title, but multiple PRs and branches going for that one ticket, bc of changes that dont depend on each other.
for instance, im working on JIRA-123

my PR titles are like `[JIRA-123] update db` and `[JIRA-123] update frontend`

however the former's source branch on my local machine is `jira-123-db` and the latter's is `jira-123-frontend` . I will have forgotten the branch name i gave them, so when I see that my CI tests failed on one of them in trailer, i have to click it to go to github to see the branch name i used locally.

They aren't branches that descend from each other. I could adjust my branching process to get around this, but its more effective for me to have independent branches for the same feature. Smaller diffs are better for reviewers :)

**Comment by ptsochantaris** [comment]
Hi, I've created a test build of the next update with this feature included, feel free to give it a go and provide feedback or issues which you may encounter.

[Trailer.app.zip](https://github.com/ptsochantaris/trailer/files/6528483/Trailer.app.zip)

**Comment by ptsochantaris** [comment]
Hi, I'll be closing this issue as v1.7.6 is now up and includes this amongst other changes. If you encounter any problems with it, please feel free to open a new issue.
