### ISSUE TITLE
Trailer hard to read in macOS Mojave's dark mode

### ISSUE THREAD

**Issue by stembrain** [ptsochantaris/trailer#371]
![image](https://user-images.githubusercontent.com/1630902/46156110-c1d10380-c246-11e8-996e-da88e002512c.png)

Workaround: dont user mojave dark mode

**Comment by ptsochantaris** [comment]
Ah, thanks for reporting this. There are specific colours which Trailer is supposed to use in dark mode for these, which are a more vibrant green/yellow/red for statuses, for instance. It uses them in the "old" dark mode for example. Interesting that it's not using them in the "new" dark mode - clearly I missed something when tweaking. Will fix asap.

**Comment by ptsochantaris** [comment]
Here's a build that may improve the situation, let me know your thoughts and/or suggestions. I'll put this out as an update a little later on as well, but I thought I should let you sanity-check it first, as I see you are a heavy CI-status user 👍

[Trailer-1612-rc.zip](https://github.com/ptsochantaris/trailer/files/2427221/Trailer-1612-rc.zip)

**Comment by ptsochantaris** [comment]
Version 1.6.13 is now out which features this addition. I suggest you try it out directly and skip the dev build above :)

**Comment by stembrain** [comment]
![screen shot 2018-09-30 at 11 52 50 am](https://user-images.githubusercontent.com/1630902/46259447-8ed97a80-c4a7-11e8-8e78-5e207690cf66.png)

looks better! rock on, Paul!

**Comment by Davidslv** [comment]
Hi @ptsochantaris I'm having a similar problem with the hovering of an item, the colour scheme seems to have changed and it's a bit hard to read

![screen shot 2018-10-15 at 15 04 22](https://user-images.githubusercontent.com/136777/46955842-c3465c80-d08b-11e8-8aa2-2fa440efe219.png)

Although I'm on 10.13.6

Thank you :)

**Comment by ptsochantaris** [comment]
Ah, nice! No, it's fine, if you're not getting the issue anymore, then all is well that ends well! :) I'll close this larger issue in a little bit though, since it has been corrected, so feel free to open a new one if you encounter this issue again (or anything else, for that matter!).

**Comment by stembrain** [comment]
Hey @ptsochantaris , I'll close this since I filed it. its good now.
