### ISSUE TITLE
Stuck refreshing when using github enterprise with single-sign-on

### ISSUE THREAD

**Issue by tbutterwith** [ptsochantaris/trailer#372]
When using 1.6.13, the app hangs on refreshing and never finishes. This issue is not present in 1.6.7 but can be found in all later versions.

**Logs:** https://gist.github.com/tbutterwith/72d385d5eab3218cf5af881042f40cac

**Comment by ptsochantaris** [comment]
Thank you for creating this issue @tbutterwith ! One small point - there may be a permission tweak needed for the above gist, as I get a 404 when trying to access it.

**Comment by tbutterwith** [comment]
Apologies. I realised I left some internal urls in there that would be best to remove. You should have access now.

**Comment by NarendraTopsInfo** [comment]
Thank you. Now it’s Working.

**Comment by ptsochantaris** [comment]
I spotted a potential hanging issue in the API code when you have an extra API server that's not configured (it may have no token, for instance) and I was wondering if this may be the case. Can you try this build (it's identical to the official build, just with this bit tweaked) to see if it improves the situation at all?

[trailer-test.zip](https://github.com/ptsochantaris/trailer/files/2437615/trailer-test.zip)

**Comment by ptsochantaris** [comment]
Interestingly enough, I spotted this case in other bits of the code too, so I've fixed those cases too. This build contains those bits as well. When you have a moment, please do have a go and let me know in case it was this that was causing you the problem:

[trailer-test-2.zip](https://github.com/ptsochantaris/trailer/files/2437662/trailer-test-2.zip)

**Comment by tbutterwith** [comment]
The issue is resolved in that latest build. Thanks for the unbelievably quick response.

**Comment by ptsochantaris** [comment]
Ah, excellent! I'm glad that's what it was. It was a bit of bad coding from my end, it turns out, but at least I'm quick at fixing my mess :D

Thank you for reporting and testing it. I'll make sure I didn't cause some silly regression later on with my tweak and push this binary out on auto-update later today 👍
