### ISSUE TITLE
Statuses from GitHub checks are missing

### ISSUE THREAD

**Issue by vytis** [ptsochantaris/trailer#373]
We have some services integrated through GitHub Marketplace and it seems that these status items are not displayed in the summary.

In preferences I have "Show all status items" and I see this:

![screen shot 2018-10-16 at 17 48 13](https://user-images.githubusercontent.com/33914/47029428-d0d31380-d16b-11e8-93ab-a42f31db7ddb.png)

While on GitHub there is "Build and Test" which is missing in Trailer:

![screen shot 2018-10-16 at 17 48 18](https://user-images.githubusercontent.com/33914/47029461-e0eaf300-d16b-11e8-970a-a816002ab713.png)

**Comment by ptsochantaris** [comment]
Hi @vytis and thanks for reporting this!

This is very interesting, and I see that your PR is public, so I'll take a look at the API and what it's sending down to try and solve the mystery. Will keep you posted!

**Comment by vytis** [comment]
Thanks for checking it! I tried getting statuses from the API and saw the same result - checks are missing... This is quite unfortunate, but it definitely makes sense to avoid working with preview APIs. With so many announcements on the GitHub's conference in this area maybe there will be something new coming.

**Comment by ptsochantaris** [comment]
Indeed - although I should say it DOES make a lot of sense to support checks as a future feature, I'm just being a bit cautious about jumping in too early. I did this for reactions and reviews last year and it ended up causing some headaches... In any case thanks for being understanding about this. I'll keep an eye out for this API, but also if you notice it stabilising, please DO give me a shout so I can look further into it.

**Comment by dcsobral** [comment]
Please reconsider using the checks API. Even by the time you wrote that last comment last year, Travis, for one, was already [deprecating the use of the status API](https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories) and, in fact, does not provide it at all any longer for private repositories.

**Comment by ptsochantaris** [comment]
@dcsobral I'm definitely all for supporting this API, it's just that it's in beta for the moment. That said, it's been a few months now, so hopefully it's going to be stabilising and I can look into starting to build support for it soon.

**Comment by ptsochantaris** [comment]
Hi, I'll be closing this issue as v1.7.6 is now up and includes this amongst other changes. If you encounter any problems with it, please feel free to open a new issue.
