### ISSUE TITLE
Display issue or pr id number

### ISSUE THREAD

**Issue by dotKev** [ptsochantaris/trailer#374]
Feature request: our team always uses issue/pr numbers to reference our tickets. It would be great to have the option expose that in the issue/pr title. I see that it's available when I right-click, but seeing it at a glance would be fantastic.

**Comment by ptsochantaris** [comment]
Yes, this makes total sense, it's super-easy to add, and I've wanted to add it for a while. There was a contributed PR recently that was going to add it as part of wider changes, so I held off doing it myself, but that PR seems to have stalled. So, let me just add it in right now. Here we go:

[trailer1615-test1.zip](https://github.com/ptsochantaris/trailer/files/2599039/trailer1615-test1.zip)

To use it, just turn on the new option for "Prefix PR/Issue numbers in item titles" from the bottom of the display options.

I'm not sure if it's better to go with the GitHub version of putting the number after the title or before it. I've got a feeling that if you care enough for this option then you probably want it first, so the test version above does that. Also, dash, or no dash? :) Perhaps another colour/tone for the number..? Let me know your thoughts on this.

Also, be aware that you can always search for an item with a number using the `number:` prefix in search - like `number:374` for this issue, or just enter the number itself, as long as you have numbers active in the the "When filtering, always check..." section of the display preferences.

I hope this helps! Let me know your feedback at some point.

**Comment by dotKev** [comment]
I'm impressed with the fast turnaround! 
I've been using the filter to find issues quickly, but the visual cue is great for at-a-glance reference. 

Putting the number at the beginning is best for my needs. You may try making the text the same color as the time and without a dash. This way it can be differentiated from the actual, entered title. The current implementation is fine though.

**Comment by ptsochantaris** [comment]
v1.6.16 is out now with this change, it should show up on auto-update. Also, I agree with your suggestions above and have integrated them into that build :) 👍

**Comment by dotKev** [comment]
Perfect! Thanks.
