### ISSUE TITLE
Feature request: snoozed items

### ISSUE THREAD

**Issue by dotKev** [ptsochantaris/trailer#375]
Is it possible to have the option to _not_ count snoozed items in the menubar count? Perhaps it would make sense on the _Snooze_ preference pane?

I need to dive into Xcode so I can contribute to this project. :-)

**Comment by ptsochantaris** [comment]
Hi! Sorry for taking total ages to get back to you on this. I have implemented this option in the "Snoozed" section of prefs. If you are still using the app, can you give this build a go and let me know if I've understood correctly? Thanks!

[trailer-1490-test.zip](https://github.com/ptsochantaris/trailer/files/3144519/trailer-1490-test.zip)
