### ISSUE TITLE
Keyboard shortcuts not working when menubar is hidden

### ISSUE THREAD

**Issue by zenangst** [ptsochantaris/trailer#376]
Hey folks,

First of, loving app... I've been looking for something like this for some time now.
However, I've run into an issue with the keyboard shortcuts not working if the menubar is hidden.
I can dig into the source code and try to come up with a fix if you accept PR's.

**Comment by ptsochantaris** [comment]
Hi @zenangst and thanks for reporting this, and your nice comments about Trailer!

I'm very happy to accept PRs, or if you have trouble locating what's breaking I can take a look - let me know how you get on!

**Comment by ptsochantaris** [comment]
Hi, going to close this as it's been inactive for a while, but please feel free to re-open if it is still an issue or you'd like to discuss it more!
