### ISSUE TITLE
Feature - Allow to pick number as a global hotkey

### ISSUE THREAD

**Issue by j-martin** [ptsochantaris/trailer#380]
Right now only letters are supported. F-keys and other symbols might be relevant too.

**Comment by ptsochantaris** [comment]
Thanks for the PR @j-martin!

I'll take a look at it ASAP just in case some tweak may be needed (due to some spaghetti logic in the Trailer code, *not* your PR :)) and let's get it merged soon 👍

**Comment by j-martin** [comment]
Hi @ptsochantaris 

I tested the RC (https://github.com/ptsochantaris/trailer/issues/384#issuecomment-499003019) and it seems like it broke the global keyboard shortcut functionality completely.

On 1.6.16, the global keyboard shortcut works as expected and displays the main window/dialogue.
On 1.6.17, the same global keyboard shortcut does nothing.

I've looked at the console (enable the logging) and it just looks like the keyboard events don't get captured.

**Comment by ptsochantaris** [comment]
Hi @j-martin - can you check that you've allowed Trailer to access your keyboard via settings? It's possible that installing the RC may have reset that permission.

<img width="780" alt="Screenshot 2019-06-08 at 22 08 05" src="https://user-images.githubusercontent.com/521581/59152348-f3d37000-8a39-11e9-8a16-d1ce4aaa9ab1.png">

**Comment by j-martin** [comment]
It was there. Looks like there already. The issue seems to be from having `Automatically hide and show the menu bar` being enabled. Not sure why/how it became an issue in this release.

![image](https://user-images.githubusercontent.com/4259753/59173638-ae2eaa00-8b02-11e9-8109-e3cab7a2d46c.png)

Regardless, if the option is disabled **or** the menu bar (in general) is highlighted/shown then it works fine. 

You can disregard my initial report. :)

**Comment by ptsochantaris** [comment]
Ah, thanks for following up - I think this may be related to this issue: https://github.com/ptsochantaris/trailer/issues/376 So keep an eye on it if this is a problem for you. I'm making a note to look into the issue myself as well, as the original author of that issue hasn't responded yet.
