### ISSUE TITLE
Feature Request: Draft Indication/Grouping

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#382]
It would be nice to have an indication that a Pull Request is a Draft or an ability to group them separately.

**Comment by ptsochantaris** [comment]
Hi @cgatesman and sorry for the slow reply - I see that GitHub's API does provide a flag to identify a PR as a draft, I'll definitely look into how practical it is to support it (as it's a beta API feature currently) and follow up soon 👍

**Comment by bwebster** [comment]
Our team uses the draft feature on all PRs.  Having some sort of ability to group them or filter them out would be great!

**Comment by ptsochantaris** [comment]
Hi, I've been working on this, and have a test build for you to try out if you like, attached below. It will display a draft indicator on, or hide, PRs which are marked as such by the API.

Please note that you have to turn this feature on though in "Preferences" -> "Display" -> "If an item is a draft..." and pick a behaviour.

You can also chose to temporarily filter by a new `status` called `draft`, e.g. `status:draft,closed` and of course `!draft` reverses that.

Let me know if you run into issue and/or have suggestions for this feature.

[Trailer1502.zip](https://github.com/ptsochantaris/trailer/files/3746686/Trailer1502.zip)

**Comment by bwebster** [comment]
@ptsochantaris I've been trying out the new feature and it's great!

I did notice one issue - the "If an item is a draft..." preference doesn't seem to show the last selected option.  Every time I open up preferences, it always resets back to "Do Nothing".

**Comment by ptsochantaris** [comment]
Whoops, thanks @bwebster! I'll patch that right up and update in a little bit.

**Comment by ptsochantaris** [comment]
Here's a patched-up version, thanks for spotting it once again. Let me know if you spot anything else!

[trailer-1507.zip](https://github.com/ptsochantaris/trailer/files/3760823/trailer-1507.zip)

**Comment by cgatesman** [comment]
Fix corrects the settings not getting updated for me. 👍 

I haven't been able to test the Draft stuff, yet, though.  My next PR I create, I will start it as a Draft to test it out.

**Comment by bwebster** [comment]
@ptsochantaris The new build is working great.  I've tried it out for a few days now, and the new functionality is working great.  Thanks for your work on this!

**Comment by cgatesman** [comment]
Verified here, too! 👍
