### ISSUE TITLE
Feature request: use unix socket as a proxy

### ISSUE THREAD

**Issue by oliverzheng** [ptsochantaris/trailer#386]
My work uses a unix proxy as a file to gain access to the corporate network, which is where the GHE sits. Is it possible to specify a file path for the unix proxy to route all connections through that?

**Comment by ptsochantaris** [comment]
Hi @oliverzheng and sorry for the slow reply.

I may be being a bit slow but it would feel to me that this was something best left to a system or networking utility, like a VPN client or an app that routes your system traffic in the way that works best for your environment and setup. I'm not sure how adding networking configuration to Trailer itself would be of much help except for this one very specific use case..?

Am I completely missing your point? If so, please do set me straight on this!

**Comment by oliverzheng** [comment]
Sorry for the late response.

This is for my work computer, where the network setup has a VPN but there is also an additional unix socket to route the traffic for authentication.

Would it make sense to have an "Advanced" button on the server config tab, where there's a field to add a unix path?

**Comment by oliverzheng** [comment]
As a workaround, I ended up using `socat` to tunnel between the unix socket and a tcp port and a local http proxy to rewrite the host so it forwards to the right domain.

**Comment by ptsochantaris** [comment]
Hi @oliverzheng - thanks for getting back to me. On your first point, the issue continues to be that, sure, I could definitely add a field that points Trailer to a socket file, but what would Trailer do with eh socket file? How would it then use Foundation to make high-level HTTP calls to the API servers via that socket without the OS networking layer pointing to it as well?

Unless I'm misunderstanding what you are saying (again, it remains entirely possible that I am misunderstanding :)) then this is a VPN issue and not an app issue. Unless you're suggesting that Trailer contains it's own VPN functions, but if so, I would probably politely resist that suggestion, in that I don't believe that Trailer is the right tool to handle system networking configuration tasks.

To your second point, it sounds like you've gotten the TCP layer worked out. It's interesting that you're re-writing the host in calls though, why do you need to do that? I'm asking out of curiosity mostly, no worries if you don't want to go into details.

**Comment by oliverzheng** [comment]
Definitely agree that Trailer shouldn't implement any variant of a VPN. 😃  It seems like Trailer uses URLSession, but that doesn't support unix socket. https://stackoverflow.com/questions/40201308/swift-http-request-on-a-unix-domain-socket

My understanding is that unix sockets that act as proxies work similarly to an OS-level's http proxy, but you can have multiple user-configured unix sockets and multiple proxies. Similar to the TCP layer, the unix proxy is a destination for where to send HTTP data to. A browser resolves the domain name to an IP address and sends the HTTP packet there normally - it could very well send it to a local unix socket if it wanted to.

So the topology I ended up with is:

`Trailer -> localhost:6789, which my 10-line node http proxy listens on -> localhost:9876, which socat listens on -> a local unix socket -> outside my computer, to authenticated vpn land`

I need the http proxy to rewrite headers because having the API url (`localhost:6789`) as a configuration string means it's used both to resolve where to send data (TCP/unix socket) and what to put into the HTTP header. Since Trailer doesn't support proxies, it uses that in the HTTP host as well, which won't work because that's not where GHE is. My proxy modifies every HTTP request to have the actual domain of GHE, so that when it gets passed along to the unix socket proxy, it has the correct HTTP headers that the GHE server would eventually accept.

I don't think my setup is common enough, and since there is a workaround, I'm not sure if it's worth switching the HTTP stack just for it. Thanks for entertaining the idea though!

**Comment by ptsochantaris** [comment]
No worries at all, this was a very interesting discussion and it's fascinating to learn about other users' networking setups as well! I'll close this issue for now, but please do feel free to keep suggesting features and enhancements!
