### ISSUE TITLE
Use API path prefix instead of urls returned by API server

### ISSUE THREAD

**Issue by oliverzheng** [ptsochantaris/trailer#387]
Somewhat related to #386. I have a local proxy that redirects HTTP requests such that they go to a GHE instance. The API path entered in the preferences do not match what GHE thinks the API prefix is, because the local proxy is rewriting the host in each HTTP request.

Is it possible to follow urls in the API responses but replace the prefix with what is entered in the preferences? That way, locally proxied request will still work. Currently, Trailer fails a complete sync because it can't follow any of the urls.

**Comment by oliverzheng** [comment]
I ended up writing a local http proxy to parse every response and replacing any `A/v3/blah` with `B/v3/blah`. Feel free to close this if this wouldn't be useful. :)

**Comment by ptsochantaris** [comment]
Hi @oliverzheng - I think what you are looking for is the "API Path" setting in preferences. Whatever you put in there will  be i place for `A` or `B`. By default for instance it's `https://api.github.com` but you can change that to `https://my.server.org/api/v3` for example. Does this help?

**Comment by oliverzheng** [comment]
Again this was because of my odd setup as referenced in https://github.com/ptsochantaris/trailer/issues/386#issuecomment-493624835. Because I had to rewrite the HTTP host header, there was a mismatch between what Trailer thought the API server was, vs what it actually is. So when the API responses contained urls that Trailer didn't know about, it followed them, even though they didn't go anywhere in the network setup.

I think given that Trailer doesn't support this network setup, it's probably doing the right thing by following the urls returned by the server directly. 😃
