### ISSUE TITLE
Filter out some labels

### ISSUE THREAD

**Issue by oliverzheng** [ptsochantaris/trailer#388]
Similar to how it's possible to ignore things by a certain user, would it make sense to ignore certain labels and not show them? Some labels may be used for automation and deployment, which may not be as useful when looking at PRs as a set of conversations to have with teammates.

**Comment by ptsochantaris** [comment]
Indeed that sounds like a nice idea, adding to the TODO list.

**Comment by ptsochantaris** [comment]
Hi, I've created a test build of the next update with this feature included, feel free to give it a go and provide feedback or issues which you may encounter.

[Trailer.app.zip](https://github.com/ptsochantaris/trailer/files/6528483/Trailer.app.zip)

**Comment by ptsochantaris** [comment]
Hi, I'll be closing this issue as v1.7.6 is now up and includes this amongst other changes. If you encounter any problems with it, please feel free to open a new issue.
