### ISSUE TITLE
Feature request: don't count ignored-user comments towards the badge count

### ISSUE THREAD

**Issue by oliverzheng** [ptsochantaris/trailer#389]
The users I set to ignore are all bots. They post predictable responses to URLs, builds, etc. It'd be nice if the badge counts didn't include their comments, since I know for every new PR I create, a bot would add a comment.

Thanks!

**Comment by ptsochantaris** [comment]
Sorry for totally ignoring this issue for so long, this specific one is probably a (negative) personal record for me. I definitely like the idea of having an option for this, it does make total sense. Adding to the TODO list.

**Comment by ptsochantaris** [comment]
Hi, this build should contain this change - if you get a chance to try it and have comments, feel free to reach out. I'll include this in the next update.

[Trailer-185-test2.zip](https://github.com/ptsochantaris/trailer/files/12209239/Trailer-185-test2.zip)

**Comment by ptsochantaris** [comment]
Hi, this feature is now in the 1.8.5 release: https://github.com/ptsochantaris/trailer/releases/tag/1.8.5 - I'm going to close this issue for now, but please feel free to re-open, or open a new issue if you continue to experience this or other issues.
