### ISSUE TITLE
Pressing return after entering group name adds a space instead

### ISSUE THREAD

**Issue by vytis** [ptsochantaris/trailer#392]
It's a tiny UX bug that I noticed some time ago but never opened an issue.

I am running v 1.6.17 on macOS 10.14.6.

Steps to reproduce:
1. Open Preferences
2. Open Repositories tab
3. Enter some text in the "Group" field for repository
4. Press "Return" key on the keyboard

Expected:
Get out of editing mode, same as most other apps e.g. renaming file in Finder.

Happened:
Adds a space after the group name. Screenshot:

![Screenshot 2019-09-11 at 10 11 22](https://user-images.githubusercontent.com/33914/64679705-8beb5600-d47c-11e9-83cf-05c540f26e26.png)

**Comment by ptsochantaris** [comment]
Nice catch, thanks for reporting this, will fix asap.

**Comment by ptsochantaris** [comment]
This build should correct the issue, try it out and let me know if it improves things for you.

[trailer-1501.zip](https://github.com/ptsochantaris/trailer/files/3670608/trailer-1501.zip)

**Comment by ptsochantaris** [comment]
All good points! I'll make a note to get around to this at some point (PRs are ofcourse always welcome). And thank you for your kind words, I've very glad Trailer is useful for you!

**Comment by ptsochantaris** [comment]
Hi! I've been doing some tweaking and this build should have the focus issue you mentioned above "fixed" (well, it's not really fixed, more like worked-around in an ugly way, I'm not entirely sure how to fix it properly) In any case, I thought I'd drop this build here for you in case you want to try it out.

[trailer-1511.zip](https://github.com/ptsochantaris/trailer/files/3964034/trailer-1511.zip)

**Comment by vytis** [comment]
@ptsochantaris tried the build you provided and it now works 100% as expected! Great job, all these small things are quite annoying to fix but quite important in the end!

**Comment by ptsochantaris** [comment]
Hi, and happy new year!

I've started a beta "stream" for Trailer 1.7 containing this feature and much more here: https://github.com/ptsochantaris/trailer/pull/400 In case you feel like trying it out and reporting any problems you may encounter, you're very welcome to!
