### ISSUE TITLE
Do not show "global" group when nothing will fall in it

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#393]
For example, I have several repositories all of which are hiding Issues in Trailer except for one which I have a Group set on.  In this configuration, I see the Issues group with a count and another Issues icon (some global group?) that is always `0` count.  It would be nice if this other global group icon is not shown if it is not possible for anything to ever fall under it.

Or perhaps, it would be nice to have an option to hide either of the Issues or Pull Request "global" icons when their count is `0`--just like what happens to the group icons.  This would be nice for those of us that use groups for most repositories while leaving a few low activity repositories without groups.  The only gotcha is dealing with the case where everything is `0`, and you'd still want some kind of icon available to access the context menu.

**Comment by ptsochantaris** [comment]
Hi @cgatesman - what you're describing is what should be happening already, i.e. that the icon which holds items which aren't assigned to a group should get hidden if there's nothing to show.

If you're not seeing items there but it's still showing up then that sounds like a bug to me - see if you can fidget around a bit with your config to see what's causing it and let me know, I can get onto fixing it asap. Perhaps one key to understanding what may be happening would be the message that you are seeing in this empty global group, see why Trailer thinks it's empty and why that may not actually be the case :)

Sorry if this is a bit vague, but basically what you're seeing is a bug I think - if you can find out how to reproduce it I'll fix it asap.

**Comment by cgatesman** [comment]
<img width="574" alt="Screen Shot 2019-09-24 at 9 57 47 AM" src="https://user-images.githubusercontent.com/6276072/65518119-c8be4080-deb1-11e9-9f53-97aa31f93700.png">

**Comment by ptsochantaris** [comment]
Ah, I see what's happening there - you have issues in your global group, so trailer is showing both the PR and Issue tabs. The workaround is to basically create a group for whatever is showing up in your global issues tab, but you're right in that it would be nice if the zeroed-out group just didn't show at all. Putting this on the TODO list.

**Comment by cgatesman** [comment]
> you have issues in your global group

Did you mean pull requests?

**Comment by ptsochantaris** [comment]
I did indeed, was typing too fast :)

**Comment by cgatesman** [comment]
> The workaround is to basically create a group for whatever is showing up in your global issues tab

This isn't an ideal option for me, because I have a large number of repositories that fall under the global.

**Comment by cgatesman** [comment]
FWIW, I don't have any global Pull Requests, now, and they're still showing up:

<img width="574" alt="Screen Shot 2019-09-27 at 11 39 43 AM" src="https://user-images.githubusercontent.com/6276072/65782430-a3cd0600-e11b-11e9-9c81-d07fc322ac36.png">

I don't know if this is because there are actually Pull Requests filtered out because I have them set to only show "Participated".

**Comment by ptsochantaris** [comment]
Indeed, the second screenshot is a good clue as to what's going on I think. It probably makes sense to improve this so that it takes the final visible count into account, and not whether there are items in those repos which may be hidden. I'll take a look at this, although things are. bit busy for me these days and it may take a little while :( - If you think you can spot the issue and/or have time for a PR it would definitely be very welcome!

**Comment by ptsochantaris** [comment]
I think I may have found the issue deep in some of the ancient part of the code :) Could you give this build a shot and let me know if it improves things for you?

[Trailer-1503.zip](https://github.com/ptsochantaris/trailer/files/3746989/Trailer-1503.zip)
