### ISSUE TITLE
Catalina: Failed to load optimized model

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#395]
I don't know if this is due to upgrading to Catalina, because it's been a while since I tried running Trailer from the command line.  Anyways, when I do, I'm now seeing this error.  Trailer seems to be running ok, but I just wanted to report this:

```
CoreData: annotation:  Failed to load optimized model at path '/Applications/Trailer.app/Contents/Resources/Trailer.momd/Trailer 39.omo'
```

**Comment by ptsochantaris** [comment]
Thanks @cgatesman and apologies for the massively slow response. This is fine, it comes from Core Data and has to do with some internal loading issue. Thanks for reporting it though, and I promise to keep a better eye on the issues section here from now on! 😱
