### ISSUE TITLE
Feature request: ignore specific "Participated" pull request

### ISSUE THREAD

**Issue by waabiisaabii** [ptsochantaris/trailer#396]
Hi,

It's an amazing app and I'm wondering if we could add a feature to ignore some of those pull requests in `Participated` section?

**Comment by ptsochantaris** [comment]
Hi @waabiisaabii - I’m really glad you’re finding Trailer useful!

You can hide items using the “Snooze” setting. If you create a snooze preset and provide no specific duration, and remove any criterion to auto-waking an item, that will move the item to the “Snoozed” section. You can then chose to additionally hide the snoozed section, which will effectively make that item invisible.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/521581/78258052-95104300-74f2-11ea-8226-3003e0463db4.png">

**Comment by ptsochantaris** [comment]
Wow, I just realised I'm severely late in answering your question BTW, no clue why I hadn't seen this issue before... apologies!

**Comment by waabiisaabii** [comment]
> Wow, I just realised I'm severely late in answering your question BTW, no clue why I hadn't seen this issue before... apologies!

haha no worries i'll try it out thank you!
