### ISSUE TITLE
Sparkle update system keeps previous versions on disk

### ISSUE THREAD

**Issue by aik099** [ptsochantaris/trailer#397]
I've noticed, that `~/Library/Application Support/Trailer/.Sparkle` folder on my disk is where all previous app versions are silently placed. They aren't even deleted after update. Over time this folder can grow to a considerable size, because each upgrade adds 2 files (zipped version + unzipped version).

Not sure if you can do something about it.

**Comment by ptsochantaris** [comment]
Hm, thanks for letting me know about that, I didn't even know Sparkle did that 😂 

I'll check to see if it has an option to disable or trim this and get back to you!

**Comment by ptsochantaris** [comment]
Hi, I'm going to close this issue as I really haven't been able to reproduce it, it could just have been an older version of Sparkle perhaps? But please feel free to open a new issue if this keep occurring and/or if you have more info on it!
