### ISSUE TITLE
Automatically snooze ignores filter settings

### ISSUE THREAD

**Issue by maxwellainatchi** [ptsochantaris/trailer#399]
I have a watched repository that's configured to only show my issues/PRs, and if I turn on the auto-snooze feature, it puts all the other issues in that repository into my "snoozed" section

**Comment by ptsochantaris** [comment]
Ah, good catch, thanks for reporting this. I’ll look into this and update you soon.

**Comment by ptsochantaris** [comment]
Hi @maxwellainatchi and sorry for taking so long to update you on this issue - I think I found the logic problem and have corrected it, but can I bother you to give this build a try to see if it fixes the issue for you? If so, I'll update the most recent beta with this tweak.

[Trailer170-beta6-rc.zip](https://github.com/ptsochantaris/trailer/files/4174077/Trailer170-beta6-rc.zip)

**Comment by maxwellainatchi** [comment]
Sure! I'll give it a try now

**Comment by maxwellainatchi** [comment]
Hm, the auto-snooze in that build doesn't seem to work at all for me. I have an issue that was last updated 24 days ago, but it's not being snoozed when set to auto-snooze after 1 day idle

**Comment by ptsochantaris** [comment]
Could it be that you manually woke the item at some point? Trailer won't auto snooze an item that has been manually woken. Auto-snoozing seems to be working fine the the build I'm using and I haven't touched that code :/ Does this happen on all old items, or was it specifically that one?

**Comment by maxwellainatchi** [comment]
I'm not sure, that's the only item I have that hasn't been manually woken. It might've had something to do with the earlier auto-snooze failure though?

**Comment by ptsochantaris** [comment]
It could... I'll definitely keep an eye on this though to see what may be going on. Thanks for testing it out! If you can reproduce this with any other item or think you may have spotted another case of this going wrong please _do_ give a shout!

**Comment by maxwellainatchi** [comment]
It's still ignoring the filter settings, but now it shows the ones that should've been appearing as recently closed (as well as showing them in the snooze section)

![image](https://user-images.githubusercontent.com/4398327/74263403-bb70e980-4ccc-11ea-9c9d-4bd4c5e30ce8.png)

**Comment by ptsochantaris** [comment]
@maxwellainatchi I think your database may have gotten corrupted - either because you may be running two instances of Trailer at once or something may have gone burb during the upgrade. My first recommendation would be to make sure that you're only running once instance, and then select "Reload All Data" from the "Misc" tab in preferences to "reboot" your DB. Hopefully things should improve, let me know how it goes 🤞

**Comment by ptsochantaris** [comment]
(Hm, another thought is, are you by any chance accessing the same repo from two difference accounts perhaps?)

**Comment by maxwellainatchi** [comment]
Ah yeah I was briefly running 2 trailer instances yesterday when I first downloaded the beta. Turns out the reason it went back to the old behavior was because it was the old version that launched on startup when my computer autoupdated last night.

It's displaying the correct behavior now after relaunching the beta and clearing the database - maybe a day needed to pass using the beta for it to register the auto-snooze?

**Comment by ptsochantaris** [comment]
Ah, great to know! About the auto-snooze, in theory it should work straight away, as the date that it uses is the one provided by GitHub, Trailer doesn't keep an "internal" timer of item modifications, but I'll definitely keep an eye on that. If you think you notice that behaviour again or have thoughts on what may be happening, please _do_ give a shout 👍

**Comment by maxwellainatchi** [comment]
Will do. Thanks for the fix!

**Comment by ptsochantaris** [comment]
No problem, thanks for reporting it!

Since you're using the beta, you may want to track #400 and use the latest build from there to get the latest fixes for this version as they're done, hopefully it should be stable "enough" for a "proper" release :)
