### ISSUE TITLE
Feature request: Add ability to only show red status checks

### ISSUE THREAD

**Issue by dr3** [ptsochantaris/trailer#402]
Currently if you have show statuses enabled, Pull requests with a lot of statuses take up a lot of vertical space

The ability to only show failed and/or pending status checks would be ideal to get the most value for vertical space

**Comment by ptsochantaris** [comment]
That makes a lot of sense, adding to the TODO list 👍

**Comment by ptsochantaris** [comment]
Hi, I've created a test build of the next update with this feature included, feel free to give it a go and provide feedback or issues which you may encounter.

[Trailer.app.zip](https://github.com/ptsochantaris/trailer/files/6528483/Trailer.app.zip)

**Comment by ptsochantaris** [comment]
Hi, I'll be closing this issue as v1.7.6 is now up and includes this amongst other changes. If you encounter any problems with it, please feel free to open a new issue.
