### ISSUE TITLE
Stuck on Refreshing repository after adding cloned repository from hard drive

### ISSUE THREAD

**Issue by MrKristoffVA** [ptsochantaris/trailer#403]
I recently started using Github on a new machine, so I used an external USB hard drive to copy over my company's repository to it so I wouldn't need to download everything. However, this time when I loaded the local repository Github is stuck on "Refreshing repository."

The progress bar makes it look about 80% done, but I let it go for about 24 hours and it won't budge. This is a large repository, about 200 GB, but I have all of the files already on my machine. Also, the last time I did this kind of move from one computer to another this part of the process went very fast.

Any ideas about what is happening here? Thanks.

**Comment by ptsochantaris** [comment]
Hi @MrKristoffVA, unless I've misunderstood this isn't really a Trailer issue? Please let me know if I've misunderstood your issue.
