### ISSUE TITLE
Feature - Allow to copy the branch name from the context menu

### ISSUE THREAD

**Issue by j-martin** [ptsochantaris/trailer#404]
I often end up having to open GitHub from Trailer to then copy the branch name in the PR.

It would be nice if there was an option to do so when right-clicking on a PR.

![image](https://user-images.githubusercontent.com/4259753/81609268-75d7c180-938c-11ea-944d-e2326bd342d1.png)

**Comment by ptsochantaris** [comment]
That makes sense, adding to the TODO list!

**Comment by ptsochantaris** [comment]
I've updated the beta with the feature (#400), have a go and let me know if it's what you meant (also, any other issues you may spot with the beta, please do give a shout in that thread :))

**Comment by j-martin** [comment]
@ptsochantaris I just tried build 1.7.0 (1561). If I click on the PR it copies a reference to the PR `<ORG>/<REPO>#<PR-ID>` which if fine and reasonable. It might make sense to add the branch name under the PR number and have a similar name copy logic.

Alternatively, I was thinking it would make sense to add an item to the context menu `Copy branch name     Shift-⌘C`. I tend to prefer a contextual menu since they offer better discoverability IHMO.

**Comment by j-martin** [comment]
To be clear, I am interested in getting the git branch name so I can quickly checkout the branch through a normal `git checkout`.

**Comment by ptsochantaris** [comment]
Hi @j-martin - you should already see that, however you may need to "reload all data" from the preferences menu to refresh the data cache stored locally by Trailer, that's something I forgot to mention :) This is what _should_ come up after that:

<img width="494" alt="Screenshot 2020-06-24 at 18 31 28" src="https://user-images.githubusercontent.com/521581/85604142-ec810380-b648-11ea-9ebb-df843a0e28c4.png">

**Comment by ptsochantaris** [comment]
(PS your point about adding a shortcut key though definitely does stand, I'll add one in :))

**Comment by j-martin** [comment]
I can confirm it was a user error. It is working. Should I leave this issue open you add the keyboard shortcut/menu option?
