### ISSUE TITLE
Feature - Open CI/check URLs directly from the context menu

### ISSUE THREAD

**Issue by j-martin** [ptsochantaris/trailer#405]
Similar to https://github.com/ptsochantaris/trailer/issues/404, I often click on PR to then go to GitHub then click on a failing check to get to our CI system.

It would be nice we could do that by just right-clicking on the PR from Trailer.

![image](https://user-images.githubusercontent.com/4259753/81609471-cfd88700-938c-11ea-8892-924311a34470.png)

Note that some repos may have more than one check/ci system in place.

**Comment by ptsochantaris** [comment]
Hi @j-martin and sorry for the very slow reply. You can do that already if you Cmd-Click on a status item in the Trailer menu. If you often perform that action, you can set the option "Make any displayed PR status line always selectable" option in the `Statuses` tab of the preferences. I hope I have understood your issue, please do let me know if I've missed the point :)

**Comment by j-martin** [comment]
That's exactly what I was looking for. Trailer is so feature-full that it's easy to miss existing features! I've been using Trailer for years, and it was on my wish list for the longest time.

In this case, maybe discoverability could be improved. Maybe a tooltip telling the user to use cmd+click if the status is hovered.
