### ISSUE TITLE
Refresh - last update failed

### ISSUE THREAD

**Issue by electroducer** [ptsochantaris/trailer#406]
Getting the red X (last update failed) and am unable to refresh on mac os 10.15.4. No changes made on my part, but has suddenly not been working. Can I pass on anything to debug?

**Comment by electroducer** [comment]
Figured it out. It's a bug.

I had a PR that >100 comments; however the API call to get the comments includes the `per_page=100`, which yields a `502` from the server in this case. The call works fine though if you remove the parameter.

**Comment by ptsochantaris** [comment]
Hi @electroducer and sorry for my extremely late reply. Thanks for digging into and seeing what's breaking. Does this still happen? 502 would suggest GitHub is having a bit of an issue (as the per_page parameter has always worked with the value 100 up until now) but they do have a habit of tweaking things in the background. If it keeps breaking I guess it may be a good idea to reduce that value in Trailer. Let me know when you have some time, and again, sorry for the very late reply.

**Comment by electroducer** [comment]
In testing out the API calls, here's what's up:

```
# This PR has >100 comments
MY_REPO_PR="https://api.github.com/repos/my/repo/pulls/123"

# Currently this is what Trailer calls:
curl GET "$MY_REPO_PR/comments?per_page=100"
# This returns a 502

curl GET "$MY_REPO_PR/comments?per_page=1000"
# This returns a 502 as well, even though the number of comments < 1000

# Drop the per_page parameter
curl GET "$MY_REPO_PR/comments
#  This gives me at least some of the comments (not sure how many)

# Include page parameter only
curl GET "$MY_REPO_PR/comments?page=1
# This gives me the same thing as the previous call

# Page 1 with 100 per page
curl GET "$MY_REPO_PR/comments?page=1&per_page=100"
# Returns a 502

# Page 2 only
curl GET "$MY_REPO_PR/comments?page=2"
# This returns some comments in the middle (I'm guessing the default per_page parameter is set to 50 maybe?)

# Page 2 with 100 per page
curl GET "$MY_REPO_PR/comments?page=2&per_page=100"
# Returns the latest comments to the end

# Page 2 with 1000 per page
curl GET "$MY_REPO_PR/comments?page=2&per_page=1000"
# Returns the same as previous
```

So basically it seems like the `per_page` parameter is useless at this point and will either 502 or have no effect when in combination with `page=2` or higher

Not sure how you want to handle this in this app. Perhaps either ignore the 502s or drop the `per_page` from the call and just get the first few comments? What are you hoping to get out of this call?

**Comment by ptsochantaris** [comment]
Hi, thanks for the detailed report! per_page maximum is 100, so 1000 would just be ignored by the server, it would just max out to 100 from its perspective. My guess is that GitHub's engineering has screwed up and has calls which time out their own gateway, like they have with their v4 API, which they still haven't fixed. The default per_page value is too low to leave as-is, unfortunately, or Trailer would eat up all out API quota trying to index comments. Can you try that call with decreasing values of `per_page` and see at what point it stops giving a 502 for you? Best way would be to decrease by 10 until it works (e.g. 90, 80, 70, etc) and increment by 1 until it stops working (e.g. at 74 or whatever it may be) Let me know how it goes. Sorry I can't do this myself but clearly there's something about the comments in the item you're trying to fetch which is giving GH's API a headache (which isn't too hard to do these days 😞)

**Comment by electroducer** [comment]
Ah, good call. Didn't think to go down instead. The highest I can go with the troublesome PR that I have here is 48. Once I set it to 49 or higher, it errors out. I can set the parameters as `?per_page=48` or `?page=1&per_page=48` and it all works fine! Weird though... it's definitely GH-side, and it could even be a bug with this particular PR, because I don't have another one with that many comments atm. Will let you know if I can confirm that the issue is happening with others.

**Comment by electroducer** [comment]
I crossed 100 comment threshold for another PR and things are working fine, so I really don't know what's going on here...

**Comment by ptsochantaris** [comment]
Indeed, in theory it should work fine, so it's definitely a GH issue, although that is no comfort in that the app isn't working as it should :) This could be fixed with an advanced option to reduce the batch number on queries with the tradeoff of higher API usage, but I wonder if you can make your problem go away for good by turning on v4 API support in the server tab of preferences?

**Comment by electroducer** [comment]
How do you turn on the v4 support? Not seeing a toggle.

**Comment by ptsochantaris** [comment]
Whoops, I keep forgetting that the beta isn't the official version yet, my bad. You can get the latest beta from here #400 which is pretty much at pre-release stage right now. It contains the option to turn on v4 API sync in the servers pane of preferences:

<img width="463" alt="Screenshot 2020-06-25 at 18 28 01" src="https://user-images.githubusercontent.com/521581/85769234-b3f92c80-b711-11ea-8774-e05abe2e0183.png">

**Comment by electroducer** [comment]
ah, yes, figured it out.... and it works! Feel free to mark this as resolved by switching to v4

**Comment by ptsochantaris** [comment]
Ah, good to know! Thanks for bearing with me on this. I'm still a bit concerned over the v3 issue though, so I'll keep an eye on it and/or watch out for similar reports from other users. Sorry for the runaround with the beta, soon it will be the "official" version :)
