### ISSUE TITLE
Review re-requested after approval still shows the user as approving the pull request

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#409]
If a user approves a PR, but you then request them to review it again, Trailer still shows the user has approved the PR.  GitHub changes their status to orange ("Awaiting requested review").

I suspect this is because the summary at the bottom of the PR shows the user has approved it, but that same user falls under "pending reviewers", as well.  I'm not sure if something can be done about that in Trailer.

**Comment by lucascurti** [comment]
The same happens when a user requests changes to a PR and then request them to review it again. Trailer keeps showing `<user> requests changes`.

**Comment by ptsochantaris** [comment]
Just short of a year later, I finally found the time to sort this bug out. Very sorry for taking ages. The solution is exactly what you mentioned @cgatesman - Trailer needed to "subtract" the assigned reviewer from the existing reviews, and to also then ensure that when a review assigned is removed (the user had reviewed) then it needs to clear that entry locally as well. This beta build should have this fix:

[Trailer.app.zip](https://github.com/ptsochantaris/trailer/files/6758443/Trailer.app.zip)

**Comment by cgatesman** [comment]
Excellent!  No worries on the time line.  I'll get this installed and let you know how it goes.

**Comment by cgatesman** [comment]
Installed, and it looks like this fixes this issue. 👍

**Comment by ptsochantaris** [comment]
Hi, I'll be closing this issue as v1.7.6 is now up and includes this amongst other changes. If you encounter any problems with it, please feel free to open a new issue.
