### ISSUE TITLE
Very Minor Improvement - Make CI link hover color a bit nicer

### ISSUE THREAD

**Issue by j-martin** [ptsochantaris/trailer#410]
When highlighting a CI result (to open the link), the link becomes blue. In dark mode at least it's a bit rough looking. While being very minor, it feels a bit odd considering the general high polish level of Trailer. :)

In dark mode, it could be a shade brighter of green, yellow, or red depending on the status.

![image](https://user-images.githubusercontent.com/4259753/89559111-0f671180-d7ca-11ea-8691-3eb94584c725.png)

As usual, thanks for making Trailer. :)

**Comment by ptsochantaris** [comment]
Hi and sorry for the slow reply, my time spent on Trailer has been far less than it should be recently. You're totally right about this, I'll definitely look into it 👍

**Comment by ptsochantaris** [comment]
Hi, I'm closing this issue as the update with this change is now live, but please feel free to reopen or create a new issue if you spot any issues or have any more suggestions about this!

**Comment by j-martin** [comment]
Confirming that everything looks nice now. :)
