### ISSUE TITLE
Feature request: Hide PRs from specific sources

### ISSUE THREAD

**Issue by ballpointcarrot** [ptsochantaris/trailer#411]
Hello, and thank you for the work you've done on Trailer. 

We use Dependabot to track and automatically update dependencies in our repositories. I would love to have the ability to block these PRs showing up as notifications in my list, as it quickly overwhelms the rest of the project details I would be interested in reviewing.

If there's already a way to filter out specific PR requests by a username, I would love to know; it seems like it's not possible based on the current implementation.

**Comment by ptsochantaris** [comment]
Hi @ballpointcarrot and sorry for the very late reply.

You're right in that you can't currently hide something based on the username, but you definitely can stop notifications being presented to you about those items by using the option in the "comments" tab of preferences.

Additionally, you can make items disappear from your PR list by using a search predicate, something like:

```
user:!username
```

However, I realise that ideally you don't want to have permanent things stuck in the search field, and it would make sense to add this as a permanent option as well. Adding to the TODO list!

**Comment by onlyplo** [comment]
This feature would be great at filtering out dependabot PRs which essentially spams Trailer everyday. :(

**Comment by ptsochantaris** [comment]
Hi, I've created a test build of the next update with this feature included, feel free to give it a go and provide feedback or issues which you may encounter.

[Trailer.app.zip](https://github.com/ptsochantaris/trailer/files/6528483/Trailer.app.zip)

**Comment by jscheel** [comment]
> Hi, I've created a test build of the next update with this feature included, feel free to give it a go and provide feedback or issues which you may encounter.
> 
> [Trailer.app.zip](https://github.com/ptsochantaris/trailer/files/6528483/Trailer.app.zip)

You just made me a very, very happy man ❤️

**Comment by onlyplo** [comment]
_choked on coffee reading this_ - amazing.🏃‍♂️💨 running to test it out now.

**Comment by ballpointcarrot** [comment]
Works beautifully on this end. Much appreciated. ❤️

**Comment by ptsochantaris** [comment]
Hi, I'll be closing this issue as v1.7.6 is now up and includes this amongst other changes. If you encounter any problems with it, please feel free to open a new issue.
