### ISSUE TITLE
Can't open mac app (1.7.0) on El Capitan (10.11)

### ISSUE THREAD

**Issue by Amorymeltzer** [ptsochantaris/trailer#412]
Excerpt from crash log (full logs available if you like):
```
Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/CoreSpotlight.framework/Versions/A/CoreSpotlight
  Referenced from: /Applications/Trailer.app/Contents/MacOS/Trailer
  Reason: image not found
```

And indeed I have no CoreSpotlight framework there.  I don't know anything about swift or mac development, but [the Apple docs](https://developer.apple.com/documentation/corespotlight) suggest it was only added in 10.13, so presumably b035a985 is at issue?

I should add that if Trailer now requires 10.13 (although e1ed3b5 suggests otherwise), that's A-Okay, I just didn't see it noted.

**Comment by ptsochantaris** [comment]
Hi @Amorymeltzer - thanks for reporting this! Trailer should work fine on 10.11, it should not require CoreSpotlight unless it's available, and the code has logic to do that. However clearly something has gone wrong with the linking, as the error above makes it seem like it's a required library. I'll dig into it asap and post a follow up here very shortly.

**Comment by ptsochantaris** [comment]
OK, I was totally and completely wrong, the code didn't have that logic, I clearly forgot to add it in, hence the explosions. I've now added the appropriate safeguards, could I get you to give this build a go and see if it corrects the issue for you? If not, does it produce the same error?

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/5252454/Trailer.zip)

**Comment by Amorymeltzer** [comment]
@ptsochantaris Thanks for the quick reply, but sadly yes, it likewise doesn't open with the same error:

```
Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/CoreSpotlight.framework/Versions/A/CoreSpotlight
  Referenced from: /Users/USER/Desktop/Trailer.app/Contents/MacOS/Trailer
  Reason: image not found
```

**Comment by ptsochantaris** [comment]
Damn, OK, will keep digging, time to break out a 10.11 VM, stay tuned :)

**Comment by ptsochantaris** [comment]
How about this one?

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/5252515/Trailer.zip)

**Comment by Amorymeltzer** [comment]
Different!  The PR icon briefly shows up in the menu bar, but then disappears.

<details>
<summary>Excerpt from error report</summary>

```
Crashed Thread:        5  Dispatch queue: NSOperationQueue 0x7fc708dd2ea0 :: NSOperation 0x7fc708cd1670 (QOS: BACKGROUND)

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7fc708cd2190 of class __NSCFLocalDataTask was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7fc708cd54f0> (
<NSKeyValueObservance 0x7fc708cd3250: Observer: 0x7fc708cd5780, Key path: state, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x7fc708d0c540>
)'
terminating with uncaught exception of type NSException
abort() called
```

</details>

There's actually a bunch of other stuff in the console:

<details>
<summary>Excerpt of some messages before crash report</summary>

```
9/20/20 16:12:19.587 taskgated-helper[44647]: validated embedded provisioning profile: file:///Users/Amory/Desktop/Trailer.app/Contents/embedded.provisionprofile

9/20/20 16:12:19.739 Trailer[44881]: CoreData: Failed to load optimized model at path '/Users/Amory/Desktop/Trailer.app/Contents/Resources/Trailer.momd/Trailer 41.omo'

9/20/20 16:12:20.634 Trailer[44881]: An uncaught exception was raised

9/20/20 16:12:20.635 Trailer[44881]: An instance 0x7fe14962f090 of class __NSCFLocalDataTask was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7fe1495dd780> (
<NSKeyValueObservance 0x7fe1495f6970: Observer: 0x7fe149610bd0, Key path: state, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x7fe14961a070>
)
```

</details>


Then, every ten seconds, there's:

```
9/20/20 16:14:40.481 com.apple.xpc.launchd[1]: (com.housetrip.Trailer.Launcher[45028]) Could not find and/or execute program specified by service: 155: Refusing to execute/trust quarantined program/file: com.housetrip.Trailer.Launcher

9/20/20 16:14:40.500 com.apple.xpc.launchd[1]: (com.housetrip.Trailer.Launcher) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
```

**Comment by ptsochantaris** [comment]
Aha, those two new errors are related. One basically is the problem and the other is the side-effect (the launcher helper trying to launch the main app and failing)

The issue here is the old-style lifetime of network data tasks on older iOS and macOS releases, if a data task is deallocated before Trailer is through observing it then in newer OSes the observation is auto-removed, but in older OSes the app had to manually ensure the observation was removed first.

My 10.11 VM is still downloading :) so please accept my apologies for using you as a test guinea-pig in the meantime, but can you try this build now and see if things improve?

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/5252551/Trailer.zip)

**Comment by Amorymeltzer** [comment]
Looks great!  Everything seems in full order as far as I can tell, picked up all my preferences and is workin' like a charm.

And no worries at all @ptsochantaris, glad to help out for an excellent product — it can't be easy to support something half a decade and five update cycles old!

**Comment by ptsochantaris** [comment]
Fantastic!

I'll be sure to put out an update with this fix, as well as some other bothersome things which I managed to miss that were reported by beta testers too. Thanks again for reporting this and let me know if you run into any other issues!

**Comment by ptsochantaris** [comment]
Hi, I'm closing this issue as the update with the fix is now live, but please feel free to reopen or create a new issue if you spot any issues or have any more suggestions about this. Thanks again for spotting and reporting it!
