### ISSUE TITLE
Closed Pull Requests are no longer shown

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#413]
Closed PRs are now no longer shown.  I don't know if this is a regression in 1.7.0 or 1.7.1.  Using v3 API.

**Comment by ptsochantaris** [comment]
It's very possible this is a regression in v3 API. Thanks for reporting, will look into it asap.

**Comment by ptsochantaris** [comment]
Hi @cgatesman and thanks again for spotting this. Can you try this build out? It should hopefully correct this issue and also #415 as well. If all is good I'll put out a general update.

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/5281932/Trailer.zip)

**Comment by cgatesman** [comment]
Running it now.  #415 seems fixed.  Will have to wait for a PR to get closed (hopefully today), and I'll let you know, here.  Thanks for the quick turnaround!

**Comment by cgatesman** [comment]
@ptsochantaris, fix is good on both issues! 🎉

**Comment by ptsochantaris** [comment]
Great stuff, thanks a lot for reporting and testing @cgatesman - I'll wrap up some other changes and put out an update very soon 👍

**Comment by cgatesman** [comment]
@ptsochantaris I may have spoke too soon.  This may have caused a regression.  Using v4 API, now, I do not see a `CONFLICT` flag on non-mergable PRs with the new option turned on.

**Comment by ptsochantaris** [comment]
Hi @cgatesman - I don't think it has, as I'm seeing conflicting PR badges on items on my lists. Additionally I double-checked that the codepath where I made this fix was touched only by v3 syncing code, so there is no way it could have influenced v4 API code. However I never rule out come weird corner case :) Can I ask you to try a "reload all data" from the "misc" menu in prefs to see if this isn't some glitch in the items from when the v3 API sync was causing trouble?

**Comment by cgatesman** [comment]
It might be a while till I have another conflict.  I'll keep my eyes pealed, though.

**Comment by cgatesman** [comment]
@ptsochantaris I have a PR, today with a conflict.  The UI does not show CONFLICT.  I am using v4 API with "Mark non-mergeable PRs" checked.  I also did a Reload All Data, and that didn't seem to fix the problem, either.  FWIW, I am seeing this problem with both the latest release, and the pre-release you posted in this Issue.  The PR is for a private repository, so, I'm sorry, I can't share a link to it, in here.

**Comment by ptsochantaris** [comment]
Hi @cgatesman, the only permissions I have enabled for my token are the ones you see checked below, i.e. all the "repo" ones and the "read:org" ones. It's very strange that you are not receiving this flag on your end though.

One thing you can try is to enable both logging options in "Misc" and see what data is being returned by the API. It may be a bit messy, but you can probably search for your PR's title for instance, and from there you can see what value it's providing for the `mergeable` field (or even if it's present). Let me know how it goes.

<img width="682" alt="Screenshot 2020-10-06 at 18 59 59" src="https://user-images.githubusercontent.com/521581/95241757-2516a880-0806-11eb-895a-f35ad91c0dbe.png">

**Comment by cgatesman** [comment]
Here is the node in question from the REST response (sensitive data X'ed out):

```json
{
  "node": {
    "__typename": "PullRequest",
    "id": "MDExOlB1bGxSZXF1ZXN0NDk1Njc3NDk3",
    "bodyText": "XXXXX",
    "state": "OPEN",
    "createdAt": "2020-09-30T17:49:47Z",
    "updatedAt": "2020-10-06T15:03:39Z",
    "number": 5026,
    "title": "XXXXX",
    "url": "XXXXX",
    "milestone": {
      "__typename": "Milestone",
      "title": "Release v4.4.3"
    },
    "author": {
      "__typename": "User",
      "id": "MDQ6VXNlcjYyNzYwNzI=",
      "login": "cgatesman",
      "avatarUrl": "https://avatars3.githubusercontent.com/u/6276072?u=76bed3557970c225d14eab05762e2389dc0f9fe6&v=4"
    },
    "assignees": {
      "edges": [],
      "pageInfo": {
        "hasNextPage": false
      }
    },
    "labels": {
      "edges": [],
      "pageInfo": {
        "hasNextPage": false
      }
    },
    "headRefOid": "fec6994880cdee53469307e2ae02d1e3dcb29bb8",
    "mergeable": "CONFLICTING",
    "additions": 17,
    "deletions": 1,
    "headRefName": "cg-5012",
    "isDraft": false,
    "mergedBy": null
  },
  "cursor": "Y3Vyc29yOnYyOpK5MjAyMC0xMC0wNlQxMTowMzozOS0wNDowMM4di3A5"
}

```

**Comment by cgatesman** [comment]
I'll have to try this another day, @ptsochantaris, as I'm busy with a release, today.  I'll let you know my findings, though!

**Comment by cgatesman** [comment]
I will say that I did just notice some weird behavior, now, and I don't know if that is part of this problem.  When I hover over entries in the Trailer dropdown, I'm seeing approvals/request changes change on PR entries.  It looks like when I hover over some, they're showing an old state of approvals/request changes, and when I'm not hovering over them, it's showing the latest state of the PR.

**Comment by ptsochantaris** [comment]
I've seen this in rare occasions, and I think that has to do with render surface caching by the system. It gets fixed if you restart the app IIRC. However I doubt this would be related to this issue, which I assume persists across restarts. Also, note to self: Need to look into that hover update glitch.

**Comment by cgatesman** [comment]
FWIW, I restarted the app and immediately tried the hovering, and it still occurs.

**Comment by ptsochantaris** [comment]
In that case you may have a corrupted database and/or may be running two trailer instances together perhaps. When you find some time, make sure there are no "Trailer" instances running on the system and nuke the data directory (you may want to export your settings first so you can quickly restore your setup) - it may help.

**Comment by cgatesman** [comment]
1. Exported settings
2. killall Trailer (only one was running)
4. mv ~/Library/Application\ Support/com.housetrip.Trailer /tmp
5. Started Trailer
6. Imported Settings

Hover glitch still occurs.  😞 

I'll have to wait for another conflict to see if that happened to fix that, though.

**Comment by ptsochantaris** [comment]
Ugh, this is demoralising 😆 Thanks for updating me 👍 I'll keep digging on the hover glitch. For some crazy reason this has to somehow link up with the conflict issue, must be some rendering problem...

**Comment by cgatesman** [comment]
I don't know how after blowing away the data directory, it could know about an old review state.  I have an item that is flipping from one person reviewing and another requesting changing to that second person approving the changes.  The requesting changes state is, obviously, an old state of the PR.  I can double check the response logs as I have a lot less PRs to sift through, right now.

**Comment by ptsochantaris** [comment]
This is what made me wonder about running two Trailer instances initially. I doubt you'd see the API provide any solution there, it feels more like the data directory is still handing around somehow, like being accessed by a zombie Trailer instance...?

**Comment by cgatesman** [comment]
I couldn't actually see where you were getting reviewer states from.  They're not in the nodes in the response data of graphql.

I'll try a good ol' fashion reboot.

**Comment by cgatesman** [comment]
Ok.  I may have some better news!

I rebooted, came back and the problem was still there.  So at a last ditch effort, I decided to kill Trailer, blow away the data directory then reboot.  System came up along with Trailer (on login), and I imported my settings.  And, now, I don't see the hover glitch!  I am hoping this corrects the CONFLICT issue...yet to find out on that one.

That's a weird one, for sure!

**Comment by ptsochantaris** [comment]
Encouraging! I have a feeling your system may be loading trailer twice, perhaps you have two copies set to "launch at login"? If so, you may want to delete any old or test copies, and check the login items in settings!

**Comment by cgatesman** [comment]
I definitely do not:

```
$ ps aux | grep Trailer
chad               502   0.0  0.4  4989264  67288   ??  S     9:34AM   0:06.52 /Applications/Trailer.app/Contents/MacOS/Trailer
chad              3357   0.0  0.0  4268300    700 s000  S+    9:45AM   0:00.00 grep Trailer
```

**Comment by cgatesman** [comment]
Just an update on this.  The changing reviewers on hover bug came back.  Unfortunately, we haven't had any conflicts in any PRs, yet, to see what the status of that issue is.

```
$ ps ax | grep -i trailer
  560   ??  S     34:27.34 /Applications/Trailer.app/Contents/MacOS/Trailer
 4062 s000  S+     0:00.01 grep -i trailer
```

**Comment by ptsochantaris** [comment]
Hi @cgatesman just to better help me track both issues, I'm going to close this issue, but please *do* open two respective issues for each bug and I'll look into them asap.

**Comment by cgatesman** [comment]
Sounds good, @ptsochantaris.  I felt bad that this issue kind of morphed into multiple things.  Currently, I'm not seeing issues (I never had a CONFLICT scenario up to now, though).  If I see any of my past reported issues again, I'll create a new Issue.  Thanks so much for your support! 👍
