### ISSUE TITLE
Mark non-mergable PRs shows CONFLICT when using v3 API

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#415]
When you have "Mark non-mergable PRs" enabled, it should do nothing if you are using v3 API.  Instead, it incorrectly  marks PRs as CONFLICT.

**Comment by ptsochantaris** [comment]
Hi @cgatesman , that feature is v4 API only I'm afraid. If you're using v3 API you should turn this option off.

<img width="277" alt="Screenshot 2020-09-23 at 10 11 42" src="https://user-images.githubusercontent.com/521581/93992212-2fa45d00-fd85-11ea-8531-94bb1f5f72be.png">

**Comment by cgatesman** [comment]
I understand that. I'm saying I would think the option should be pretty much a noop and do nothing if you're using v3, and you shouldn't see any side effects.
