### ISSUE TITLE
All closed PRs from repo show up regardless of Hiding filter

### ISSUE THREAD

**Issue by bsiegel** [ptsochantaris/trailer#419]
Using Trailer 1.7.2, I have the following configuration:
- Repo "A" set up with Pull Requests: Participated
- Other repos set up with Pull Requests: All
- When something is merged: Move any merged items to "Merged"
- When something is closed: Move any merged items to "Closed"

After updating to 1.7.0, all PRs that are merged or closed in repo "A" are being displayed in their respective sections even if I never participated in them - the "when something is merged" setting seems to override the repo configuration of "Participated".

Prior to 1.7.0, the repo configuration "Participated" seemed to override other display settings and this scenario worked correctly - a PR that was merged in repo "A" that I did not participate in never appeared in Trailer at all.

Is there any way to restore the previous behavior? I don't want to change the "When something is merged / closed" setting because I still need to see all merged or closed PRs in the other repos.

**Comment by ptsochantaris** [comment]
Hi @bsiegel and sorry for the very slow reply. This definitely sounds like a bug, will investigate!

**Comment by ptsochantaris** [comment]
The new update is now out and should correct this issue. Going to close it for now, but as always please feel free to re-open if there's more to do, or create new issues!
