### ISSUE TITLE
Menu bar items do not adapt to Big Sur's Dynamic desktop wallpaper

### ISSUE THREAD

**Issue by filliph** [ptsochantaris/trailer#422]
If I use the "Dynamic Desktop" wallpaper "Big Sur":
<img width="561" alt="image" src="https://user-images.githubusercontent.com/9424286/99146485-838a3e80-2670-11eb-96bb-28fd44f5d140.png">
And I open my computer early in the morning, Trailer does not adapt its icons like Docker does:
<img width="118" alt="image" src="https://user-images.githubusercontent.com/9424286/99146474-6ce3e780-2670-11eb-9e4e-ed258074408c.png">
My Appearance setting is set to Dark. I'm using v1.7.2 (1570).

**Comment by ptsochantaris** [comment]
Hi @filliph - I also spotted this yesterday and it kills me too :) Will be sure to fix it for the next update (assuming there is API for it) 👍

**Comment by filliph** [comment]
Can confirm this morning that this has been fixed in the latest release, thanks!

**Comment by ptsochantaris** [comment]
Awesome, thanks for verifying! Let me know if you spot any more issues in Big Sur (or in general)
