### ISSUE TITLE
Error Authenticating: Server did not respond

### ISSUE THREAD

**Issue by pnarielwala-tc** [ptsochantaris/trailer#424]
Hello!

I'm running into an issue connecting to my github accounts getting the following error:
![Image 2020-12-10 at 1 30 57 PM](https://user-images.githubusercontent.com/37671065/101814331-ff4e9e00-3aeb-11eb-8f0a-9d9bb38c85a5.jpg)

Not sure how to see the API calls to get information on what's going on (tried using Charles Proxy). 

Any help would be appreciated and love this app, thanks!

**Comment by pnarielwala-tc** [comment]
Running the following in my terminal works though
```
$ curl -i -H "Authorization: token <GITHUB_TOKEN>" https://api.github.com/user/repos
```

**Comment by pnarielwala-tc** [comment]
Happens with v1.7.4, but works on v1.7.2

**Comment by ptsochantaris** [comment]
Hi, no clue how I managed to miss this report, sorry for not responding sooner. Are you still having this issue?

**Comment by stackptr** [comment]
@ptsochantaris Github sent out emails earlier in April urging users to regenerate tokens (explained in this [blog post][1]). I get the above error when using a token, though it looks like the name of the API server is omitted:

<img width="372" alt="Screen Shot 2021-04-11 at 4 52 23 PM" src="https://user-images.githubusercontent.com/4542907/114325695-4b374100-9ae6-11eb-8fbb-2811d1b0c186.png">

If I revert to my earlier, working token, I get the same error, so it's unclear if the token itself is the issue or something else. The tokens both show the `repo` and `read:org` permissions, and the API paths are unchanged / look right to me:

<img width="992" alt="Screen Shot 2021-04-11 at 4 53 51 PM" src="https://user-images.githubusercontent.com/4542907/114325733-80439380-9ae6-11eb-9a05-4e326b36d3a5.png">

[1]: https://developer.github.com/changes/2021-04-05-behind-githubs-new-authentication-token-formats

**Comment by stackptr** [comment]
Trailer seems to be working with that updated token, fyi.

**Comment by ptsochantaris** [comment]
Thanks for the update @stackptr, my feeling is that most probably the endpoint that the test option uses may not work anymore. I haven't had much time to work on Trailer as I would have liked recently, but I'll be sure to look at that when I do. As long as Trailer works otherwise, then that's fine.
