### ISSUE TITLE
Please put trailer's status popup window at a higher level

### ISSUE THREAD

**Issue by danwood** [ptsochantaris/trailer#425]
Unlike iStatMenus, which has its custom status bar window popup at a higher level (NSWindow.Level.mainMenu or 
NSWindow.Level.statusBar), trailer's status bar window is apparently 3, NSWindow.Level.floating, which conflicts with a floating window in the software I'm working on.

Using this reference of window levels …
    https://jameshfisher.com/2020/08/03/what-is-the-order-of-nswindow-levels/

Can you set a higher window level please?

**Comment by ptsochantaris** [comment]
Hi, I'll be closing this issue as v1.7.6 is now up and includes this amongst other changes. If you encounter any problems with it, please feel free to open a new issue.
