### ISSUE TITLE
Feature Request: Saved/persisted filters

### ISSUE THREAD

**Issue by kamranayub** [ptsochantaris/trailer#428]
I love the filtering capability but don't love how it seems to disappear sometimes or that I have to remember to type them in. 

Since you cannot add a filter expression in the Repository view, it would be nice to have "saved views" that persist a filter. For example, when triaging PRs, I prefer to hide things I don't have to take action on so I use `state:unread`. Having the ability to see this in a dedicated dropdown item would be ideal.

![image](https://user-images.githubusercontent.com/563819/109328226-d605fa00-781e-11eb-8d2c-1d8c0f59dfe9.png)

Similarly, for issues, I don't want to see issues I've created necessarily, I only want to see ones assigned to me because I have to take action on them, so I use `assignee:kamranayub`.

![image](https://user-images.githubusercontent.com/563819/109328211-d0a8af80-781e-11eb-9185-15a2315155ad.png)

**Comment by ptsochantaris** [comment]
I really like the idea of persisting the filters and have thought about it for a while, but decided that it's worth waiting until someone else asks for it too, and here we are :) Adding to the TODO list!

Incidentally, for your first scenario there is the `Only display items with unread badges` option in settings - although admittedly that is app-wide, not status-item wide.

On the assignee front, there's no corresponding option indeed - but then that's what filters are for, but it's annoying if they're not persisted like you point out in the first place. :)

Stay tuned.

**Comment by ptsochantaris** [comment]
Hi, I'll be closing this issue as v1.7.6 is now up and includes this amongst other changes. If you encounter any problems with it, please feel free to open a new issue.
