### ISSUE TITLE
Feature Request: Filter/Hide PRs I approved

### ISSUE THREAD

**Issue by kamranayub** [ptsochantaris/trailer#429]
When triaging PRs, I don't need to take any more action once I approve a PR. They could move to Participated or I could hide them. I only want to see PRs that I have to pay attention to so it'll come back into "Mine" when my review is dismissed or if someone re-requests a review. If there was a filter for this, that is fine. An option in the Reviews tab to configure this would also work.

In our workflow, we need two approvers on a PR, being able to filter out PRs with N approvals would be nice-to-have too. Right now, it will keep it Mine until it's merged but I don't really want to see it in the list if I don't have to pay attention to it. 

At the moment I can filter by `state:unread` and then Mark as Read to workaround this.

**Comment by kud** [comment]
Yeah I could like somethingmlike this too, please.

**Comment by ptsochantaris** [comment]
Hi, sorry for the slow pace of comms recently :) This does make a lot of sense, adding to the TODO list. I would imagine that if someone re-requests a review after the approval you'd want the item to show up again - but happy to hear any arguments against that if you disagree :)

**Comment by ptsochantaris** [comment]
Hi, this build should have this feature now. You can find two new checkboxes in the "reviews" preference tab which can optionally hide PRs which are approved or rejected (or both :))

If you get a chance to try it out, and encounter issues, have thoughts or have suggestions they'd be very welcome.

[Trailer-185-1681.zip](https://github.com/ptsochantaris/trailer/files/12217172/Trailer-185-1681.zip)

**Comment by ptsochantaris** [comment]
Hi, this feature is now in the 1.8.5 release: https://github.com/ptsochantaris/trailer/releases/tag/1.8.5 - I'm going to close this issue for now, but please feel free to re-open, or open a new issue if you continue to experience this or other issues.
