### ISSUE TITLE
UI issue: Top of app hidden when mac autohide menu bar is enabled

### ISSUE THREAD

**Issue by robichaudc** [ptsochantaris/trailer#431]
A small amount of top padding would probably solve the issue

![Screen Recording 2021-03-15 at 04 54 56 PM](https://user-images.githubusercontent.com/31775963/111220221-48acfe80-85af-11eb-9ba8-68d3178da621.gif)

**Comment by ptsochantaris** [comment]
Hi, I'll be closing this issue as v1.7.6 is now up and includes this amongst other changes. If you encounter any problems with it, please feel free to open a new issue.
