### ISSUE TITLE
Token permissions

### ISSUE THREAD

**Issue by 99** [ptsochantaris/trailer#432]
Hi,

Thank you for developing this great app. 
I couldn't find this in documentation or README. But it would be helpful to define what kind of scopes the GH token will require for this to work.

**Comment by filliph** [comment]
I had the same question, found this old comment: https://github.com/ptsochantaris/trailer/issues/237#issuecomment-186244013

Would be great if the readme could be updated :)

**Comment by damsleth** [comment]
I copied the scopes specified in #237, but the v4 endpoint still didn't work.
Seems the v4 (graphql) endpoint needs more permissions, specifically [as per the github docs](https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#authenticating-with-graphql)

```
user
public_repo
repo
repo_deployment
repo:status
read:repo_hook
read:org
read:public_key
read:gpg_key
```

Pasted my own Trailer PAT scopes below for easier reference

![image](https://user-images.githubusercontent.com/7300548/118982948-35862880-b97c-11eb-9995-1d00ad02149c.png)

**Comment by ptsochantaris** [comment]
Hi, for what it’s worth my settings are exactly what the text in the app specifies, i.e. read:org and all the repo settings. I use v4 api, but those were the settings used in the v3 api as well. If you find that you need additional permissions for certain items to appear, please do let me know so I can update the descriptions in the app!

![public-jpeg](https://user-images.githubusercontent.com/521581/119226861-18c82d00-bb03-11eb-851f-eea475ccfc0c.jpeg)
