### ISSUE TITLE
Setting a new token removes all assigned repository group names & show/hide settings

### ISSUE THREAD

**Issue by cgatesman** [ptsochantaris/trailer#433]

**Comment by Odaeus** [comment]
Can confirm, now GitHub is telling us to update our tokens to a new format. I tried to import a backup but that resets to the old token which doesn't work any more. I guess a workaround would be to edit the backup file to replace the token.

**Comment by cgatesman** [comment]
> Can confirm, now GitHub is telling us to update our tokens to a new format.

How do you think I ran into this issue? 😉

**Comment by ptsochantaris** [comment]
Hi guys. Yes, resetting the GitHub token is a horror from the days when Trailer was a tiny little utility, and it just nuked everything to keep things clean. Obviously by now this functionality is _way_ overdue for a fix, and will add this on the (slow moving, I hate to admit, PRs welcome) TODO list. TemporarilyI would strongly recommend just editing it manually as @Odaeus mentioned.

**Comment by cgatesman** [comment]
Completely understand, and I can see how this particular issue wouldn't be as high of priority.  Thanks!

**Comment by ptsochantaris** [comment]
Hi! V1.4.5 is now up with minor fixes, amongst which is this one. Hopefully it makes your life a bit easier. Let me know if you run into issues.

**Comment by dnicolacopoulos** [comment]
Hi!
I still have this issue even with v1.7.5.
After I regenerated the token as instructed by Github, I lost all my saved repos I was watching and can't seem to get them back...
I'm not sure I can find a backup and how to edit as @Odaeus mentioned. Can you please provide mode details?
Thanks!

**Comment by ptsochantaris** [comment]
Hi @dnicolacopoulos, that sounds more like a token permission issue rather than Trailer deleting the local data cache. Check that your new token has the required permissions (all the repo permissions and read:org permission). If you want to keep backups of your Trailer config, you can do it from the Misc tab in preferences, but there are no auto backups made by default.

**Comment by dnicolacopoulos** [comment]
Hi @ptsochantaris 
I realized I had to re-enable SSO after the token was regenerated..Once I did that, I got my repos back. 👍

**Comment by ptsochantaris** [comment]
Great stuff, thanks for the update @dnicolacopoulos - I'll note that down as a new requirement then, perhaps to add it in the requirements description for the auth token 👍

**Comment by bshega-godaddy** [comment]
@dnicolacopoulos Thank you, I ran into this same thing and that fixed!
