### ISSUE TITLE
Menu bar item changes placement on its own

### ISSUE THREAD

**Issue by elainemckinley** [ptsochantaris/trailer#434]
Hi there! Been using trailer for a while and love it, great way of staying on top of WIP.

I've had an issue recently where the menu bar item seems to change where it's placed on my bar. I use an app called Dozer, which hides some unused icons, and Trailer seems to be putting itself into the hidden section to the left. Is there logic within Trailer that moves the menu bar icon itself? And if so how can I turn that off?

I'm on macOS Big Sur, and don't believe this to be a problem with Dozer (I have other menu bar apps not affected by this, and have recently reinstalled macOS and both apps).

**Comment by klundberg** [comment]
I'm also seeing this, on macOS 11.3. Whenever it refreshes its data it seems to shift to the leftmost position on the menubar for some reason for me.

**Comment by hyunjinjeong** [comment]
Same here. It would be great if the menu bar icon doesn't move on refreshing.

**Comment by elainemckinley** [comment]
I'd like to mention for folks here that, fwiw, I haven't experienced this on version 1.7.5. Is that the same version y'all are on?

**Comment by hyunjinjeong** [comment]
I don't know why, but now it works fine for me 🎉 
I'm using Trailer 1.7.5 and macOS 11.4.

**Comment by ptsochantaris** [comment]
Hi, sorry for the very late response - I wanted to ask if this is still an issue, or if not, I could close it?

**Comment by elainemckinley** [comment]
I haven't experienced it in weeks, so would be content with it being closed :)
