### ISSUE TITLE
Feature Request: Allow to hide avatar on notifications only

### ISSUE THREAD

**Issue by kgrhartlage** [ptsochantaris/trailer#435]
I would like to keep avatars on the menu bar dropdown because they offer a quick way to identify the author and do not take away from other information. Notifications, however, have so much less real estate to display information that their information value is - in relative terms - greatly reduced when also showing avatars.
If adding a separate setting is not desirable, maybe always hiding avatars on notifications by default is an option.

Thank you for considering and making this app.

**Comment by ptsochantaris** [comment]
Hi! Sorry for the slow reply. This makes total sense. This pre-build of the next release should include this feature. If you get a chance, have a go with it and let me know if the new option (it's in Preferences next to the "main" option) does what you expect.

[Trailer.app.zip](https://github.com/ptsochantaris/trailer/files/6758948/Trailer.app.zip)

**Comment by ptsochantaris** [comment]
Hi, I'll be closing this issue as v1.7.6 is now up and includes this amongst other changes. If you encounter any problems with it, please feel free to open a new issue.
