### ISSUE TITLE
Simple way to migrate/share settings?

### ISSUE THREAD

**Issue by danmcmahill** [ptsochantaris/trailer#436]
Is there a simple way to migrate settings from one computer to another?  I have 3 basic use cases:

1.  Co-worker:  "trailer is awesome, you totally need to use it, here are my settings that you can import (minus github token)"
2.  Replacing computer with a newer one, I want to keep all of my settings.  If I have to put in my token again, that is ok.
3.  Maintaining a common setup between two different computers but the same user (me).  Not sure how this looks.  For things like `~/.bashrc` I use git with a bare repo to manage my dot files.  This way I have have the same basic feel on my different systems.

**Comment by ptsochantaris** [comment]
Hi @danmcmahill - the export/import settings function should cover what you need I think. Check it out on the "Misc" tab of preferences. Let me know if you run into problems.

**Comment by danmcmahill** [comment]
Thanks!  I somehow missed that one.
