### ISSUE TITLE
Confusing release note for `1.7.5` about "nuke all contents"

### ISSUE THREAD

**Issue by sheldonhull** [ptsochantaris/trailer#437]
Couldn't find resolved commits to explain what this meant.

```
Will not nuke all the contents of a server's repos if the auth token is modified
```

I recall setting my token to only reading workitems, so I'm not concerned too much on this, however it gave me pause and made me rotate my token to be safe. Mind updating the release notes on what "all contents of a servers's repos" refers to (assuming pending notifications?)

**Comment by ptsochantaris** [comment]
Hi, it just means that in the past if you edited an API server auth token it would clear all the contents from the server on Trailer, and you needed to re-configure the related repos from scratch, a leftover from the ancient days of Trailer. This is no longer the case, so the auth token can be replaced or edited without clearing local data.
