### ISSUE TITLE
Red X for Pull Requests when using Github v4

### ISSUE THREAD

**Issue by ajsharma** [ptsochantaris/trailer#439]
Firstly, thank you for such a great and useful application, I rely on it daily! 

For the actual issue report: 

On Trailer 1.7.5, I turned on Github v4, but all my pull requests disappeared and I started to see the Red `X` icon and no pull requests.

I turned on the console logs and see the following error message:

```
Field 'issues' doesn't exist on type 'Query'
```

might be the cause of the problem? 

![Screen Shot 2021-06-03 at 10 15 08 AM](https://user-images.githubusercontent.com/766658/120686185-93733f80-c455-11eb-830a-12b430561a9f.png)
 
 I've reverted to v3 and everything went back to normal and working, so I assume it's v4 specific.

**Comment by ptsochantaris** [comment]
Hi, interesting! Looks like a corner case with the generated GraphQL query. Could you possibly (temporarily) activate the logging API option from `Misc` and include a copy of the query here (please redact any confidential info if there is any) so I can take a look at the query that's failing?

**Comment by ajsharma** [comment]
Hi @ptsochantaris, sorry to disappear, thank you for your patience. 🙏 

I see a 

> Rolling back changes for failed sync on API server 'GitHub'

error, and then I get the Red `X` on my Trailer dropdown.

## Console output:
<img width="611" alt="Screen Shot 2022-03-25 at 10 06 49 AM" src="https://user-images.githubusercontent.com/766658/160168318-7d22b734-158a-4fd0-a6b6-4e18253f1b10.png">

## Github PR list
<img width="807" alt="Screen Shot 2022-03-25 at 10 03 28 AM" src="https://user-images.githubusercontent.com/766658/160168416-14c64af9-4f20-41a5-9581-e2c3425e0c32.png">


## Trailer PR list 
<img width="539" alt="Screen Shot 2022-03-25 at 10 02 45 AM" src="https://user-images.githubusercontent.com/766658/160168407-8e561b06-b490-45f6-abfd-f54b38d17155.png">


I'll try another `Reload All Data` with the API responses as well, but it'll take a little time for me to redact the secrets

**Comment by ajsharma** [comment]
From skimming for errors in the console logs:

```
0x0304) ciphersuite(TLS_AES_128_GCM_SHA256) group(0x001d) signature_alg(0x0403) alpn(h2) resumed(0) offered_ticket(0) false_started(0) ocsp_received(0) sct_received(0) connect_time(61ms) flight_time(30ms) rtt(15ms) write_stalls(0) read_stalls(2)]
default 10:11:20.345875-0700  Trailer nw_flow_connected [C4.1 IPv4#88241b56:443 in_progress socket-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] Output protocol connected
default 10:11:20.346029-0700  Trailer [C4.1 IPv4#88241b56:443 ready socket-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] event: flow:finish_connect @0.095s
error 10:11:20.346103-0700  Trailer nw_endpoint_handler_set_adaptive_read_handler [C4.1 IPv4#88241b56:443 ready socket-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
error 10:11:20.346230-0700  Trailer nw_endpoint_handler_set_adaptive_write_handler [C4.1 IPv4#88241b56:443 ready socket-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
default 10:11:20.346642-0700  Trailer nw_connection_report_state_with_handler_on_nw_queue [C4] reporting state ready
default 10:11:20.346735-0700  Trailer [C4 Hostname#167b8528:443 ready resolver (satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns)] event: flow:finish_connect @0.096s
default 10:11:20.346808-0700  Trailer [C4.1 IPv4#88241b56:443 ready socket-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] event: flow:changed_viability @0.096s
default 10:11:20.346857-0700  Trailer [C4 Hostname#167b8528:443 ready resolver (satisfied (Path is satisfied), interface: en0, ipv4, ipv6, dns)] event: flow:changed_viability @0.096s
default 10:11:20.346935-0700  Trailer Connection 4: connected successfully
default 10:11:20.346972-0700  Trailer Connection 4: TLS handshake complete
default 10:11:20.347093-0700  Trailer Connection 4: ready C(N) E(N)
default 10:11:20.347348-0700  Trailer Task <D45430F6-CAA1-4D7F-B93F-C4F32172EB1D>.<108> now using Connection 4
```

and later 

```
default 10:11:24.559834-0700  Trailer Status update: GitHub: Open Issues
default 10:11:24.560045-0700  Trailer API data from https://api.github.com/graphql: {"errors":[{"path":["query","issues"],"extensions":{"code":"undefinedField","typeName":"Query","fieldName":"issues"},"locations":[{"line":1,"column":802}],"message":"Field 'issues' doesn't exist on type 'Query'"},{"path":["fragment issueFragment"],"extensions":{"code":"useAndDefineFragment","fragmentName":"issueFragment"},"locations":[{"line":1,"column":357}],"message":"Fragment issueFragment was defined, but not used"}]}
default 10:11:24.560286-0700  Trailer (GQL 'Authored Items') Received page (No stats)
default 10:11:24.560559-0700  Trailer (GQL 'Authored Items')  Error: Failed with error: 'Field 'issues' doesn't exist on type 'Query''
default 10:11:24.560707-0700  Trailer [Telemetry]: Activity <nw_activity 12:2 [EB385C7F-E81C-4843-A5EE-6C437D4E06CD] (reporting strategy default)> on Task <88643A25-2020-467D-8171-15B69267EE36>.<125> was not selected for reporting
default 10:11:24.561489-0700  Trailer Task <88643A25-2020-467D-8171-15B69267EE36>.<125> {strength 0, tls 4, ct 0, sub 0, sig 1, ciphers 0, bundle 0, builtin 0}
default 10:11:24.561680-0700  Trailer Task <88643A25-2020-467D-8171-15B69267EE36>.<125> now using Connection 4
default 10:11:24.562042-0700  Trailer Task <88643A25-2020-467D-8171-15B69267EE36>.<125> sent request, body S 890
default 10:11:25.518142-0700  Trailer Task <88643A25-2020-467D-8171-15B69267EE36>.<125> received response, status 200 content U
default 10:11:25.521400-0700  Trailer Task <88643A25-2020-467D-8171-15B69267EE36>.<125> done using Connection 4
default 10:11:25.521619-0700  Trailer Task <88643A25-2020-467D-8171-15B69267EE36>.<125> response ended
default 10:11:25.521697-0700  Trailer Task <88643A25-2020-467D-8171-15B69267EE36>.<125> summary for task success {transaction_duration_ms=960, response_status=200, connection=4, reused=1, request_start_ms=0, request_duration_ms=0, response_start_ms=957, response_duration_ms=3, request_bytes=970, response_bytes=9451, cache_hit=1}
default 10:11:25.522080-0700  Trailer Task <88643A25-2020-467D-8171-15B69267EE36>.<125> finished successfully
```

**Comment by ptsochantaris** [comment]
Very interesting, looks like a bug when querying items which you have authored, in repositories outside the list… noting down the error in the log to dig into it. For the moment I would suggest disabling that option to see if it fixes things.

**Comment by ajsharma** [comment]
Maybe a case where I was previously in an organization but have since left? 

I'm currently away from that computer, but will try when I get back to it next week.

**Comment by ptsochantaris** [comment]
If you're still having this issue, please give the new beta a try in case it improves things, as there's been quite a bit of code cleanup: https://github.com/ptsochantaris/trailer/pull/468

**Comment by ptsochantaris** [comment]
The new update is now out and corrects various issues - given the quiet I'm going to assume the issue has been corrected. Going to close it for now, but as always please feel free to re-open if there's more to do, or create new issues!
