### ISSUE TITLE
Could not refresh repository list

### ISSUE THREAD

**Issue by hampgoodwin** [ptsochantaris/trailer#440]
Hello!,
I'm getting an issue in Trailer where I'm unable to refresh the repository list from GitHub when rescanning.

`Could not refresh repository list from GitHub, please ensure that the tokens you are using are valid`

![image](https://user-images.githubusercontent.com/17371239/123664551-aaa71200-d7f4-11eb-8132-e224ee969f3c.png)

It suggests I validate that the tokens I am using are invalid, yet when I test in the `servers` tab, I get a successful test. I've also tried changing the PAT access rules to have much more than should be required, and it still fails.

![image](https://user-images.githubusercontent.com/17371239/123664962-14272080-d7f5-11eb-8497-11e4f1026d01.png)

Note I have tried this on github v4 and github v3 api's.

What other information can I get to you to help with this issue?

**Comment by ptsochantaris** [comment]
Hi @hampgoodwin - this feels very much like a permission issue TBH, can you check if you have provided the needed permissions to the auth token which you have generated? See this thread: https://github.com/ptsochantaris/trailer/issues/432
