### ISSUE TITLE
Repositories preferences: rightmost column heading is cut off

### ISSUE THREAD

**Issue by TallGirlVanessa** [ptsochantaris/trailer#444]
This column is cut off so all it says is a mysterious "F..."

<img width="956" alt="Trailer_Preferences" src="https://user-images.githubusercontent.com/103690/129262332-5ba83785-c52b-4c80-9d2f-318081ee5229.png">

 I tried disconnecting my mice to get rid of the scrollbar. The issue persisted.

<img width="966" alt="Trailer_Preferences" src="https://user-images.githubusercontent.com/103690/129262640-9dd59177-015e-49eb-8a4c-d129ff4bb72c.png">

I found out through the source that this is supposed to be "Fork".

**Comment by ptsochantaris** [comment]
Whoops, thanks for spotting that, will fix it up!

**Comment by idrougge** [comment]
Also, the columns can't be adjusted for size or rearranged.

**Comment by ptsochantaris** [comment]
That whole view can use a bit of a facelift indeed :) PRs always welcome, or I’ll dig into it in a while.

**Comment by ptsochantaris** [comment]
Sorry for taking forever to look into this. The recent beta should hopefully improve things. If you get a chance to try it out and see, you can find it here: https://github.com/ptsochantaris/trailer/pull/468

**Comment by ptsochantaris** [comment]
The new update is now out and should correct this issue. Going to close it for now, but as always please feel free to re-open if there's more to do, or create new issues!
