### ISSUE TITLE
The application "Trailer" can't be opened.

### ISSUE THREAD

**Issue by yuanstanley** [ptsochantaris/trailer#449]
I tried installing Trailer, it seemed like it was having issues and not opening properly after I set my preferences, so I deleted the Application and re-downloaded it. When trying to run it the second time, I hit this 

> The application "Trailer" can't be opened. -47

![image](https://user-images.githubusercontent.com/6366221/140408484-3a6a8715-f440-462a-96fd-7e90bb689e4c.png)

I tried looking to see if it was a corrupt cache or something but in `Application Support` I don't have the `com.housetrip.Trailer` directory at all.

**Comment by ptsochantaris** [comment]
Sorry I realise that by the time I write this, you will have solved this or stopped caring :) But this isn't a Trailer error I'm afraid, it seems to come from macOS. Possibly permission issue? A disk check may help!

**Comment by ptsochantaris** [comment]
Hi, going to close this for now, but please feel free to re-open if this is still a problem for you.
