### ISSUE TITLE
Possible performance issues

### ISSUE THREAD

**Issue by jblejder** [ptsochantaris/trailer#451]
I just want to flag a possible performance issue that makes me want to drop using trailer on macOS.
Was hoping to see if other people have similar experience.

Using Macbook Pro 16-inch intel i9 64Gb ram

Standard software engineering setup. Just an Intellij running, chrome, some music.
I've noticed my laptop is often spinning fans at 100% showing 99&deg;C temp even when I do almost nothing.
And eventually I've noticed killing Trailer.App usually helps.

From monitoring it for a moment I seen huge spike in power usage. And eventually turned our Not responsive and then recovered.
So I assume this happens much more often.
![Screen Shot 2022-01-21 at 3 42 39 pm](https://user-images.githubusercontent.com/17861372/150467329-9dafdb9f-6058-40bd-aca9-1488b8bfabc1.png)

It usually sits quite close to Intellij
![Screen Shot 2022-01-21 at 3 33 20 pm](https://user-images.githubusercontent.com/17861372/150467482-e5327df6-b918-4800-bdd0-ae8b8564dbac.png)

**Comment by ptsochantaris** [comment]
Hi, and sorry for taking ages to reply. Thanks for filing this issue, Trailer UI performance was definitely a big issue.

You may like 1.8.0 which has just been released, which includes a lot of work to specifically work around these hitches that take a while when Trailer is syncing a lot of items (it wasn't originally designed to sync as much data as people use it for these days :))

Could you give the latest release a go and see if it improves things for you? Many of the non-responsive pauses should have improved by a lot, but please do let me know if you still encounter them.
