### ISSUE TITLE
status items filter only looks at status description, not context

### ISSUE THREAD

**Issue by leohemsted** [ptsochantaris/trailer#452]
I'd quite like to be able to exclude PR status items from trailer based on the context (ie: who/what sent them). Right now the filter only works with the description (ie: what the pr status message says).

Specifically I'd quite like to a known flakey PR status check that we're currently ignoring (solving that is a separate issue lol)

The filtering code is here and I think would be simple enough to modify to look at context as well: https://github.com/ptsochantaris/trailer/blob/e3c24b8378d1a72212f52f9ca0a5593f229611d8/Shared/PullRequest.swift#L310-L312

I'm not sure if that would affect existing users workflows (well, it surely _could_, but would it be an issue) or if there are other consequences that I'm missing?

**Comment by ptsochantaris** [comment]
Hi, sorry for the slow reply - can you be a bit more specific? E.g. when you say "context" what do you mean - can you provide an example?
