### ISSUE TITLE
Question: OR / AND filtering?

### ISSUE THREAD

**Issue by kamranayub** [ptsochantaris/trailer#453]
Sorry to open an issue for this, but I searched (and there is a lack of docs I think generally?) for this beforehand.

I am trying to do an "OR / AND" filter like

```
assignee:kamranayub OR labels:my-team-label AND status:unread
```

So I can filter both the `Mine` and `Participated` groups down. `Participated` is a bit too aggressive by default for monorepos (see some of the other issues I've opened, like #429) and it would be nice to support OR'ing filters to get just to what we really need.

Aside: could be useful to enable Discussions feature in this repo to collect questions / community support 😄

**Comment by ptsochantaris** [comment]
Hi! Yes, you're right, filtering is "and" only for now. Things that get ORed are the items in each category - for example `label:a,b status:unread` will show all unread times with labels containing `a` or `b`. What you describe sounds much more like Spotlight-style queries that didn't exist way back in the ancient times when Trailer got started, but I can definitely see the utility I what you suggest. I'll keep the issue open for now and revisit this. Sorry for the very slow reply BTW, I've been away from this project for ages.

PS there's a beta that could definitely use some testing if you're feeling adventurous: https://github.com/ptsochantaris/trailer/pull/468
