### ISSUE TITLE
API v4 on GHE doesn't show PR CI / statuses

### ISSUE THREAD

**Issue by stembrain** [ptsochantaris/trailer#454]
I have the v3 and v4 API set up for my server. If I check the `use GitHub v4 API` box and reload all the data, the CI statuses don't show. They show as expected if I call v3

I have logging turned on in trailer, but I can't find the logs in Console.app. Any hints on where those are might let me dig a bit deeper. Maybe the GraphQL call isnt getting the CI statii ?

**Comment by ptsochantaris** [comment]
Statuses may not show after the first sync but should show on subsequent syncs. If you are still experiencing this issue could you give the latest beta a try? https://github.com/ptsochantaris/trailer/pull/468

**Comment by ptsochantaris** [comment]
The new update is now out and includes changes to greatly improve CI/status syncing. Going to close it for now, but as always please feel free to re-open if there's more to do, or create new issues!
