### ISSUE TITLE
Filtering out comments from github-actions does not seem to work

### ISSUE THREAD

**Issue by jornetsimon** [ptsochantaris/trailer#455]
<img width="1056" alt="Screenshot 2022-03-29 at 09 33 11@2x" src="https://user-images.githubusercontent.com/936101/160558177-58e538de-d766-4acc-9db6-5eb3aea8e6dd.png">

Maybe because it's a bot?

**Comment by benjaffe** [comment]
same issue here... it makes the badges not very helpful, since my build process spams me a few times during each build

By the way, this is a life-changing app <3

**Comment by ptsochantaris** [comment]
Hi! Sorry for not replying for ages, I've been away from this project for far too long. I strongly smell a bug where the `-` isn't being filtered correctly in the app. Making a note to look into this as I work on the latest beta (which you can find here BTW: https://github.com/ptsochantaris/trailer/pull/468 in case you want to take a look)

**Comment by ptsochantaris** [comment]
Hi, can you give version 1.8.1 a try to see if it corrects this issue?

**Comment by jornetsimon** [comment]
Looks like it works properly now 👍
