### ISSUE TITLE
Display of base and head branches hides repository names

### ISSUE THREAD

**Issue by Jeff-Walker** [ptsochantaris/trailer#457]
When I check "Show repository names", I see the repository in the PR list. When I click on "...including base & head branches", the repository name goes away. I hope these screenshots are clear enough. The top one you can see that RxBenefits/rxb-billing-service is displayed and below that RxBenefits/rxb-claim-import-service, but on the bottom they look the same so I can't tell the difference.

![image](https://user-images.githubusercontent.com/1640710/175382298-2843a86f-b584-488d-8112-acf36e00de8e.png)

![image](https://user-images.githubusercontent.com/1640710/175382688-ec46635d-7b07-4a56-938c-b060684cb7e5.png)

But,

![image](https://user-images.githubusercontent.com/1640710/175382946-f60ad745-70f2-49ca-a879-407c1247086b.png)

![image](https://user-images.githubusercontent.com/1640710/175382830-52a7e5bd-83a4-4d20-9dad-8b3cb15b3581.png)

**Comment by ptsochantaris** [comment]
Hi and sorry for the very slow comms - This is definitely a good reason to still show the repo there. Adding this to the TODO list.

**Comment by ptsochantaris** [comment]
Hi this build should contain this correction - but to make sure I've fixed it properly, could you give it a try and let me know if it has improved things for you?

[Trailer-185-1682.zip](https://github.com/ptsochantaris/trailer/files/12221721/Trailer-185-1682.zip)

**Comment by Jeff-Walker** [comment]
It looks good to me. Thanks for working on this.

**Comment by ptsochantaris** [comment]
Whoops I missed closing this issue a while back, will close it now. Thanks for reporting the issue! Will close this issue now, but please feel free to open new issues related to this or other problems/suggestions.
