### ISSUE TITLE
Trailer cannot connect anymore due to old "Replication mode" site

### ISSUE THREAD

**Issue by mationic** [ptsochantaris/trailer#458]
I'm connecting to an GitHub Enterprise version. This GitHub was in replication mode one time. Now Trailer cannot connect anymore, even though the replication mode is off.

Testing the connection in preferences results in "The test failed for unsupported URL", scanning repositories results in no repos found. When I start dumping API responses and see that Trailer is still retrieving the "Server in replication mode" page. Using a browser or curl to connect to the API works fine. It looks like a caching issue..?
I have this problem for a week now.

**Comment by ptsochantaris** [comment]
I'm not too sure how best to help you with that issue. If you suspect a Trailer caching problem then you can nuke the trailer directory is `Caches`. If you want to make absolutely sure there is no caching issue going on you can try running it through a proxy and see what is coming back from the server vs what is being logged perhaps?

If you get a chance, there is a new beta up which has a lot of tweaks and improvements, so it may be worth trying if you get a chance: https://github.com/ptsochantaris/trailer/pull/468

**Comment by ptsochantaris** [comment]
Going to close for now as there doesn't seem to be activity on this issue - please feel free to re-open if you have more info on this.
