### ISSUE TITLE
Show wrong statuses for PR and Issue in the menu bar

### ISSUE THREAD

**Issue by t18n** [ptsochantaris/trailer#459]
![image](https://user-images.githubusercontent.com/14198542/178227156-85244a7d-e5d9-4761-a4b5-35b9d0f0eb96.png)

As you can see, the red `x` showed while all the PRs are `green`. I have muted 2 of the PRs that has conflicts as well. On the Issues one, none of the individual issues reflects the red `x`.

**Comment by ptsochantaris** [comment]
Sorry for the very slow reply. That red `x` means a sync issue with GitHub. Check the token you are using, and if you get a chance, you can try out the latest beta here: https://github.com/ptsochantaris/trailer/pull/468

**Comment by ptsochantaris** [comment]
Going to close this for now in the hope the latest beta has corrected this, but please feel free to re-open if that's not the case.
