### ISSUE TITLE
What is the unexpandable "F..." final tab in the Preferences window?

### ISSUE THREAD

**Issue by DiskImage** [ptsochantaris/trailer#461]
What the heck is this thing? I can see that it is a word that starts with an `F` character, and that it's too long for the space allocated, as well as that column being a boolean one... But the divider lines do not allow for expanding the columns, and there doesn't appear to be any sort of tooltip for the column header.

Is this `F for respect`?
![image](https://user-images.githubusercontent.com/1789383/178785979-0b1318ff-edd4-4531-8157-6fd61ef40fc1.png)

**Comment by zachwalton** [comment]
Was wondering the same thing and went looking, appears to be "Forked" https://github.com/ptsochantaris/trailer/blob/763c61c449dcd8622bc38234e7f7de2ddf9d2220/Trailer/PreferencesWindow.xib#L423

**Comment by awmottaz** [comment]
And what might "Forked" mean? Like I should mark whether the repo was forked from another one? How does that affect the notifications I see in Trailer?

**Comment by blalor** [comment]
Duplicate of #444.

**Comment by ptsochantaris** [comment]
The new update is now out and should correct this issue. Going to close it for now, but as always please feel free to re-open if there's more to do, or create new issues!
