### ISSUE TITLE
[Feature Request] Open repo url by clicking on it

### ISSUE THREAD

**Issue by kud** [ptsochantaris/trailer#467]
Hey,

In the `Repositories` tab, it could be great to be able to double click on the name of the watched repository to be able to go to Github easily.

Cheers,

**Comment by ptsochantaris** [comment]
Good idea, I think I've wanted something similar myself a while back 👍 Adding to the TODO list.

**Comment by ptsochantaris** [comment]
Hi, I have added this feature in this build as part of an improvement pass on the repositories list. If you get a chance to try it out let me know your thoughts and suggestions.

[Trailer-185-test4.zip](https://github.com/ptsochantaris/trailer/files/12210401/Trailer-185-test4.zip)

**Comment by ptsochantaris** [comment]
Hi, this feature is now in the 1.8.5 release: https://github.com/ptsochantaris/trailer/releases/tag/1.8.5 - I'm going to close this issue for now, but please feel free to re-open, or open a new issue if you continue to experience this or other issues.
