### ISSUE TITLE
Reduce Personal Access Token exposure

### ISSUE THREAD

**Issue by rahim** [ptsochantaris/trailer#470]
The Personal Access Token used by Trailer is somewhat sensitive given the broad permissions it requires.

At the moment the token is shown in the Preferences UI in the clear

<img width="1056" alt="Screenshot 2023-02-15 at 12 45 48" src="https://user-images.githubusercontent.com/14014/219033936-57e37e98-49c3-4622-a10e-b5c16d33ee2c.png">

And can be found on disk by anything with access to the files in the user's Library.

ie
```
$ sqlite3 ~/Library/Application\ Support/com.housetrip.Trailer/Trailer.sqlite 'SELECT ZAUTHTOKEN FROM ZAPISERVER;'
ghp_xxxxxxxxxxxxxxxxxxxxx
```

[Storing this in the user's Keychain](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_keychain) would keep this behind some level of access control and off disk in unencrypted form.

Obscuring the existing token in the Preferences UI until the user provided further authentication (eg TouchID) would further protect it.

**Comment by ptsochantaris** [comment]
You are totally right and this change is [long overdue](https://github.com/ptsochantaris/trailer/issues/158) - will add 👍

**Comment by ptsochantaris** [comment]
Here is a test build with this feature enabled. It should, in theory, migrate your token(s) to the keychain and remove them from the database, as well as hide them from the UI. You can always find the tokens in the Keychain. Note that this isn't quite polished yet - for instance if you deny Keychain access I suspect things will break :) But I wanted to get some feedback in the meantime if you find you have the time to test it out.

[Trailer-1692.zip](https://github.com/ptsochantaris/trailer/files/12317600/Trailer-1692.zip)

**Comment by ptsochantaris** [comment]
Ok, fixed ;) Sorry about that!

[Trailer-1692.zip](https://github.com/ptsochantaris/trailer/files/12317777/Trailer-1692.zip)

**Comment by ptsochantaris** [comment]
A fresh binary that won't auto-update when 1.8.7 is out shortly, because otherwise anyone using the above test build would lose their tokens :)

[Trailer-188.zip](https://github.com/ptsochantaris/trailer/files/12323297/Trailer-188.zip)

**Comment by rahim** [comment]
Thank you @ptsochantaris, this is great news. I'll test this out shortly and let you know how I get on.

**Comment by ptsochantaris** [comment]
Fantastic news - thanks for testing! I'll send this out as part of the next update 👍

**Comment by ptsochantaris** [comment]
Version 1.8.8 is now up and contains this feature. Will close this issue now, but please feel free to open new issues related to this or other problems/suggestions.
