### ISSUE TITLE
feature request: filter out issues by date

### ISSUE THREAD

**Issue by blalor** [ptsochantaris/trailer#471]
I'd like the ability to filter out issues/PRs that were last updated more than X days ago.  This would help me focus on items that have some recency.

**Comment by ptsochantaris** [comment]
Hi! You can do this in the "Snooze" section from preferences. On the bottom right you can select a number of days to do exactly what you describe: 

<img width="514" alt="Screenshot 2023-07-01 at 18 21 04" src="https://github.com/ptsochantaris/trailer/assets/521581/20c8a837-ef43-433d-ac59-adac351e96f7">

Have I understood your requirement correctly? Happy to discuss more!

**Comment by ptsochantaris** [comment]
Going to close this for now, but please do open a new issue or re-open this one if I didn't understand your question/request.
