### ISSUE TITLE
Trailer crashes when on GitHub enterprise (1.7.6 (121B))

### ISSUE THREAD

**Issue by jriverac** [ptsochantaris/trailer#474]
I have not gotten Trailer to work with our GitHub Enterprise instance. It just Crashes whenever I launch it. It used to work some time back, then it stopped, and for some time, I have been unable to see what is wrong. Is this a known issue with GHE? Are there logs I can look into?

**Comment by ptsochantaris** [comment]
Hi, you may want to remove the Trailer directory `com.housetrip.Trailer` from `Application Support` to reset everything. A new version is now up, please give that a try to see if things have improved at all. If you get a crash please post the crash log here and I'll try to take a look asap, thanks!

**Comment by ptsochantaris** [comment]
Hi, I'm going to close this for now, but please feel free to open a new issue if you are still experiencing issues.
