### ISSUE TITLE
TrailerLauncher Permission issue since recent updates

### ISSUE THREAD

**Issue by mcg** [ptsochantaris/trailer#482]
Using version 1.8.5(1688)

I have Trailer start on boot and am getting a dialog with `“Trailer” can’t be opened because TrailerLauncher is not allowed to open documents in Terminal` on boot now.

**Comment by ptsochantaris** [comment]
This sounds like a permissions issue on macOS, it seems to have "forgotten" about the permissions of the helper utility that launches it. Things to try:
- Unselect and re-select "launch at login" from trailer preferences.
- Try deleting the launch item entirely and repeat the above step :)

Let me know how this goes 🙏

**Comment by mcg** [comment]
Tried this to no effect, however I do not have a "Open at Login" item for Trailer, only a "Allow in Background" for 'Trailer.app". Selecting "launch at login" in Trailer doesn't seem to do anything, and it will not launch on login. Disabling the "Trailer.app" in "Allow in Background" does stop the permission error on login, but no Trailer starts.

**Comment by ptsochantaris** [comment]
Ah, I see it now, can reproduce! Thanks for reporting this, fixing!

<img width="720" alt="Screenshot 2023-08-11 at 16 28 28" src="https://github.com/ptsochantaris/trailer/assets/521581/3f5229e0-4e6b-40a0-bb6b-6d5ea7e253f4">

**Comment by mcg** [comment]
Still not sure the "start on login" does anything, but it now starts with the "Trailer" "Allow in background" enabled and no more permission error. Thanks for that fix so fast.

**Comment by ptsochantaris** [comment]
Ah, great to know, thanks for testing so quickly! I'll verify the "launch on login" setting as well soon, but I definitely wanted to fix this sooner rather than later as I'm sure it can be frustrating.

Thanks again for reporting this - I'll close the issue for now, but please do open more issues if you spot any regression or new problem!
