### ISSUE TITLE
Docs missing link

### ISSUE THREAD

**Issue by kamilpp** [ptsochantaris/trailer#483]
"Visit Trailer on Github" link does not work
![image](https://github.com/ptsochantaris/trailer/assets/26869324/520cd664-9b6f-4255-919e-2d4767e9ab11)

**Comment by ptsochantaris** [comment]
Oh whoops! Thanks so much for spotting this! I'll fix it up 👍

**Comment by ptsochantaris** [comment]
Fixed, thanks again!
