### ISSUE TITLE
v1.8.8 & 1.8.9 group PRs with my team as reviewer under "Mine" section

### ISSUE THREAD

**Issue by bazbremner** [ptsochantaris/trailer#486]
I've taken a comment originally posted by @BenRPeloton in https://github.com/ptsochantaris/trailer/issues/485#issuecomment-1690219428 as that issue has been closed, and I'm also noticing the same issue, which I believe is a bug.

With v1.8.8 and v1.8.9 (current release at the time of writing) PRs raised in repos with [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) configuration which automatically sets a team I'm a member of to be a required reviewer of those PRs causes Trailer to add those PRs to "Mine" immediately, seemingly regardless of the settings in Display -> "When something from "all items" is assigned..."

This behaviour does not occur with v1.8.7, which I've downgraded to.

BenRPeloton's original post follows:

 I'm noticing after the 1.8.8 update that all PRs with me or teams I'm in in the "Reviewers" field on a PR are all in the "Mine" section, where before it was only PRs that had me specifically assigned to them. My team does a lot of auto-assigning PRs based on teams and edited code, so this leads to a lot of noise. I didn't change any settings since the update, and My "When something from all items is assigned to me/ my teams" setting looks like it should work as I expect. 

<img width="913" alt="Screenshot 2023-08-23 at 11 52 17 AM" src="https://github.com/ptsochantaris/trailer/assets/48031214/cc71f587-b572-42cc-a654-d89a2621af83">

I only have one repository in the watched list and the Pull Request visibility for it is set to "Mine".

Is this a new bug introduced in this update, or am I just doing something wrong?

_Originally posted by @BenRPeloton in https://github.com/ptsochantaris/trailer/issues/485#issuecomment-1690219428_

**Comment by ptsochantaris** [comment]
Hi @bazbremner - Review assignments are handled in the `Reviews` section. The section in your screenshot refers to item assignments (e.g. when an issue is assigned to you or your team). Can you check if the setting in the `Reviews` tab is what you expect?

That said, I wouldn't be shocked if there's some bug, so I'm definitely up for investigating it if those settings are not doing what they're expected. It may help to look at the JSON data coming down for this PR to see if the related team info is showing up there. In case this is a public repo, or if you think you'd be at liberty to send me the sync log from Misc, let me know at ptsochantaris at me dot com and I'll happily take a look.

**Comment by BenRPeloton** [comment]
So I can't say for sure but it sounds like @bazbremner is in a similar situation to me, where the CODEOWNERS file in my project auto-assigns teams that I'm in as Reviewer for a PR that changes some area of the code, which results in a lot of noise. Trailer was very helpful previously for this as it would only show PRs that I specifically (And not my teams) were set as Assignee for (and not Reviewer). Starting in 1.8.8, it instead shows all PRs that a team I'm in is marked as Reviewer for. 

I imagine this is functionality that others want given the recent bug fix I originally commented on, but I can't find a way to separate items based on Assignee vs Reviewer. What I'd like to do is move all PRs assigned to one of my teams to "Participated" and all PRs assigned to me specifically to "Mine", which is what I assumed the "When something from all items is assigned to me/my teams" option in DIsplay did. 

All that being said, I'm still not sure if this is a bug and that is how it's supposed to work, or if it was never supposed to work that way and this is a feature request.

**Comment by ptsochantaris** [comment]
@BenRPeloton What ought to happen is that item assignment is handled by the options in the display tab. Being assigned as a reviewer to an item is handled by the options in the Reviews tab. If this isn’t what you’re seeing then there’s most probably a bug. If you can give me a rough idea of what your settings are and what the behaviour you expect is (vs what’s happening) I’ll definitely take a good look and try to solve any bug. (Or if some new feature help Trailer reduce your noise even more, we can address that as a feature request too ofcourse)

**Comment by BenRPeloton** [comment]
Okay, I understand what's happening now. The language in the Display tab confused me, I thought that "something from all items" being "assigned" to me or my team was referring to the "Assignee" section in a PR, and a PR being assigned for review was referring to the Reviewer section. Now that I've set the options in the Reviews tab set to this it's working as expected. Sorry for being dense!
<img width="276" alt="Screenshot 2023-08-28 at 5 20 32 PM" src="https://github.com/ptsochantaris/trailer/assets/48031214/0c8add19-9630-4946-b074-028a6dcbd799">

**Comment by ptsochantaris** [comment]
Ah, nice, I'm glad that's all it was. It seems that the text on these two tabs could use some improvement!

Can you think of some kind of messaging (or even re-arrangement) of those options that would have made it clearer which option does what? I'm thinking that for starters the text in the review tab could avoid using the term "assigned for review" and be something closer to:
```
When a PRs reviewers include...
 ... Me directly
 ... One of my teams
```
Which would avoid talking about "assignments" perhaps? Definitely open to suggestions from anyone with thoughts on this!

**Comment by bazbremner** [comment]
Hello again, sorry for the slow response - a long weekend, a couple of feverish days and parenting has meant I've only just got back around to commenting now.

To be clear the screenshot in the initial issue comment was lifted from BenRPeloton's post.

I now understand that this behaviour should be controlled by the "Reviews" section preferences, not "Display" - thanks for pointing that out, and sorry for the misunderstanding.

_However_, after looking again, I still believe there is a bug.

I've upgraded from 1.8.7 (which I was running as it doesn't exhibit the issue described here) to 1.8.10 (latest release at this point) and triggered a "Reload all data".

Despite setting both Display options to "Don't move it" and both Reviews options to "Don't Move It" 10 of the 14 PRs open on projects I'm watching are displayed as "Mine", when in reality is:

- 1 (draft) PR is mine
- 9 PRs have my team as an auto-assigned reviewer via the CODEOWNERs mechanism
- the 4 PRs not displaying as "Mine" have already been reviewed by other team member, hence adding them as the reviewer and removing my team (and the review state is not showing on those PRs, but I'm not sure if that's relevant here).

This is in disagreement with behaviour in 1.8.7 and earlier and my understanding of the Display and Review options.

I'd expect 1 PR as "Mine" and 13 under "All PRs"

I'm be happy to carry out any debugging steps, but unfortunately I can't share screenshots or API responses as this is against a private GHE instance (also probably worth mentioning, just in case that turns out to be relevant).

Again, current settings are:

<img width="939" alt="trailer-display" src="https://github.com/ptsochantaris/trailer/assets/173771/fad742d7-6fd6-4335-8ca0-06d9da64ed9a">

<img width="939" alt="trailer-reviews" src="https://github.com/ptsochantaris/trailer/assets/173771/3cecf32a-7754-4497-9724-cae32d0be0fa">

**Comment by ptsochantaris** [comment]
Hi @bazbremner and thanks for the feedback - no worries on the timing, we all have lives outside of code review :D 

It's interesting that you're seeing this behaviour by default. From what I understand, selecting "do nothing" still seems to do _something_ in the reviews tab. If you select _something else_ - for example, setting "...to my teams" to send the items to "Participated", does _that_ bit work OK? As you can suspect I'm trying to determine if this is an issue with the "do nothing" option specifically or perhaps a more general issue with routing based on review status.

PS. You shouldn't need to "Reload all" for the routing changes to take effect - just picking the new option should update the menu after a moment, but thanks for trying that out as well, just to be safe 👍

**Comment by ptsochantaris** [comment]
Thanks @bazbremner for the extremely detailed report! I'll start digging around that area. I _think_ the commit you linked to seems OK logic-wise - as the assigned review status is the subsequently used to resolve which section to send the item to, and the logic is that if you are direction mentioned, then it is treated by the logic in "...to me", or if the team slug is in the team assignments then it is treated by the logic in "...to my teams". Will dig further and keep you updated.

**Comment by ptsochantaris** [comment]
I've dug a bit and realised that, for one, there is (...yet another 🤦...) display problem in the reviews assignment menus in the macOS preferences window. This build corrects it, but you will need to go there and re-set your options, as they'll probably now point to the wrong values. Once that is out of the way, I'd be interested in seeing how this affects the results you're seeing @bazbremner - it may or may not be the core cause of the issue, but at least it's one less layer to dig through :)

[Trailer-1718.zip](https://github.com/ptsochantaris/trailer/files/12473022/Trailer-1718.zip)

**Comment by bazbremner** [comment]
@ptsochantaris thanks for the updated build - I've been running it this morning and early signs look extremely promising. 🎉 

All choices for Reviews -> "When a PR is assigned for review..." -> "...to my teams": does indeed place PRs with my team under the selected section as expected.

**Comment by ptsochantaris** [comment]
Excellent! Sounds like a step up from where we were at least, will put up an update later today 👍 Let's keep an eye on this, if you spot issue give a shout and I can dig more 👍 Thanks for your help in isolating this very annoying issue 🙏

**Comment by bazbremner** [comment]
@ptsochantaris thanks for releasing [1.8.11](https://github.com/ptsochantaris/trailer/releases/tag/1.8.11), since this appears to have fixed the issue, I'll close this off.

Thanks very much for your help and for Trailer generally. 👍

**Comment by ptsochantaris** [comment]
@bazbremner You're very welcome, and thanks again for your help in fixing this!
