### ISSUE TITLE
Put pull requests assigned to me in a separate Assigned section

### ISSUE THREAD

**Issue by nherzing** [ptsochantaris/trailer#65]
It would be nice to have an Assigned section where pull requests that are assigned to me would show up. Right now, they just show up under All Pull Requests which isn't very helpful.

**Comment by theKashyap** [comment]
What feature have you added to Sourcetree? I was looking for a solution to problem listed in OP. I'm on Sourcetree 2.x on Mac OSX, I see no "Display" tab under Preferences.
